### ISSUE TITLE
Interpolate operator

### ISSUE THREAD

**Issue by glopesdev** [dotnet/reactive#1006]
A common failure mode when using `Zip` on two reactive data streams is that one of the streams may have missing values (e.g. because of dropped packets). In these situations, it is often desirable to interpolate over the missing values to restore parity to the result of `Zip`.

Besides the `Zip` scenario, interpolation of missing values over a data stream is a useful operation over sequential data in general.

This proposal is for a new `Interpolate` operator with the following signature:

```c#
IObservable<TSource> Interpolate<TSource>(IObservable<TSource> source, Func<TSource, TSource, IEnumerable<TSource>> interpolator);
```

The operator takes a `source` and an `interpolator` function, which given the previous and current value, returns any missing intermediate values, if any. Any values returned by the interpolator will be injected in the result sequence, just before emitting the current value.

For example, consider the following marble diagrams:

```
S1                  ---a---b---d ---|
S2                  ---1---2---3---4---|
Zip(S1,S2)          ---(a,1)---(b,2)---(d,3)---|

Interpolate(S1)     ---a---b---cd---|
Zip(Interpolate,S2) ---(a,1)---(b,2)---(c,3)---(d,4)---|
```

Below I am including a reference implementation using standard reactive operators for consideration:

```c#
static IObservable<TSource> Interpolate<TSource>(IObservable<TSource> source, Func<TSource, TSource, IEnumerable<TSource>> interpolator)
{
    return Observable.Create<TSource>(observer =>
    {
        var hasPrevious = false;
        var previous = default(TSource);
        var sink = Observer.Create<TSource>(
            x =>
            {
                if (hasPrevious)
                {
                    foreach (var missing in interpolator(previous, x))
                    {
                        observer.OnNext(missing);
                    }
                }
                else hasPrevious = true;

                observer.OnNext(x);
                previous = x;
            },
            observer.OnError,
            observer.OnCompleted);
        return source.SubscribeSafe(sink);
    });
}
```

**Comment by akarnokd** [comment]
I think the `Interpolate` operator is too specific to your case to be included in Rx.NET proper. Luckily, as an extension method, it can live in any 3rd party library.

With `zip`, you need to decide when the sequence should. If all sources can extrapolate, they will eventually keep extrapolating unless stopped by some means. I.e., having a master sequence determine when the zip should end. Otherwise, you have to implement a custom `Zip` that automatically extrapolates its sources until all sources end up being extrapolated.

**Comment by akarnokd** [comment]
Closing as too specific and uncommon to be included in Rx.NET proper.
