### ISSUE TITLE
Possible to run System.Linq.Async AsParallel?

### ISSUE THREAD

**Issue by sdcb** [dotnet/reactive#1022]
Wondering if is it possible to run `Reactive.Linq.Async` AsParallel?
Such as: 
```csharp
await Enumerable.Range(1, 10)
    .ToAsyncEnumerable()
    .AsParallel()
    .SelectAwait(async x =>
    {
        await Task.Delay(500);
        return x;
    })..ToListAsync();
```

So that I can don't need to wait 10x0.5=5s to complete it, just like the LINQ code:
```csharp
Enumerable.Range(1, 10)
    .AsParallel()
    .AsOrdered()
    .Select(x =>
    {
        Thread.Sleep(500);
        return x;
    }).ToList();
```

**Comment by danielcweber** [comment]
Impossible already on a conceptual level I would guess: Async iterators are not supposed to run in parallel but rather, calls `MoveNext` must be serialized. But there's an easy way out: Use Reactive Extensions to convert the pull-based-sequence into a push-based one. Place a call to `ToObservable` right where you would put `AsParallel` and from there on, multiple elements may (asynchonously) be in flight at the same time (by using [this method](https://github.com/dotnet/reactive/blob/cc4b5eb76871e4e0429060ad826a4ae81304da78/Rx.NET/Source/src/System.Reactive/Linq/QueryLanguage.StandardSequenceOperators.cs#L231)).

Hope it helps.

**Comment by mungojam** [comment]
I believe you can do it like this:

```
await Enumerable.Range(1, 10)
          .Select(x => 
          Task.Delay(500)
     )
    .ToAsyncEnumerable()
    .SelectAwait(async x =>
    {
        await x;
    }).ToListAsync();
```

or something along those lines depending on the exact need. You might need to pull out a separate async function to replace the call to Task.Delay with what you actually need but you get the idea. It seems to work in my case.

**Comment by BrunoJuchli** [comment]
> I believe you can do it like this:
> 
> ```cs
> await Enumerable.Range(1, 10)
>           .Select(x => DoSomething(x))
>           .ToList() //to force all of the Tasks to start
>           .ToAsyncEnumerable()
>           .SelectAwait(async x => await x)
>           .ToListAsync();
> 
> async Task<int> DoSomething(int x) {
>         await Task.Run(() => Thread.Sleep(500)); //Just to replicate your example, but could use Task.Delay
>         return x;
> }
> ```
> 
> or something along those lines depending on the exact need. It seems to work in my case.

Imagine the numbers of elements the source enumerable (what is `Enumerable.Range(1, 10)` returns ) is out of your control:
what you do results in unbounded concurrency at `.ToList() // to force all of the Tasks to start` line.

IMO you should always (be able to) limit concurrency (number of parallel workers).

Also, your example introduced the concurrency on a non-`async` IEnumerable, not on an `IAsyncEnumerable`. 
You could also just have used `await Task.WhenAll(...)` on the tasks created, no need for using `IAsyncEnumerable`, at all.
