### ISSUE TITLE
Incorrect results on TestScheduler CreateHotObservable

### ISSUE THREAD

**Issue by Ripper555** [dotnet/reactive#1025]
The number of Recorded<Notification<int>> objects affects the result. This has to be a bug. The 454545 ticks simulates data at 22 Hz. The Buffer with TimeSpan should get the same result every time but doesn't.

```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reactive;
using System.Reactive.Linq;
using Microsoft.Reactive.Testing;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace TestSchedulerTests
{
    [TestClass]
    public class UnitTest1
    {
        [DataTestMethod]
        [DataRow(2000)]
        [DataRow(3000)]
        [DataRow(4000)]
        [DataRow(5000)]
        [DataRow(6000)]
        [DataRow(7000)]
        [DataRow(8000)]
        [DataRow(9000)]
        public void TestMethod1(int count)
        {
            var list = Enumerable.Range(1, count)
                .Select(o => new Recorded<Notification<int>>(o * 454545, 
                                             Notification.CreateOnNext(o)))
                .ToArray();
            var scheduler = new TestScheduler();
            var result = new List<int>();

            scheduler.CreateHotObservable(list)
                .Buffer(TimeSpan.FromSeconds(30), scheduler)
                .Subscribe(x => result.AddRange(x));

            scheduler.AdvanceTo(TimeSpan.FromSeconds(30).Ticks);

            Assert.AreEqual(660, result.Count);
        }
    }
}
```

![image](https://user-images.githubusercontent.com/2703264/64457600-a7d7ac00-d0b8-11e9-975f-8cf2c7c27a3e.png)

**Comment by akarnokd** [comment]
You have an integer overflow when setting the onNext timestamp: 5000 * 454545 = 2.272.725.000 > 2.147.483.647 so you get a bunch of negative timestamps which is by default considered as current time + 1 tick (t = 1 in this case) and a bunch of those happen before t = 454545, hence the reason you have more signals than expected.

Use `o * 454545L` to do a long multiply and the tests should pass.

**Comment by Ripper555** [comment]
Thank you. Dumb mistake on my part.
