### ISSUE TITLE
source.Delay(observable) throws NullReferenceException if source emits a value immediately

### ISSUE THREAD

**Issue by christopherpaul** [dotnet/reactive#1048]
The following code throws a `NullReferenceException`:

```C#
            var source = Observable.Return(1);
            var delayed = source.Delay(_ => Observable.Return(2));
            delayed.Subscribe(Console.Write); // NullReferenceException
```

This only seems to happen if `source` emits a value immediately on subscription.
The kind of observable used in the argument to `Delay` does not seem to make any difference.

System.Reactive v4.1.6
.NET Framework 4.7.2

**Comment by onovotny** [comment]
Any chance you can add a failing unit test with this using the virtual time scheduler?
