### ISSUE TITLE
Why does auto connect take an Action of IDisposable?

### ISSUE THREAD

**Issue by vitolpoc** [dotnet/reactive#1052]
When would this be called more than once?  Why not use a SingleAssignmentDisposable instead of an Action<IDisposable>?

The "minObservers" is more of a "total of all previous subscriptions", i.e.

var sub1 = consumer1.Subscribe();
sub1.Dispose();

var sub2 = consumer2.Subscribe();

// This is two subscribers, even though only one is "active", since it doesn't ever decrement the _count.

We also have a bug if we go over int.MaxValue subscriptions in the lifetime of the app, since it will overflow and then subscribe again... after quite some time I guess!

`internal sealed class AutoConnect<T> : IObservable<T>
    {
        private readonly IConnectableObservable<T> _source;
        private readonly int _minObservers;
        private readonly Action<IDisposable> _onConnect;
        private int _count;

        internal AutoConnect(IConnectableObservable<T> source, int minObservers, Action<IDisposable> onConnect)
        {
            _source = source;
            _minObservers = minObservers;
            _onConnect = onConnect;
        }

        public IDisposable Subscribe(IObserver<T> observer)
        {
            var d = _source.Subscribe(observer);

            if (Volatile.Read(ref _count) < _minObservers)
            {
                if (Interlocked.Increment(ref _count) == _minObservers)
                {
                    var c = _source.Connect();
                    _onConnect?.Invoke(c);
                }
            }
            return d;
        }
    }`

**Comment by akarnokd** [comment]
>  Why not use a SingleAssignmentDisposable

What if someone wants to put the connection's disposable into a CompositeDisposable, or a List, or some other data structure?
