### ISSUE TITLE
Why does auto connect take an Action of IDisposable?

### ISSUE THREAD

**Issue by DavidKiff** [dotnet/reactive#1053]
When would this be called more than once? Why not use a SingleAssignmentDisposable instead of an Action?

The "minObservers" is more of a "total of all previous subscriptions", i.e.

var sub1 = consumer1.Subscribe();
sub1.Dispose();

var sub2 = consumer2.Subscribe();

// This is two subscribers, even though only one is "active", since it doesn't ever decrement the _count.

Should AutoConnect mandate consumers need to provide an action or single assignment disposable?  It's currently optional and I can foresee many people not realizing they should be cleaning something up.

We also have a bug if we go over int.MaxValue subscriptions in the lifetime of the app, since it will overflow and then subscribe again... after quite some time I guess!

```
internal AutoConnect(IConnectableObservable<T> source, int minObservers, Action<IDisposable> onConnect)
    {
        _source = source;
        _minObservers = minObservers;
        _onConnect = onConnect;
    }

    public IDisposable Subscribe(IObserver<T> observer)
    {
        var d = _source.Subscribe(observer);

        if (Volatile.Read(ref _count) < _minObservers)
        {
            if (Interlocked.Increment(ref _count) == _minObservers)
            {
                var c = _source.Connect();
                _onConnect?.Invoke(c);
            }
        }
        return d;
    }
}
```

**Comment by akarnokd** [comment]
>  Why not use a SingleAssignmentDisposable

What if someone wants to put the connection's disposable into a CompositeDisposable, or a List, or some other data structure?

> We also have a bug if we go over int.MaxValue subscriptions in the lifetime of the app, since it will overflow and then subscribe again... after quite some time I guess!

Please read the source code:

```cs
if (Volatile.Read(ref _count) < _minObservers)
```

**Comment by DavidKiff** [comment]
They still can add it to what ever data structure they want?  The API implies it call "callback" more than once.  This would be explicit...

var subscription = new SingleAssignmentDisposable();

stream.AutoConnect(1, subscription);

var compositeDisposable = new CompositeDisposable(subscription).

**Comment by akarnokd** [comment]
Why is this a problem for you?

**Comment by DavidKiff** [comment]
I think it’s more the API is not overly clear in its intent.  

What if the action calls me back twice?  Do I need to dispose the previous one?  Do I need to keep a list of them?  

I had to dig through the code to work out it will never call me back twice, although perhaps it will in a future update?  Then I have broken code?

If it can only be assigned to once, it would appear the aptly named SingleAssignmentDisposable would be best suited? Consumers then don’t need to dig around in the code and protect against possible multiple calls.

**Comment by akarnokd** [comment]
Using `Action<IDisposable>` is the most broad way that allows dealing with the connection's `IDisposable`. You can ignore it, add it to a `CompositeDisposable`, assign it to a `MultiAssignmentDisposable`, store it in some field, etc.

As a library design, we have to consider broader aspects than most user would use in certain situations.
