### ISSUE TITLE
Unit and System.Reactive.Unit collision after latest VS and nugets updates

### ISSUE THREAD

**Issue by rhy-ama** [dotnet/reactive#1054]
**Target framework:**
.Net Core 2.2 (console app)

**Dependencies:**
System.Reactive 4.1.6

**Full list of packages installed**
Akavache 6.9.1
DynamicData 6.13.13
MathNetNumerics 4.8.1
Microsfty.Extensions.DependencyInjection 3.0.0.
ReactiveUI 10.3.6

**VisualStudio 2019 16.3.2**

Using the following

using System.Reactive;
using System;
using System.Reactive.Concurrency;

        public static IObservable<Either<Exception, Unit>> Poll<Unit>(
            TimeSpan interval,
            IScheduler scheduler)
        {
            return Observable.Create<Either<Exception, Unit>>(observer =>
            {
                return scheduler.ScheduleAsync(async (ctrl, ct) => {
                    while (!ct.IsCancellationRequested)
                    {
                        try
                        {
                            observer.OnNext(Either.Right<Exception, Unit>(Unit.Default));
                        }
                        catch (Exception ex)
                        {
                            observer.OnNext(Either.Left<Exception, Unit>(ex));
                        }
                        await ctrl.Sleep(interval, ct);
                    }
                });
            });
        }

results in "Observable does not exist in the current context". 

I see that [observable.create](https://docs.microsoft.com/en-us/previous-versions/dotnet/reactive-extensions/hh229114(v%3Dvs.103))  is in **System.Reactive.Linq**.

If I include System.Reactive.Linq, Unit.Default is no longer recognized and it appears there are two definitions for Unit, one from System.Reactive.Unit and another i can not identify. 

PS: Either class could be found [here](https://stackoverflow.com/questions/19547880/how-do-i-implement-polling-using-observables)

**Comment by danielcweber** [comment]
Guessing: The other `Unit` class is imported by the same library that imports `Either`. Right click on the "wrong" Unit class in the code, select "Go to definition" to see where it comes from.

**Comment by rhy-ama** [comment]
@danielcweber thank you for reply. you gave me the chance to try it out again.

the Either class is self-contained and uses no other classes/namespaces as you can see from the provided link. it is just a wrapper to handle errors, that in this case wraps around Unit return value.

the solution had a number of other projects targeting several platforms. as well as shared code base project. the project under compilation is as described. what worked for me was to unload all other projects in the solution, remove and re-install all nuggets. exit vs. clean up debug/release/obj directories. and re-open the solution. after these steps i could remove System.Reactive namespace prefix from Unit references. It seems like a VS issue caching assemblies in the latest VS release.
