### ISSUE TITLE
Namespace collision with DbSet of Ef core

### ISSUE THREAD

**Issue by aleGuardiola** [dotnet/reactive#1058]
The EntityFramework Core  DbSet<Entity> implements IEnumerable and IAsyncEnumerable as well what cause a collision because the extensions for IAsyncEnumerable are in the same namespace: "System.Linq", one solution can be changing the namespace for the IAsyncEnumerable extensions maybe something like "System.Linq.Async"

**Comment by onovotny** [comment]
Dup of #1057

The issue is that DbSet implements both of those interfaces and thus both sets of extension methods apply.

Closing as by design. You can use AsQueryable() to distinguish.

**Comment by aleGuardiola** [comment]
That will be quick fix but also I consider it is a limitation, because I cannot use the benefits of the IAsyncEnumerable of Ef core or probably other class or interface that support  both implementations.

**Comment by onovotny** [comment]
I would take it up with the EF team -- it's how they designed their type.

**Comment by SimonCropp** [comment]
fyi i reopened https://github.com/dotnet/reactive/issues/1057
