### ISSUE TITLE
xmldoc for System.Linq.Async

### ISSUE THREAD

**Issue by Daniel15** [dotnet/reactive#1063]
Would it be possible to add xmldocs for `System.Linq.Async`? Currently Visual Studio does not show any intellisense for these methods, which makes it tricky to tell exactly what some of them do.

![image](https://user-images.githubusercontent.com/91933/67744529-ff223a80-f9de-11e9-8543-f9515ec23429.png)

**Comment by akarnokd** [comment]
There isn't any docs in the source at all.

@onovotny can you setup System.Linq.Async to have VS complain about missing docs on public members as well as ensure the build does generate XML?

**Comment by onovotny** [comment]
We can have it complain about missing docs, the bigger issue is time. We need someone to create the method docs first.

**Comment by akarnokd** [comment]
Indeed there are a lot of methods and probably dozens of PRs worth of changes. I have some free time this week to start working on them. Btw, which sln is for System.Linq.Async `Ix.NET` or `Ix.Async.NET` now?

**Comment by onovotny** [comment]
It looks like `Ix.Async.NET` is a subset of `Ix.NET` that only has the main libraries and tests. `Ix.NET` has the benchmark tests and the reference assembly projects too.

**Comment by akarnokd** [comment]
Closing via #1098 & #1099.
