### ISSUE TITLE
Merge method for IAsyncEnumerable

### ISSUE THREAD

**Issue by Daniel15** [dotnet/reactive#1064]
Is there a "merge" method for `IAsyncEnumerable` that will combine multiple `IAsyncEnumerable`s into a single `IAsyncEnumerable` that yields items in the order they're received? I thought something like this would be in `System.Linq.Async`, but I don't see anything for it.

**Comment by akarnokd** [comment]
Do you mean running multiple sources at once but still getting items in order as with `Concat`?

There is a `ConcatEager` operator in [my extensions project](https://github.com/akarnokd/async-enumerable-dotnet#available-sources).

**Comment by Daniel15** [comment]
Say I have two `IAsyncEnumerable`s, `a` and `b`, that produce items like this, at the specified times:

`a`:
- 00:00: `hello`
- 00:05: `world`

`b`:
- 00:01: `foo`
- 00:02: `bar`
- 00:06: `baz`

I want to get a single enumerable that produces items in this order:
- `hello`
- `foo`
- `bar`
- `world`
- `baz`

I'll take a look at your project; maybe it does what I need.

**Comment by akarnokd** [comment]
That looks like plain `AsyncEnumerableEx.Merge`.

**Comment by Daniel15** [comment]
@akarnokd - Works great, thanks!

```
public static async Task Main(string[] args)
{
	var sources = new[]
	{
		A(),
		B(),
	};

	await foreach (var item in async_enumerable_dotnet.AsyncEnumerable.Merge(sources))
	{
		Console.WriteLine(item);
	}
}

private static async IAsyncEnumerable<string> A()
{
	yield return "hello";
	await Task.Delay(5000);
	yield return "world";
}

private static async IAsyncEnumerable<string> B()
{
	await Task.Delay(1000);
	yield return "foo";
	await Task.Delay(1000);
	yield return "bar";
	await Task.Delay(4000);
	yield return "baz";
}
```

Output:
```
hello
foo
bar
world
baz
```

Do you think that `.Merge` method will ever be merged into `System.Linq.Async`? It's very useful, and I imagine will be a pretty common operation.

**Comment by akarnokd** [comment]
There is an official one with different internals: https://github.com/dotnet/reactive/blob/305d381dcc46c5966e7260e0959b3083846bf05f/Ix.NET/Source/System.Interactive.Async/System/Linq/Operators/Merge.cs#L13

**Comment by Daniel15** [comment]
Oops, I missed that as it's in the `System.Interactive.Async` assembly and I only had `System.Linq.Async` installed 😅
