### ISSUE TITLE
System.Reactive.xml in Release/Publish directory

### ISSUE THREAD

**Issue by virzak** [dotnet/reactive#1066]
Any idea if `System.Reactive.xml` is needed for production to run smoothly? It is the only xml related to packages that is being output. I tried to remove it and everything worked fine. Trying to minimize the distribution size.

**Comment by virzak** [comment]
Was able to prevent by adding

```xml
  <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
    <AllowedReferenceRelatedFileExtensions>
        .pdb;
        .dll.config
    </AllowedReferenceRelatedFileExtensions>
  </PropertyGroup>
```

to the project file, BTW

**Comment by onovotny** [comment]
The XML are the docs for IntelliSense. They're not needed at runtime for your app.
