### ISSUE TITLE
How Interval skips exceptions

### ISSUE THREAD

**Issue by yedajiang44** [dotnet/reactive#1068]
code
```
            Observable.Interval(TimeSpan.FromMilliseconds(1))
                .ObserveOn(TaskPoolScheduler.Default)
                .SubscribeOn(TaskPoolScheduler.Default)
                .Subscribe(x =>
                {
                    if (x == 5)
                        throw new Exception("asd");
                    Console.WriteLine(x);
                }, e =>
                {
                    Console.WriteLine(e);
                });
```
I want to get
```
1
2
3
4
Exception ....
6
7
8
....
```

**Comment by danielcweber** [comment]
You can't. When an OnNext handler throws an execption to Rx, the sequence will terminate. You can try SubscribeSafe, it'll probably route the exception to your OnError handler, but that's it. You won't observe 6, 7, 8, ....

**Comment by yedajiang44** [comment]
thanks for your reply！but there is no other solution to get the results？

**Comment by danielcweber** [comment]
You could write your own Subscribe extension that would catch all the exceptions from OnNext and route it to OnError. You would violate Rx grammar though, have a look at section 4.1 in the [design guidelines](https://download.microsoft.com/download/4/E/4/4E4999BA-BC07-4D85-8BB1-4516EC083A42/Rx%20Design%20Guidelines.pdf). It says that an OnCompleted/OnError notification should be the last notification in any sequence.

**Comment by quinmars** [comment]
> but there is no other solution to get the results？

The `IObservable<T>` is the push-model counterpart to the `IEnumerable<T>`, so semantically your example could be translated to:

```csharp
try
{
    foreach (var x in Enumerable.Range(0, 10))
    {
        if (x == 5)
            throw new Exception("asd");
        Console.WriteLine(x);
    }
}
catch (Exception e)
{
    Console.WriteLine(e);
}
```

But what you want is:

```csharp
foreach (var x in Enumerable.Range(0, 10))
{
    try
    {
        if (x == 5)
            throw new Exception("asd");
        Console.WriteLine(x);
    }
    catch (Exception e)
    {
        Console.WriteLine(e);
    }
}
```

So write it that way!

```csharp
Observable.Interval(TimeSpan.FromMilliseconds(1))
    .ObserveOn(TaskPoolScheduler.Default)
    .SubscribeOn(TaskPoolScheduler.Default)
    .Subscribe(x =>
    {
        try
        {
            if (x == 5)
                throw new Exception("asd");
            Console.WriteLine(x);
        }
        catch (Exception e)
        {
            Console.WriteLine(e);
        }
    });
```

**Comment by yedajiang44** [comment]
> > but there is no other solution to get the results？
> 
> The `IObservable<T>` is the push-model counterpart to the `IEnumerable<T>`, so semantically your example could be translated to:
> 
> ```cs
> try
> {
>     foreach (var x in Enumerable.Range(0, 10))
>     {
>         if (x == 5)
>             throw new Exception("asd");
>         Console.WriteLine(x);
>     }
> }
> catch (Exception e)
> {
>     Console.WriteLine(e);
> }
> ```
> 
> But what you want is:
> 
> ```cs
> foreach (var x in Enumerable.Range(0, 10))
> {
>     try
>     {
>         if (x == 5)
>             throw new Exception("asd");
>         Console.WriteLine(x);
>     }
>     catch (Exception e)
>     {
>         Console.WriteLine(e);
>     }
> }
> ```
> 
> So write it that way!
> 
> ```cs
> Observable.Interval(TimeSpan.FromMilliseconds(1))
>     .ObserveOn(TaskPoolScheduler.Default)
>     .SubscribeOn(TaskPoolScheduler.Default)
>     .Subscribe(x =>
>     {
>         try
>         {
>             if (x == 5)
>                 throw new Exception("asd");
>             Console.WriteLine(x);
>         }
>         catch (Exception e)
>         {
>             Console.WriteLine(e);
>         }
>     });
> ```

I got it ,thanks~
