### ISSUE TITLE
Error while building

### ISSUE THREAD

**Issue by Sattasundar** [dotnet/reactive#1073]
I am getting error while building the Xamarin solution in VS 2017;

**Severity	Code	Description	Project	File	Line	Suppression State
Error		Can not resolve reference: `System.Threading.Tasks.Extensions`, referenced by `System.Reactive`. Please add a NuGet package or assembly reference for `System.Threading.Tasks.Extensions`, or remove the reference to `System.Reactive`**	

Let me know how to solve this issue.

**Comment by onovotny** [comment]
What solution are you trying to build? With what version of what references?
