### ISSUE TITLE
ToObservable in SelectMany dispatch null object when it cannot be possible

### ISSUE THREAD

**Issue by Odonno** [dotnet/reactive#1077]
Well, I just refactored some code today using a `SelectMany` with a `enumerable.ToObservable()` inside. 

That worked fine but I just ran in an issue where the following `GroupBy` sometimes receive a `null` object... It is weird because in my process, it cannot be possible to receive `null` values because they are filtered upfront..

I just fixed it with a 

```cs
.Where(operation => operation != null) // To fix a bug in SelectMany
```

Does anyone has an explanation? And maybe a better solution?

**Comment by akarnokd** [comment]
We can't help without the relevant code parts you forgot to share. Please provide all relevant code.

**Comment by Odonno** [comment]
Oh, sorry. Yes, I understand that it can difficult without repoducible code. The current repository is private for now but we will make it public soon so I'll publish a link to the source code when it's done.

**Comment by Odonno** [comment]
So, we switched from `Buffer` to `GroupByUntil` because it better suits our use case. Since then, the unnecessary `Where` is no longer needed. I guess there was something we did wrong after the `Buffer`.
