### ISSUE TITLE
Question: How does observable lives with task pool?

### ISSUE THREAD

**Issue by IdeaHunter** [dotnet/reactive#1085]
Imagine we have following function:
```cs
public IObservable<T> SubscribeAsync<T>(string channel)
{
    return Observable.Create<T>((observer, task) =>
    {
        return redis.SubscribeAsync(channel, (ch, msg) =>
        {
            var value = JsonConvert.DeserializeObject<T>(msg);
            observer.OnNext(value);
        });
    });
}
```
would be called from async code from asp.net core like that:
```cs
private Task<IObservable<object>> SubscribeNewMessages(ResolveEventStreamContext arg)
{
       var pubSub = arg.Source;
       return pubsub.SubscribeAsync("messages");
}
```
In this situation we are capturing async thread in a sync code (bad) and using this sync code to call async method (even worse).

I tried to search for something like:
```cs
Task<IObservable<TResult>> CreateAsync<TResult>(Func<IObserver<TResult>, CancellationToken, Task> subscribeAsync);
```
but unable to find one.

I have no idea how Rx lives with async code and why does it have sync method that can be called from async method and how well this lives with task pool and i dont see a reason of absence of async create method. 

Can you please explain:
1)  why do we call async code from sync method?
2) how well Rx lives in context of async code?
3) how valid is my attempt to handle async code the way i did it?

**Comment by akarnokd** [comment]
> why do we call async code from sync method?

I don't understand what you mean.

> how well Rx lives in context of async code?

There are methods that take or return `Task` and you have `ConfigureAwait()` to specify if the context should be captured or not. `System.Reactive.Concurrency.TaskPoolScheduler.Default` is provided to run observables and processing stages on the task pool via `ObserveOn`, `SubscribeOn` or any operator that takes an `IScheduler`.

> how valid is my attempt to handle async code the way i did it?

Not sure why you have `Task<IObservable<object>>`, i.e., the creation of an `IObservable` will happen sometime in the future? This is somewhat uncommon usage to my knowledge. What's the problem you are trying to solve. If there is a subscription side-effect you want to avoid, use `SubscribeOn` with the task pool scheduler.

**Comment by IdeaHunter** [comment]
> System.Reactive.Concurrency.TaskPoolScheduler.Default is provided to run observables and processing stages on the task pool via ObserveOn, SubscribeOn or any operator that takes an IScheduler.

Oh, thanks, that was big part of my question!
when i first saw `Observable.Create<T>` it created impression of absence of asynchronous (async /await) api because neither of methods were returning `Task<Observable<>>` and having a sync api on an webserver and especially on socket connection is bad because it could just take away task from task pool(and associated thread)
https://github.com/davidfowl/AspNetCoreDiagnosticScenarios/blob/master/AsyncGuidance.md#avoid-using-taskresult-and-taskwait
Also i saw a lot of locks in implementation which made my assumption of synchronous even more strong.

But from your comment i see i was mistaken.

@akarnokd Thanks a lot
