### ISSUE TITLE
Ix await foreach with GroupBy? 

### ISSUE THREAD

**Issue by alexdresko** [dotnet/reactive#1086]
This seems like something I could do in Rx, but my Ix experiments aren't working. 

I'm using a `System.Threading.Channels.Channel` to generate the AsyncEnumerable, and this works as expected (I'm not grouping in this example). 

(side note: I ain't no wizard, so I'll happily accept if this is just plain wrong)

```
async Task Main()
{
	var channel = Channel.CreateUnbounded<int>(new UnboundedChannelOptions {
		SingleReader = false,
		SingleWriter = false
	});
	
	var rand = new Random();
	
	var writing = Enumerable
		.Range(0, 10)
		.Select(async e => {
			await Task.Delay(rand.Next(1, 5) * 1000);
			var w = rand.Next(0, 10);
			w.Dump($"writing for index {e}");
			await channel.Writer.WriteAsync(w);
		});
					
	async Task Read(int reader) {
		await foreach (var a in channel.Reader.ReadAllAsync())
		{
			a.Dump($"reading with reader {reader}");
		}
	}

	var reading = Enumerable
		.Range(0, 2)
		.Select(async p => await Read(p));
	
	"waiting".Dump();
	await Task.WhenAll(reading.Concat(writing));
}
```

Essentially, the output looks like:

```
* writing for index 3
	5
* writing for index 1
	4
* writing for index 5
	5
* reading with reader 1
	4
* reading with reader 0
	5
* reading with reader 0
	5
* writing for index 9
	8
* writing for index 8
	0
* reading with reader 0
	0
* reading with reader 1
	8
* writing for index 0
	4
* reading with reader 1
	4
* writing for index 2
	3
* writing for index 4
	5
* writing for index 7
	8
* writing for index 6
	8
* reading with reader 0
	3
* reading with reader 1
	5
* reading with reader 0
	8
* reading with reader 1
	8
```

So I tried changing the `Read` function to use `GroupBy` like this:

```
	async Task Read(int reader) {
		await foreach (var a in channel.Reader.ReadAllAsync()**.GroupBy(r => r % 2 == 0)**)
		{
			a.Dump($"reading with reader {reader}");
		}
	}
```

...but none of the reads ever dump. All I see in the output are the "writing" lines from the previous output. 

What's up with `GroupBy`? Am I not using it correctly? I tried things like `.Where` and `.Distinct` and those work fine here. It's just `GroupBy` that doesn't produce any results.

**Comment by alexdresko** [comment]
Wait... Does the channel writer have to complete before GroupBy works?  This simplified example does work, but only with the `channel.Writer.Complete();` line. Otherwise, it just waits as before. 

```
async Task Main()
{
	var channel = Channel.CreateUnbounded<int>(new UnboundedChannelOptions
	{
		SingleReader = false,
		SingleWriter = false
	});
	
	var xs = new List<int> { 1, 2, 3, 4, 5, 6, 7, 8 };
	
	foreach (var x in xs)
	{
		await channel.Writer.WriteAsync(x);
	}
	channel.Writer.Complete();

	await foreach (var y in channel.Reader.ReadAllAsync().GroupBy(x => x % 2 == 0))
	{
		y.Dump();
	}
}
```

**Comment by akarnokd** [comment]
I'm not 100% certain but IAsyncEnumerable::GroupBy looks like it is not live and does all the grouping before it releases the groups upon upstream completion.

**Comment by alexdresko** [comment]
@akarnokd That's what it looks like. How did you figure out that it's not "live"? 

Is there another construct I can use? I basically need a queue of lists, where the list can be appended to up to the point that the queue item is processed.  I'm having trouble translating that concept to a well known c# construct, or even a library that does what I need.

**Comment by akarnokd** [comment]
The source code doesn't look anything like [my version](https://github.com/akarnokd/async-enumerable-dotnet/blob/master/async-enumerable-dotnet/impl/GroupBy.cs) that is live and pushes out group items as soon as there is demand for them.

**Comment by alexdresko** [comment]
@akarnokd So where's the disconnect? Where did your version come from and why is the official version not live?  Yours sounds exactly like what I need.

**Comment by akarnokd** [comment]
> So where's the disconnect? 

Not sure what you mean.

> Where did your version come from

It is an intuitive implementation based on my experience with backpressure-enabled reactive flows.

> why is the official version not live?

Probably because if you don't consume a group in the live version, both the main and the other groups hang. That's a risk not taken by the standard implementation.

**Comment by quinmars** [comment]
> why is the official version not live?

If you consider the following query:

```csharp
var list = Enumerable.Range(1, 12).GroupBy(i => i % 2).Concat();
```
The result will be: `1, 3, 5, 7, 9, 11, 2, 4, 6, 8, 10, 12`. Obviously there needs to be buffering somewhere in the pipeline to get that result. In LINQ to objects (Ix) `GroupBy` is eagerly so it builds a dictionary and once the sequence is completed it will yield the collected content. In the reactive world, however, `GroupBy` is lazy and the buffering happens in the `Concat` operator. The point is there needs to be buffering or eagerly evaluation somewhere else the sequence would hang as @akarnokd pointed out.

Async.Ix is an async one-to-one translation of Ix, so it uses the same semantics as Ix (and not like Rx).
