### ISSUE TITLE
Which operators should I use to split one IEnumerable for two consumers

### ISSUE THREAD

**Issue by 3da** [dotnet/reactive#1089]
IEnumerable<T> producer = ProcessDocuments();

void Consume1(IEnumerable<T> sequence);

void Consume2(IEnumerable<T> sequence);

Currently I use 
`
Consume1(producer);
Consume2(producer);
`
But it makes twice more iterations for producer.

How to consume twice but with only once run producer?

**Comment by danielcweber** [comment]
Not really within the scope of Reactive Extensions, but simple answer: You can't. If you don't want to iterate producer twice, iterate it once with ToArray(), then share the resulting array.

**Comment by 3da** [comment]
Small note: Consume1 and Consume2 works parallel. ToArray with take all available memory so not acceptable.

**Comment by akarnokd** [comment]
`IEnumerable` is for synchronous/blocking processing so you can't just process one `IEnumerable` on two threads. There is no good way to coordinate between enumerators in a synchronous fashion.

You can turn that `IEnumerable` into an `IObservable` and use `Publish(Func)` to share it for a limited time. Something like this could work:

```cs
producer.ToObservable()
.Publish(shared =>
    Observable.Merge(
        Observable.Defer(() =>
        {
            Consume1(shared.ToEnumerable());
            return Observable.Empty<int>();
        }).SubscribeOn(Scheduler.Default),
        Observable.Defer(() =>
        {
            Consume2(shared.ToEnumerable());
            return Observable.Empty<int>();
        }).SubscribeOn(Scheduler.Default)
    )
)
.Subscribe()
```

Note however that there is no backpressure with this so if `producer` generates items really fast, you'll end up with a lot of excess memory usage.

**Comment by 3da** [comment]
But what if use IAsyncEnumerable instead of IEnumerable?

**Comment by akarnokd** [comment]
Ix.Async doesn't feature any form of publishing, multicasting or sharing an `IAsyncEnumerable` afaik. [My library](https://github.com/akarnokd/async-enumerable-dotnet) has `Publish` like with `Observable.Publish`.

**Comment by 3da** [comment]
> [My library](https://github.com/akarnokd/async-enumerable-dotnet) has `Publish` like with `Observable.Publish`.

Very interesting. I will learn something about your library.
