### ISSUE TITLE
Empty target .NETCoreApp3.0 in 4.2.0 nuget package.

### ISSUE THREAD

**Issue by jmderuty** [dotnet/reactive#1090]
Hello,

The System.Reactive Nuget package contains a target for .NETCoreApp3.0, but the target is empty. 

Apparently MSBuild seems able to cope correctly with that and automatically switches to .NetStandard2.0 for .NETCoreApp3.0 projects.
However, our project use Nuget.Commands to restore Nuget packages as part of an update mechanism and as a .NETCoreApp3.0 target exists, it selects it instead of .NetStandard2.0 and fails to find System.Reactive.dll

Is it expected?

**Comment by akarnokd** [comment]
Indeed the `system.reactive.4.2.0.nupkg` is missing files in its `netcoreapp3.0` directory, however, there are other directories with 3.0 content.

![image](https://user-images.githubusercontent.com/1269832/69423748-3dcdbb00-0d27-11ea-9e34-151d0b15ec37.png)

**Comment by jmderuty** [comment]
Ok, I think I understand now: The provided targets file switches between the  netcoreapp3.0 version in build or the netstandard version depending if we are running with WPF or not.

```
<Project>
  <PropertyGroup>
    <UseWindowsRxVersion Condition="'$(UseWpf)' == 'true' OR '$(UseWindowsForms)' == 'true'" >true</UseWindowsRxVersion>
    <UseWindowsRxVersion Condition="'$(UseWindowsRxVersion)' == '' " >false</UseWindowsRxVersion>
  </PropertyGroup>
  <ItemGroup>
    <Reference Condition="'$(UseWindowsRxVersion)' == 'true' "  Include="$(MSBuildThisFileDirectory)..\..\build\netcoreapp3.0\System.Reactive.dll" />
    <Reference Condition="'$(UseWindowsRxVersion)' != 'true' "  Include="$(MSBuildThisFileDirectory)..\..\lib\netstandard2.0\System.Reactive.dll" />

    <FrameworkReference Condition="'$(UseWindowsRxVersion)' == 'true' " Include="Microsoft.WindowsDesktop.App" />
  </ItemGroup>
</Project>
```
I understand the need, I'm pretty sure the only way to make that work is to use msbuild to restore.

**Comment by onovotny** [comment]
Correct, this is a workaround for the lack of a way to differentiate between .NET Core 3 on Windows with the Desktop SDK vs .NET Core 3 without. 

You do need to use either `dotnet restore` or `msbuild /restore` for it to work correctly.

**Comment by akarnokd** [comment]
Closing as resolved.
