### ISSUE TITLE
Backer in Readme has invalid SSL certificate

### ISSUE THREAD

**Issue by jmrnilsson** [dotnet/reactive#1091]
The anime-dude has invalid cert which causes chrome to put out a scary message; Someone might be trying to steal your digits. This is also an advert btw.

**Suggestion**
Remove link until cert is fixed.
Let backer know certs point to something else.

https://pronama.co.jp/?utm_source=opencollective&utm_medium=github&utm_campaign=reactiveui

**Comment by onovotny** [comment]
Fixed, thanks.
