### ISSUE TITLE
Wiki: Contributing code

### ISSUE THREAD

**Issue by akarnokd** [dotnet/reactive#1108]
### Introduction

Hello and thank you for contributing to dotnet/reactive. Before you proceed with your contribution:

- Please make sure your contribution is in line with the project's [licensing model](https://github.com/dotnet/reactive/blob/master/LICENSE) and
your employment allows you to contribute to open source.

- Please sign the [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/reactive?pullRequest=1101) in case the CLA bot asks you
for being a new contributor.

- Please make sure you target the `master` branch when creating the PR.

### Forking and branching

In order to contribute to the project, you have to fork it, make changes in your local fork and branch, then propose a so-called Pull Request. The following sections will guide you through the steps:

#### 1. Fork `dotnet/reactive` (once)

On GitHub, navigate to `dotnet/reactive` and create a fork if you haven't done so:

![image](https://user-images.githubusercontent.com/1269832/70239404-89428900-176b-11ea-8f65-be2026ca750e.png)

#### 2. Clone the `origin/master` branch (once)

Usually, the `master` branch gets outdated in user forks, therefore, it is highly recommended you checkout the project's git repository, then add a new reference to your fork. (Unfortunately, this has to be done from command line because Visual Studio does not support adding remotes from the UI.)

```
git clone https://github.com/dotnet/reactive.git

cd reactive

git remote add myfork https://github.com/user/reactive.git
```

Replace `user` with your user name.

#### 3. Refresh the `master` branch

In Visual Studio, right click on the branch icon on the lower right and select **Pull**:

![image](https://user-images.githubusercontent.com/1269832/70241272-120ef400-176f-11ea-860b-0b3bb8183b1c.png)

For command line:

```
git pull origin/master
```

#### 4. Create your branch.

In the same popup menu, select **New branch...**, 

![image](https://user-images.githubusercontent.com/1269832/70241492-67e39c00-176f-11ea-81ee-217686a55ba0.png)

then specify a custom name indicating what you try to do within, then click **Create branch**:

![image](https://user-images.githubusercontent.com/1269832/70241229-fe638d80-176e-11ea-9d40-f78385320311.png)

For command line

```
git checkout -b [name_of_your_new_branch]
```

#### 5. Apply your modifications

Now you are in your own branch and you can perform the changes you wanted on the appropriate subproject. `dotnet/reactive` has several solution files, of which the two most important ones are `System.Reactive.sln` for Rx.NET and `Ix.NET.sln` for Ix and Async Ix:

![image](https://user-images.githubusercontent.com/1269832/70242171-a9c11200-1770-11ea-85dc-da57c07edfe8.png)

The layout of the projects can be confusing at times, so here are some hints where to find the various components usually targeted for contributions:

**`System.Reactive`** solution

- The standard operator descriptions and documentations are located in the **`System.Reactive`** 
 subproject under the `Linq` directory in files named like `Observable.X.cs` where `X` is the name of the operator category. If you don't know which category an operator belongs to, open one such file, then use the method dropdown to navigate to the correct one.
- Operators are intercepted through an interface indirection. Each operator method must be listed in `Linq/IQueryLanguage.cs` and their implementation invoked in `Linq/QueryLanguage.X.cs` where `X` is again the operator category.
- The concrete operator implementations should be placed in their own file named after the operator (overloads can be toghether) under the `Linq/Observable/` directory.
- Tests are also placed in individual files based on the operator name and can be found in the **`Tests.System.Reactive`** subproject under the `Tests/Linq/Observable/` directory.

**`Ix.NET`** solution

- The project does not host implementations for the standard **`System.Linq`** operators anymore as these have been moved into the CoreFx library some time ago.
- Extra operators are implemented in their own file in the **`System.Interactive`** subproject under the `Linq/Operators` directory. However, there is no separate main partial class but each operator file is a partial class of `EnumerableEx`. Each such partial class hosts the entire operator implementation. Individual operator test files are located in the `System.Interactive.Tests` subproject under the `System/Linq/Operators` directory.
- Standard async operators are implemented in their own file in the **`System.Linq.Async`** subproject  under the `Linq/Operators` directory. Each file is a partial class of `Linq/AsyncEnumerable.cs` . Each such partial class hosts the entire operator implementation. Individual operator test files are located in the `System.Linq.Async.Tests` subproject under the `System/Linq/Operators` directory.
- Extra async operators are implemented in their own file in the **`System.Interactive.Async`** subproject  under the `Linq/Operators` directory. Each file is a partial class of `Linq/AsyncEnumerableEx.cs` . Each such partial class hosts the entire operator implementation. Individual operator test files are located in the `System.Interactive.Async.Tests` subproject under the `System/Linq/Operators` directory.

Here are some general hints to consider:

- **Changing documentation of an operator.** If you are fixing or adding documentation, please make sure both the `Observable.X.cs` and `Qbservable.X.cs` files get an update for Rx.NET.

- **Fixing or adding an operator.** Please include unit tests that verify the behavior of the new feature. Please make sure the code coverage is reasonably high with the new code. Depending on the feature, you may want to include actual multi-threaded test cases to verify the correct async behavior, however, please be mindful of the time such tests take and try to stay under a few seconds.

- **Adding an operator.** Including all above, you'll have to update the API approvals file in `Rx.NET\Source\tests\Tests.System.Reactive.ApiApprovals\Api\ApiApprovalTests.Core.approved.cs`

- **Please run all tests of the solution.** This makes sure nothing broke accidentally. Some unit tests may fail though:
  - `ApiApprovalTests`: you'll have to add the new method signatures to `ApiApprovalTests.Core.approved.cs`
  - `ArgumentValidationTest`: operators on `Observable` and `ObservableEx` have to be implemented with null checks for their parameters. The test failure message should indicate which overloads and arguments are missing validation code.
  - `LicenseHeaderTest`: new files should include the standard license header of the project (including the empty newline after the text):
```
// Licensed to the .NET Foundation under one or more agreements.",
// The .NET Foundation licenses this file to you under the Apache 2.0 License.",
// See the LICENSE file in the project root for more information.",

```

#### 6. Commit your changes

Once you are done with the changes, you must commit them so git knows about it. Either use the **Commit** button (pencil icon) on the bottom right corner:

![image](https://user-images.githubusercontent.com/1269832/70243211-71223800-1772-11ea-996c-a64feb7a10c7.png)

then specify the short commit message:

![image](https://user-images.githubusercontent.com/1269832/70243337-b181b600-1772-11ea-96a1-a6463b337073.png)

The pick **Commit All**. (Please do not pick any of the other options there as the push has to be manually routed to your branch, see the next step.)

or from command line

```git
git commit -m "short change description here"
```

#### 7. Push the changes

In Visual Studio, pick the **Unpushed commit** (up arrow) on the bottom right to begin the process:

![image](https://user-images.githubusercontent.com/1269832/70243693-61572380-1773-11ea-8cd9-9dd56b08b3c5.png)

In the synchronization dialog, select the **Push** option from the menu, then select your remote name you specified in step 2) (`myfork`), then select the branch name you gave in step 4) 

![image](https://user-images.githubusercontent.com/1269832/70243929-dcb8d500-1773-11ea-98b3-edade9ec2f97.png)

or on the command line

```
git push myfork name_of_your_new_branch
```

Once ready, press the **Push** button and you are done locally. Now you have to propose these
changes by opening a pull request on GitHub.

### Opening a Pull Request

When you are ready to submit your changes, go to the [Pull requests](https://github.com/dotnet/reactive/pulls) page and once your branch pops up, click on the green "Compare & Pull request"

![image](https://user-images.githubusercontent.com/1269832/70239253-41bbfd00-176b-11ea-9bed-cee37e33e340.png)

Then, depending on your kind of your contribution, please read the welcome text or the following related subsection and fill in the comments textbox:

![image](https://user-images.githubusercontent.com/1269832/70244456-b8a9c380-1774-11ea-98fb-fbdb00a404c6.png)

When you write the PR description, please consider the following points depending on the type of your contribution:

#### Bugfix

- Please describe what and how the bug manifested itself and what kind of fix did you implement. Practically, you are writing these descriptions for the search engines so others can find the resolution easier.
- Please reference the related issue(s) to the original bug report (example: `Fixes #X`, `Resolves #X`). Note that some behaviors are by design and are not bugs. If you are unsure, please open an [issue](https://github.com/dotnet/reactive/issues) first.

- Please include the relevant unit test(s) that verify the fix works. It is recommended you write the unit test(s) first to see they failed before your fix; however, there is no need to post a PR to demonstrate this failure stage. Please post in a state where the issue is resolved.

#### Enhancement

- Please consider opening an [issue](https://github.com/dotnet/reactive/issues) first to discuss the kind and impact of the enhancement, if such an issue doesn't exist yet.  Also please check if there was a consensus about accepting such an enhancement.
- Please describe how, what and why the enhancement is implemented. Practically, you are writing these descriptions for the search engines so others can find the change details easier.
- Please reference the related issue(s) to the original issue report (example: `Fixes #X`, `Resolves #X`).
- Please include the relevant unit test(s) or benchmark(s) that show or verify the enhancement works.

#### Feature request

- We strongly recommend opening an [issue](https://github.com/dotnet/reactive/issues) first to discuss the nature and impact of the request first. If such an issue already exists, please check if there was a consensus and approval for accepting a contribution.
- Please describe what request is about, how it works in general and what possible corner cases it or the user should consider. Please include some basic usage examples of the important components and/or overloads. Practically, you are writing these descriptions for the search engines so others can find out about the new feature easier.
- Please reference the related issue(s) to the original issue report (example: `Resolves #X`).
- Please include unit tests that verify the behavior of the new feature. Please make sure the code coverage is reasonably high with the new code.
- Depending on the feature, you may want to include actual multi-threaded test cases to verify the correct async behavior, however, please be mindful of the time such tests take and try to stay under a few seconds.

**Comment by bupbetocvang** [comment]
#

> ### Giới thiệu
> Xin chào và cảm ơn bạn đã đóng góp cho dotnet / Reactive. Trước khi bạn tiến hành đóng góp của mình:
> 
> * Vui lòng đảm bảo đóng góp của bạn phù hợp với [mô hình cấp phép](https://github.com/dotnet/reactive/blob/master/LICENSE) của dự án và 
>   việc làm của bạn cho phép bạn đóng góp cho nguồn mở.
> * Vui lòng ký [Thỏa thuận cấp phép cộng tác viên](https://cla.dotnetfoundation.org/dotnet/reactive?pullRequest=1101) trong trường hợp bot CLA yêu cầu bạn 
>   là cộng tác viên mới.
> * Vui lòng đảm bảo bạn nhắm mục tiêu `master`chi nhánh khi tạo PR.
> 
> ### Ngã ba và phân nhánh
> Để đóng góp cho dự án, bạn phải rẽ nhánh nó, thực hiện các thay đổi trong nhánh và nhánh của địa phương, sau đó đề xuất cái gọi là Yêu cầu kéo. Các phần sau đây sẽ hướng dẫn bạn qua các bước:
> 
> #### 1. Ngã ba `dotnet/reactive`(một lần)
> Trên GitHub, điều hướng đến `dotnet/reactive`và tạo một ngã ba nếu bạn chưa làm như vậy:
> 
> ![hình ảnh](https://user-images.githubusercontent.com/1269832/70239404-89428900-176b-11ea-8f65-be2026ca750e.png)
> 
> #### 2. Nhân bản `origin/master`chi nhánh (một lần)
> Thông thường, `master`chi nhánh bị lỗi thời trong các nhánh người dùng, do đó, chúng tôi khuyên bạn nên kiểm tra kho git của dự án, sau đó thêm một tham chiếu mới vào ngã ba của bạn. (Thật không may, điều này phải được thực hiện từ dòng lệnh vì Visual Studio không hỗ trợ thêm điều khiển từ xa từ UI.)
> 
> ```
> git clone https://github.com/dotnet/reactive.git
> 
> cd reactive
> 
> git remote add myfork https://github.com/user/reactive.git
> ```
> 
> Thay thế `user`bằng tên người dùng của bạn.
> 
> #### 3. Làm mới `master`chi nhánh
> Trong Visual Studio, nhấp chuột phải vào biểu tượng nhánh ở phía dưới bên phải và chọn **Kéo** :
> 
> ![hình ảnh](https://user-images.githubusercontent.com/1269832/70241272-120ef400-176f-11ea-860b-0b3bb8183b1c.png)
> 
> Đối với dòng lệnh:
> 
> ```
> git pull origin/master
> ```
> 
> #### 4. Tạo chi nhánh của bạn.
> Trong cùng một menu bật lên, chọn **Chi nhánh mới ...** ,
> 
> ![hình ảnh](https://user-images.githubusercontent.com/1269832/70241492-67e39c00-176f-11ea-81ee-217686a55ba0.png)
> 
> sau đó chỉ định một tên tùy chỉnh cho biết những gì bạn cố gắng thực hiện trong đó, sau đó nhấp vào **Tạo chi nhánh** :
> 
> ![hình ảnh](https://user-images.githubusercontent.com/1269832/70241229-fe638d80-176e-11ea-9d40-f78385320311.png)
> 
> Đối với dòng lệnh
> 
> ```
> git checkout -b [name_of_your_new_branch]
> ```
> 
> #### 5. Áp dụng sửa đổi của bạn
> Bây giờ bạn đang ở trong chi nhánh của riêng mình và bạn có thể thực hiện các thay đổi bạn muốn trên tiểu dự án phù hợp. `dotnet/reactive`có một số tệp giải pháp, trong đó hai tệp quan trọng nhất `System.Reactive.sln`dành cho Rx.NET và `Ix.NET.sln`Ix và Async Ix:
> 
> ![hình ảnh](https://user-images.githubusercontent.com/1269832/70242171-a9c11200-1770-11ea-85dc-da57c07edfe8.png)
> 
> Bố cục của các dự án đôi khi có thể gây nhầm lẫn, vì vậy đây là một số gợi ý để tìm các thành phần khác nhau thường được nhắm mục tiêu cho các đóng góp:
> 
> **`System.Reactive`** dung dịch
> 
> * Các mô tả hành tiêu chuẩn và các tài liệu được đặt tại các 
>   tiểu dự án thuộc thư mục trong tập tin có tên như nơi là tên của hạng mục nhà điều hành. Nếu bạn không biết toán tử thuộc về loại nào, hãy mở một tệp như vậy, sau đó sử dụng menu thả xuống phương thức để điều hướng đến đúng loại.**`System.Reactive`**`Linq``Observable.X.cs``X`
> * Nhà khai thác đang bị chặn thông qua một giao diện gián tiếp. Mỗi phương pháp điều hành phải được liệt kê trong `Linq/IQueryLanguage.cs`và thực hiện của họ viện dẫn trong `Linq/QueryLanguage.X.cs`nơi `X`lại là loại nhà điều hành.
> * Việc triển khai toán tử cụ thể nên được đặt trong tệp riêng của chúng được đặt tên theo toán tử (quá tải có thể được hoàn thành) trong `Linq/Observable/`thư mục.
> * Các thử nghiệm cũng được đặt trong các tệp riêng lẻ dựa trên tên toán tử và có thể được tìm thấy trong **`Tests.System.Reactive`**tiểu dự án trong `Tests/Linq/Observable/`thư mục.
> 
> **`Ix.NET`** dung dịch
> 
> * Dự án không lưu trữ các triển khai cho các **`System.Linq`**toán tử tiêu chuẩn nữa vì chúng đã được chuyển vào thư viện CoreFx một thời gian trước đây.
> * Toán tử bổ sung được thực hiện trong tệp riêng của chúng trong **`System.Interactive`**tiểu dự án dưới `Linq/Operators`thư mục. Tuy nhiên, không có lớp một phần chính riêng biệt mà mỗi tệp toán tử là một lớp một phần của `EnumerableEx`. Mỗi lớp một phần như vậy lưu trữ toàn bộ thực hiện toán tử. Các tệp kiểm tra toán tử riêng lẻ được đặt trong `System.Interactive.Tests`tiểu dự án trong `System/Linq/Operators`thư mục.
> * Các toán tử async tiêu chuẩn được triển khai trong tệp riêng của chúng trong **`System.Linq.Async`**tiểu dự án trong `Linq/Operators`thư mục. Mỗi tập tin là một lớp một phần của `Linq/AsyncEnumerable.cs`. Mỗi lớp một phần như vậy lưu trữ toàn bộ thực hiện toán tử. Các tệp kiểm tra toán tử riêng lẻ được đặt trong `System.Linq.Async.Tests`tiểu dự án trong `System/Linq/Operators`thư mục.
> * Các toán tử async bổ sung được triển khai trong tệp riêng của chúng trong **`System.Interactive.Async`**tiểu dự án trong `Linq/Operators`thư mục. Mỗi tập tin là một lớp một phần của `Linq/AsyncEnumerableEx.cs`. Mỗi lớp một phần như vậy lưu trữ toàn bộ thực hiện toán tử. Các tệp kiểm tra toán tử riêng lẻ được đặt trong `System.Interactive.Async.Tests`tiểu dự án trong `System/Linq/Operators`thư mục.
> 
> Dưới đây là một số gợi ý chung để xem xét:
> 
> * **Thay đổi tài liệu của một nhà điều hành. **Nếu bạn đang sửa chữa hoặc thêm tài liệu, vui lòng đảm bảo cả tệp `Observable.X.cs`và `Qbservable.X.cs`tệp đều được cập nhật cho Rx.NET.
> * **Sửa chữa hoặc thêm một toán tử. **Vui lòng bao gồm các bài kiểm tra đơn vị xác minh hành vi của tính năng mới. Vui lòng đảm bảo mức độ bao phủ mã cao một cách hợp lý với mã mới. Tùy thuộc vào tính năng, bạn có thể muốn bao gồm các trường hợp thử nghiệm đa luồng thực tế để xác minh hành vi không đồng bộ chính xác, tuy nhiên, vui lòng lưu ý thời gian các thử nghiệm như vậy mất và cố gắng duy trì trong vài giây.
> * **Thêm một toán tử. **Bao gồm tất cả ở trên, bạn sẽ phải cập nhật tệp phê duyệt API trong`Rx.NET\Source\tests\Tests.System.Reactive.ApiApprovals\Api\ApiApprovalTests.Core.approved.cs`
> * **Hãy chạy tất cả các bài kiểm tra của giải pháp. **Điều này đảm bảo không có gì vô tình phá vỡ. Một số bài kiểm tra đơn vị có thể thất bại mặc dù:
>   
>   * `ApiApprovalTests`: bạn sẽ phải thêm chữ ký phương thức mới vào `ApiApprovalTests.Core.approved.cs`
>   * `ArgumentValidationTest`: Nhà khai thác trên `Observable`và `ObservableEx`phải được thực hiện với kiểm tra null cho các thông số của họ. Thông báo lỗi kiểm tra sẽ cho biết quá tải và đối số nào đang thiếu mã xác thực.
>   * `LicenseHeaderTest`: các tệp mới phải bao gồm tiêu đề giấy phép tiêu chuẩn của dự án (bao gồm dòng mới trống sau văn bản):
> 
> ```
> // Licensed to the .NET Foundation under one or more agreements.",
> // The .NET Foundation licenses this file to you under the Apache 2.0 License.",
> // See the LICENSE file in the project root for more information.",
> ```
> 
> #### 6. Cam kết thay đổi của bạn
> Khi bạn đã thực hiện xong các thay đổi, bạn phải cam kết chúng để git biết về nó. Sử dụng nút **Cam kết** (biểu tượng bút chì) ở góc dưới bên phải:
> 
> ![hình ảnh](https://user-images.githubusercontent.com/1269832/70243211-71223800-1772-11ea-996c-a64feb7a10c7.png)
> 
> sau đó xác định tin nhắn ngắn cam kết:
> 
> ![hình ảnh](https://user-images.githubusercontent.com/1269832/70243337-b181b600-1772-11ea-96a1-a6463b337073.png)
> 
> Chọn **Cam kết Tất cả** . (Vui lòng không chọn bất kỳ tùy chọn nào khác ở đó vì việc đẩy phải được chuyển thủ công đến chi nhánh của bạn, xem bước tiếp theo.)
> 
> hoặc từ dòng lệnh
> 
> ```
> git commit -m "short change description here"
> ```
> 
> #### 7. Đẩy các thay đổi
> Trong Visual Studio, chọn **cam kết Unpushed** (mũi tên lên) ở dưới cùng bên phải để bắt đầu quá trình:
> 
> ![hình ảnh](https://user-images.githubusercontent.com/1269832/70243693-61572380-1773-11ea-8cd9-9dd56b08b3c5.png)
> 
> Trong hộp thoại đồng bộ hóa, chọn tùy chọn **Đẩy** từ menu, sau đó chọn tên từ xa bạn đã chỉ định trong bước 2) ( `myfork`), sau đó chọn tên chi nhánh bạn đã đưa ra trong bước 4)
> 
> ![hình ảnh](https://user-images.githubusercontent.com/1269832/70243929-dcb8d500-1773-11ea-98b3-edade9ec2f97.png)
> 
> hoặc trên dòng lệnh
> 
> ```
> git push myfork name_of_your_new_branch
> ```
> 
> Khi đã sẵn sàng, nhấn nút **Đẩy** và bạn đã hoàn thành cục bộ. Bây giờ bạn phải đề xuất những 
> thay đổi này bằng cách mở yêu cầu kéo trên GitHub.
> 
> ### Mở một yêu cầu kéo
> Khi bạn đã sẵn sàng để gửi các thay đổi của mình, hãy chuyển đến trang [Yêu cầu kéo](https://github.com/dotnet/reactive/pulls) và khi chi nhánh của bạn bật lên, nhấp vào "So sánh & Kéo yêu cầu" màu xanh lá cây
> 
> ![hình ảnh](https://user-images.githubusercontent.com/1269832/70239253-41bbfd00-176b-11ea-9bed-cee37e33e340.png)
> 
> Sau đó, tùy thuộc vào loại đóng góp của bạn, vui lòng đọc văn bản chào mừng hoặc tiểu mục liên quan sau đây và điền vào hộp văn bản nhận xét:
> 
> ![hình ảnh](https://user-images.githubusercontent.com/1269832/70244456-b8a9c380-1774-11ea-98fb-fbdb00a404c6.png)
> 
> Khi bạn viết mô tả PR, vui lòng xem xét các điểm sau tùy thuộc vào loại đóng góp của bạn:
> 
> #### Vá lỗi
> * Vui lòng mô tả những gì và làm thế nào lỗi xuất hiện và cách khắc phục bạn đã thực hiện. Thực tế, bạn đang viết những mô tả này cho các công cụ tìm kiếm để những người khác có thể tìm thấy độ phân giải dễ dàng hơn.
> * Vui lòng tham khảo (các) vấn đề liên quan đến báo cáo lỗi ban đầu (ví dụ : `Fixes #X`, `Resolves #X`). Lưu ý rằng một số hành vi là do thiết kế và không phải là lỗi. Nếu bạn không chắc chắn, xin vui lòng mở một [vấn đề](https://github.com/dotnet/reactive/issues) đầu tiên.
> * Vui lòng bao gồm (các) thử nghiệm đơn vị có liên quan để xác minh sửa chữa hoạt động. Bạn nên viết (các) bài kiểm tra đơn vị trước để thấy chúng thất bại trước khi sửa lỗi của bạn; tuy nhiên, không cần thiết phải đăng bài PR để chứng minh giai đoạn thất bại này. Xin vui lòng gửi trong một tình trạng mà vấn đề được giải quyết.
> 
> #### Tăng cường
> * Vui lòng xem xét mở một [vấn đề](https://github.com/dotnet/reactive/issues) trước để thảo luận về loại và tác động của việc tăng cường, nếu vấn đề đó chưa tồn tại. Ngoài ra, vui lòng kiểm tra xem có sự đồng thuận về việc chấp nhận tăng cường như vậy không.
> * Vui lòng mô tả cách thức, những gì và tại sao việc tăng cường được thực hiện. Thực tế, bạn đang viết những mô tả này cho các công cụ tìm kiếm để những người khác có thể tìm thấy các chi tiết thay đổi dễ dàng hơn.
> * Vui lòng tham khảo (các) vấn đề liên quan đến báo cáo vấn đề ban đầu (ví dụ : `Fixes #X`, `Resolves #X`).
> * Vui lòng bao gồm (các) bài kiểm tra đơn vị có liên quan hoặc (các) điểm chuẩn hiển thị hoặc xác minh công việc nâng cao.
> 
> #### Yêu cầu tính năng
> * Chúng tôi thực sự khuyên bạn nên mở một [vấn đề](https://github.com/dotnet/reactive/issues) trước để thảo luận về bản chất và tác động của yêu cầu trước. Nếu một vấn đề như vậy đã tồn tại, vui lòng kiểm tra xem có sự đồng thuận và chấp thuận cho chấp nhận đóng góp hay không.
> * Vui lòng mô tả những gì yêu cầu là về, làm thế nào nó hoạt động nói chung và những trường hợp góc có thể nó hoặc người dùng nên xem xét. Vui lòng bao gồm một số ví dụ sử dụng cơ bản của các thành phần quan trọng và / hoặc quá tải. Thực tế, bạn đang viết những mô tả này cho các công cụ tìm kiếm để những người khác có thể tìm hiểu về tính năng mới dễ dàng hơn.
> * Vui lòng tham khảo (các) vấn đề liên quan đến báo cáo vấn đề ban đầu (ví dụ `Resolves #X`:).
> * Vui lòng bao gồm các bài kiểm tra đơn vị xác minh hành vi của tính năng mới. Vui lòng đảm bảo mức độ bao phủ mã cao một cách hợp lý với mã mới.
> * Tùy thuộc vào tính năng, bạn có thể muốn bao gồm các trường hợp thử nghiệm đa luồng thực tế để xác minh hành vi không đồng bộ chính xác, tuy nhiên, vui lòng lưu ý thời gian các thử nghiệm như vậy mất và cố gắng duy trì trong vài giây.

**Comment by akarnokd** [comment]
@bupbetocvang Why did you translate this to vietnamese?

**Comment by akarnokd** [comment]
Created the wiki page: https://github.com/dotnet/reactive/wiki/Contributing-Code
