### ISSUE TITLE
Different behavior when subscribing an Observable with a sync/async subscriber

### ISSUE THREAD

**Issue by Smoovsky** [dotnet/reactive#1117]
Hi all,

I'm new to this library (as well as to reactive programming).

I got this snippet:
```csharp
using (var watcher = new FileSystemWatcher())
            {
                Directory.CreateDirectory("some path here");
                watcher.Path = "some path here";
                watcher.IncludeSubdirectories = true;
                watcher.NotifyFilter = NotifyFilters.FileName;
                watcher.Filter = "*.csv";

                Observable
                .FromEventPattern<FileSystemEventArgs>(watcher, "Created"
                // ,Scheduler.CurrentThread 
                )
                .Subscribe(_ => NewCsvEventHandler(_.Sender, _.EventArgs).Wait()); // does not work
                // or .Subscribe(async _ => await NewCsvEventHandler(_.Sender, _.EventArgs)); // does work

                watcher.EnableRaisingEvents = true;
```

When the subscriber is async, everything works fine, but when it's synchronous, It seems all following events are dropped if the first handler does not finish in-time. I don't know the reason.

I want the subscriber to be "blocking", meaning the next file event is not processed until the previous one is finished, even if there are many events that arrive at the same time(of course I don't want to drop any event too). What shall I do right in this case with reactive library?

Thanks for helping.

**Comment by apobekiaris** [comment]
assuming your NewCsvEventHandler(_.Sender, _.EventArgs) returns a task try this, no need to await anything

```cs
using (var watcher = new FileSystemWatcher())
            {
                Directory.CreateDirectory("some path here");
                watcher.Path = "some path here";
                watcher.IncludeSubdirectories = true;
                watcher.NotifyFilter = NotifyFilters.FileName;
                watcher.Filter = "*.csv";

                Observable
                .FromEventPattern<FileSystemEventArgs>(watcher, "Created"
                // ,Scheduler.CurrentThread 
                )
.SelectMany(_=>NewCsvEventHandler(_.Sender, _.EventArgs))
                .Subscribe()

                watcher.EnableRaisingEvents = true;
```

**Comment by Smoovsky** [comment]
> assuming your NewCsvEventHandler(_.Sender, _.EventArgs) returns a task try this, no need to await anything
> 
> ```cs
> using (var watcher = new FileSystemWatcher())
>             {
>                 Directory.CreateDirectory("some path here");
>                 watcher.Path = "some path here";
>                 watcher.IncludeSubdirectories = true;
>                 watcher.NotifyFilter = NotifyFilters.FileName;
>                 watcher.Filter = "*.csv";
> 
>                 Observable
>                 .FromEventPattern<FileSystemEventArgs>(watcher, "Created"
>                 // ,Scheduler.CurrentThread 
>                 )
> .SelectMany(_=>NewCsvEventHandler(_.Sender, _.EventArgs))
>                 .Subscribe()
> 
>                 watcher.EnableRaisingEvents = true;
> ```

Would you share some insights please?

What shall I do if I don't want concurrency, to handle the events one after the other?
Thanks.

**Comment by apobekiaris** [comment]
your post is not well formed so hard to guess but what you want is to merge two signals, so a possible way for this is the [SelectMany](http://reactivex.io/documentation/operators/flatmap.html) operator.

**Comment by apobekiaris** [comment]
>What shall I do if I don't want concurrency, to handle the events one after the other?

Concat operator or a simple google search

**Comment by apobekiaris** [comment]
Merge operator is also a good fir here or even Switch

**Comment by apobekiaris** [comment]
just avoid awaits u do not need to await just create and combine signals, when both are ready u can get your emit without awaits

**Comment by Smoovsky** [comment]
> just avoid awaits u do not need to await just create and combine signals, when both are ready u can get your emit without awaits

Alright, thanks.
Time to give up, a concurrent dictionary and constantly polling it will do the job.

I tried Switch, Concat, read about SelectMany and ManySelect, spent entire Sunday afternoon Googling and testing.
I only have one observable, but returning itself in Switch doesn't seems to be a solution.

Perhaps it's just I'm dumb.

Thanks for help anyway.

**Comment by danielcweber** [comment]
@Smoovsky Contrary to what @apobekiaris suggested, `SelectMany` won't wait on the downstream OnNext-handler task to finish before passing in the next value, so it won't serialize calls to your event-handling-routine in `NewCsvEventHandler`.

There's two ways you could go: Either protect calls to `NewCsvEventHandler` (which I assume to return a `Task`) by an asynchronous lock. Just as you would do with an ordinary `lock(...) {...}`, but asynchronously. The `SemaphoreSlim` can do this for you, check out [this blog post on its usage](https://blog.cdemi.io/async-waiting-inside-c-sharp-locks/).

If you like the reactive paradigm and would like to go a bit deeper into the notions of push-based vs. pull-based-streams ([which have become a first-class-citizen in C# 8](https://csharp.christiannagel.com/2019/03/20/asyncstreams/)), you could import `System.Interactive.Async`  and convert the `IObservable` that you have to an `IAsyncEnumerable` and conveniently `foreach` over that. 

Be aware, however that both proposed methods don't really handle backpressure. If the change-events from that FileSystemWatcher keep coming faster then you can process them in serial, you might end up with a problem. I assume that what you want to do in `NewCsvEventHandler` is sufficiently simple to not be an issue.
