### ISSUE TITLE
ValueTask and adoption of System.Linq.Async

### ISSUE THREAD

**Issue by zvolkov** [dotnet/reactive#1119]
We are a large US company having implemented our own version of async LINQ a little while ago (using a copy of what was future IAsyncEnumerable design, with our enumerators using async/await). Now we have upgraded to C# 8 and are looking into switching over to System.Linq.Async. However during our trial run we ran into the following difficulty:

Your -Await methods take selector functions and predicates that return ValueTask<T>. This is a nice optimization, however, wouldn't it mean that our existing async LINQ code would have to wrap the outputs of their lambdas with `new ValueTask<T>(lambdasReturnValue)`?

Is there some trick that we missed that would make ValueTask<T> more easily compatible with async lambdas and async methods returning Task<T>?

**Comment by akarnokd** [comment]
I don't think there is any automatic conversion available. You could either propagate the type change to those functions and have them now return `ValueTask<T>` or define extension method overloads that do the wrapping for you before calling this library's operators.

**Comment by danielcweber** [comment]
If you were previously using lambdas inside a System.Linq.Async-operator like this

`Operator(x => SomeTaskReturningMethod())`

and you're now faced with the operator signature requesting for a `Func<T, ValueTask<R>>` you should be golden with

`Operator(async x => await SomeTaskReturningMethod())`.

**Comment by zvolkov** [comment]
Oh, so async lambdas automatically return ValueTask when needed? That's super nice.

**Comment by danielcweber** [comment]
Does that solve the issue ?

**Comment by zvolkov** [comment]
Yes, this ticket can be closed - thanks a lot!
