### ISSUE TITLE
Split out System.Windows.Forms references away from System.Reactive and into a separate Desktop package

### ISSUE THREAD

**Issue by michal-ciechan** [dotnet/reactive#1124]
#### Feature request

> Which next library version (i.e., patch, minor or major)? 

Major?, as it most likely would be a breaking change due classes/methods being moved out/around.

> What are the platform(s), environment(s) and related component version(s)?

.NET Framework System.Reactive at least 4.2.2+ (Checked 4.2.2 and 4.3.2)

> How commonly is this feature needed (one project, several projects, company-wide, global)?

Causing audit issues Company-wide on any projects using Rx in any Full Framework service code (e.g. AspNetCore 2.x).

> Please describe the feature.

Would like to see the Windows.Forms references moved out of the main System.Reactive library and into their own NuGet package. We are getting audit issues as SonarQube is complaining that all of our server side projects should be using STA Thread attributes as we have a reference to Windows.Forms.

Yes we are ignoring the error, but still think it is worth moving out into their own package.

**Comment by clairernovotny** [comment]
To set expectations, this is not going to change until .NET 5. .NET 5 will enable the following:

- `net5.0`: Effectively the .NET Core version today
- `net5.0-windows`: The version with WPF/WinForms stuff in it

Your project, a website, would be `net5.0` and thus get the reference without WPF/WinForms in it. 

We'll get a preview out as soon as there's a .NET 5 SDK that supports these new TFMs

**Comment by Thaina** [comment]
As for me I think this also cause problem with godot html build

**Comment by clairernovotny** [comment]
Closing as this is handled in .NET 5 with a `net5.0-windows10.0.19041` target that's separate from the `net5.0` version.

**Comment by AigioL** [comment]
I'm using it **avaloniaui** and **C#/WinRT** and **SelfContained true** publish  

[C#/WinRT](https://docs.microsoft.com/en-us/windows/uwp/csharp-winrt/net-projection-from-cppwinrt-component#edit-the-project-file-to-execute-cwinrt) Must use **net5.0-windows10.0.19041.0**  

But I don't need it WinForms And WPF  

However, the documents I have published contain these two items, Now it's included, which makes my published assembly very large   

I found it in checking dependencies ```system.reactive``` WinForms is referenced  

I see that ```build\netcoreapp3.1\System.Reactive.targets``` has code for checking dependency, but net5.0 does not. Can you send a new version to fix this problem
