### ISSUE TITLE
Throttle with maximum time overload.

### ISSUE THREAD

**Issue by JohanLarsson** [dotnet/reactive#113]
Like this:
http://stackoverflow.com/a/30761373/1069200

**Comment by akarnokd** [comment]
Sounds like https://github.com/dotnet/reactive/issues/395 .

**Comment by JohanLarsson** [comment]
Similar but slightly different semantics. For practical purposes #395 would be fine.
I often use this for things like buffering saving state to disk.

**Comment by danielcweber** [comment]
Assuming that #395 would do the trick, I close this. @JohanLarsson Please reopen if still relevant and elaborate on the difference of semantics of your proposal.
