### ISSUE TITLE
CoreRT build never finishes.

### ISSUE THREAD

**Issue by woachk** [dotnet/reactive#1133]
#### Bug

> Which library version?
4.3.0-preview-* (ran dotnet add package System.Reactive -v "4.3.0-preview*" after adding the preview NuGet feed.)

> What are the platform(s), environment(s) and related component version(s)?
macOS Catalina

> What is the use case or problem?
.NET CoreRT build.

> What is the expected outcome?
Working successfully.

> What is the actual outcome?
Takes forever and never finishes.

> Part of the CoreRT ILC debug output:

[log.txt](https://github.com/dotnet/reactive/files/4114259/log.txt)

`

**Comment by danielcweber** [comment]
What's the exact version you end up with? Don't use a preview because there's no preview newer than the latest release. The AOT-compilation bug you're experiencing should be fixed with the latest release.

**Comment by danielcweber** [comment]
Checking....no, the latest of these fixes has not been released yet.

@onovotny Could you please publish a preview from master?

**Comment by woachk** [comment]
> What's the exact version you end up with? Don't use a preview because there's no preview newer than the latest release. The AOT-compilation bug you're experiencing should be fixed with the latest release.

System.Reactive                     4.3.0-preview*     4.3.0-preview.90

**Comment by FoggyFinder** [comment]
Any news about date of next release ?

**Comment by hez2010** [comment]
Ping. Any updates? It blocks Avalonia to be built by CoreRT.

**Comment by clairernovotny** [comment]
I can get a release out shortly, it'll be 4.4.x, can you confirm that the latest fixes things for you? It's `System.Reactive -version 4.3.0-preview.162` in the CI Artifacts feed.

**Comment by clairernovotny** [comment]
Would you be able to submit a PR to fix that? That'd be the fastest way to get a release out with the fix.

**Comment by hez2010** [comment]
@clairernovotny PR sent and all tests passed in my environment.

**Comment by clairernovotny** [comment]
4.4.0-preview.1 is in the CI feed if you can try it and verify that things work as expected on CoreRT?

**Comment by hez2010** [comment]
Yes, now it works as expected.

**Comment by teobugslayer** [comment]
@hez2010, please help me! I've added a NuGet reference to System.Reactive 4.4.1 to my project and CoreRT still never finishes the build and I can see the infinite type recursion in the output log. What did you do to make it work?

**Comment by hez2010** [comment]
> @hez2010, please help me! I've added a NuGet reference to System.Reactive 4.4.1 to my project and CoreRT still never finishes the build and I can see the infinite type recursion in the output log. What did you do to make it work?

You need to use nuget package lock file to fix version of System.Reactive to 4.4.1
