### ISSUE TITLE
AddRange() for CompositeDisposable

### ISSUE THREAD

**Issue by JohanLarsson** [dotnet/reactive#115]
I think it would be nice even if it is a trivial extension method.
The consensus in chat was that it would be bloat.
Asking what you think before writing a PR.

**Comment by akarnokd** [comment]
What is the expected signature and behavior with this extension. Does this have to be in Rx.NET?

**Comment by JohanLarsson** [comment]
A signature like:
```cs
public void AddRange(IEnumerable<IDisposable> collection)
```

Probably makes sense.
Keeping it similar to `List<T>.AddRange()`. Been a while since I had a need for this so I'm happy to close the issue.

**Comment by akarnokd** [comment]
I see. I'd say PR welcome.

**Comment by akarnokd** [comment]
Closing due to lack of interest or follow-up PR.
