### ISSUE TITLE
Wiki Page "Building Testing Debugging" Incomplete

### ISSUE THREAD

**Issue by ecb29** [dotnet/reactive#1152]
The following wiki page was vandalized:

https://github.com/dotnet/reactive/wiki/Building-Testing-and-Debugging

I have replaced it with TBD text, as the original was also blank.

If desired, it might be nice to flesh it out?

**Comment by danielcweber** [comment]
Thanks a lot 👍 

>If desired, it might be nice to flesh it out?

Sure, much appreciated. Go ahead.

**Comment by ecb29** [comment]
Sure, installing VS now, I can write up at least a basic series of steps.
