### ISSUE TITLE
CombineLatest with more than 2 values of different types

### ISSUE THREAD

**Issue by Odonno** [dotnet/reactive#1155]
#### Feature request

I just found that the `CombineLatest` operator allows us to use a `IEnumerable<TSource>` which is fine or we can use a `<TFirst, TSecond, TResult>` which can be really useful in my current case. 

However, I want to consume more than 2 `Observable` with different values, how am I supposed to do that?

Thanks for your help.

**Comment by akarnokd** [comment]
There should be overloads for 3..16 argument variants: [CombineLatest.Generated.cs](https://github.com/dotnet/reactive/blob/master/Rx.NET/Source/src/System.Reactive/Linq/Observable/CombineLatest.Generated.cs#L15)

**Comment by Odonno** [comment]
Ah, yes. It seems to be. Thanks for your answer.
