### ISSUE TITLE
Observable.Return prevents value GC until whole sequence disposed

### ISSUE THREAD

**Issue by aguahombre** [dotnet/reactive#1210]
I have noticed that Observable.Return keeps a reference to the value passed after it has been forwarded to the observer. This prevents the value being GCed. 

Take this extreme example:
```
using System;
using System.Reactive.Linq;

namespace ObservableReturn
{
    class Program
    {
        static void Main(string[] args)
        {
            using var subscription = Observable.Return(new byte[0x1000000])
               .Concat(Observable.Never<byte[]>())
               .Subscribe(x => Console.WriteLine(x.Length));

            Console.ReadKey();
            GC.Collect();
            Console.ReadKey();
        }
    }
}
```

The large initial byte array is not GCed while the app is running.
Here is the memory dump taken at the second ReadKey.
![image](https://user-images.githubusercontent.com/17591364/81575551-12a35a80-939f-11ea-8ebb-fff9452b48d8.png)

I would expect the byte array to have been GCed at the second ReadKey.

A fix would be to null the value reference held in Observable.Return after it is passed to the observer.OnNext method ensuring it is no longer referenced.

This example used RX v4.4.1 running in .netcore 3.1 console app.

**Comment by danielcweber** [comment]
An observable can be subscribed to any number of times. So Observable.Return must hold on to the value, it can't null it at any time. Also, it obviously can't determine that it's only going to be subscribed to once, as in your code. Not a bug.
