### ISSUE TITLE
WinUI 3 CoreDispatcherScheduler

### ISSUE THREAD

**Issue by tomasfabian** [dotnet/reactive#1230]
#### Question / Feature request
Rx does not have a `System.Reactive.Concurrency.CoreDispatcherScheduler` for WinUI 3.0 preview . It should be a wrapper for Windows.UI.Core.CoreDispatcher. Are there any plans to add it to Rx in .NET 5?

In the Rx repository I found DispatcherSchedulers only for UWP and WPF/WinForms (.Net Framework/.Net Core 3.1). 

Thank you very much

**Comment by clairernovotny** [comment]
Yes, we plan to support WinUI once things are further along.

**Comment by tomasfabian** [comment]
Great @clairernovotny, thank you for your very quick response :)

**Comment by visionarylab** [comment]
ReactiveUI don't have support for UWP's multi windows. Any guidance here?

`                clock.Tick.Select(second => $"{second}s")
                    .ObserveOn(RxApp.MainThreadScheduler)
                    .Subscribe(elapsed => Elapsed = elapsed)
                    .DisposeWith(disposables);`

We have to write replacement of RxApp.MainThreadScheduler for UWP (Multi-instance windows architecture)

**Comment by clairernovotny** [comment]
I would recommend filing an issue in the ReactiveUI repo.

**Comment by bartdesmet** [comment]
Rx 5.0 should have the necessary foundational pieces. For the layers on top, please check with ReactiveUI.

**Comment by tomasfabian** [comment]
Thank you very much @bartdesmet and @clairernovotny
