### ISSUE TITLE
OnNext when using IgnoreElements

### ISSUE THREAD

**Issue by unitrix0** [dotnet/reactive#1245]
Why does the Observable that is returned from `IgnoreElements` have a `OnNext` delegate when it is never called? Or did I something wrong here?

**Comment by bartdesmet** [comment]
Everything is statically typed as `IObservable<T>` and `IObserver<T>`, so the three `On*` methods will always show up. We're not adding special types for one-off operators such as `IgnoreElements` that do not use some of the `On*` methods. The compositional nature of Rx would suffer as well; by having all operators return `IObservable<T>`, they can be composed with other operators that accept an `IObservable<T>`.
