### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by thosylve1** [dotnet/reactive#1251]
#### Bug
Hi, 
I created, the following short C# program containing a memory leak. The result seems to be connected to how Rx.NET works internally. It seems to me that this is incorrect behaviour, but maybe you can explain why it is not - otherwise, I report this issue.

class Program
    {
        private static int _counter = 0;
        private static WeakReference<Subject<string>> weakRef;
       
        static void Main(string[] args)
        {
            DoStuff();

            GC.Collect();

            Thread.Sleep(1000);

            GC.Collect();

            var s = weakRef.TryGetTarget(out var subject);
            subject?.OnNext("T"); //EXPECTED TO BE NULL
            Console.WriteLine("COUNTER: " + _counter); //PRINTS 40.000, EXPECTED 0
            Console.ReadLine();
        }

        static void DoStuff()
        {
            var subject = new Subject<string>();
            weakRef = new WeakReference<Subject<string>>(subject);
           
            for (var i = 0; i < 40_000; i++)
            {
                _ = Do(subject);
            }
        }

        static async Task Do(IObservable<string> o)
        {
            var _ = await o.FirstAsync();
            Interlocked.Increment(ref _counter);
        }
    }

Despite our best efforts, bugs can slip into releases or corner cases forgotten about. We will try our best to remedy the situation
and/or provide workarounds. Note that certain (odd) behaviors are by design and as such are not considered bugs.

> Which library version?
4.4.1
> What are the platform(s), environment(s) and related component version(s)?
.NET Core 3.1.301
> What is the use case or problem?
Avoiding explicitly disposal of observables

> What is the expected outcome?
0 should be printed to the console.
> What is the actual outcome?
40000 is printed to the console.
> What is the stacktrace of the exception(s) if any?
N/A
> Do you have a code snippet or project that reproduces the problem?
As above.

**Comment by danielcweber** [comment]
>subject?.OnNext("T"); //EXPECTED TO BE NULL

Why would you expect that? In fact, the continuation in `Do` keeps a reference on the subject. After `OnNext` provides a value, `FirstAsync` completes asynchronously and increments the counter. Looks like correct behaviour.

**Comment by thosylve1** [comment]
I guess because nothing is holding a reference to the created tasks and the subject. As such I would expect all the tasks and the subject to be garbage collectable. Was just curious about the semantics of Rx.NET.

**Comment by danielcweber** [comment]
Nothing to do with Rx. The async method is still considered to be "in-flight", even when there is no reference held on the task returned by `Do`. As a result, the subject stays in scope.

**Comment by thosylve1** [comment]
Ok, thanks for clarifying :)
