### ISSUE TITLE
Add LargestBy/SmallestBy combinators

### ISSUE THREAD

**Issue by glopesdev** [dotnet/reactive#126]
In time-series and data stream analysis, it is often useful to sort finite sliding windows of the data in search for the k-Largest or k-Smallest items. Currently Rx supports **MaxBy**/**MinBy** but no **OrderBy** combinator, so it is not very easy to implement retrieval of the k-Largest/Smallest items. In fact, the operator is not trivial to get right in general, so an effective implementation would be extremely welcome.

In fact, not only for **Rx.NET**, but also for **Enumerable** streams this operator could be very useful in alternative to the expensive **OrderBy().Take()** combination that requires caching and sorting the entire stream. I believe **LargestBy**/**SmallestBy** would be very useful also for **Ix.NET**.

Proposed signature:

``` csharp
public static IObservable<IList<TSource>> LargestBy<TSource, TKey>(
    this IObservable<TSource> source,
    int count,
    Func<TSource, TKey> keySelector,
    IComparer<TKey> comparer
)
```

**Comment by akarnokd** [comment]
Sounds like one should be able to do it with `Aggregate` (and perhaps `Defer`):

```cs
Observable.Range(1, 10)
    .Select(v => 11 - v)
    .Aggregate(new SortedSet<int>(), (list, v) =>
    {
        list.Add(v);
        if (list.Count > 5)
        {
            list.Remove(list.Last());
        }

        return list;
    })
    .SelectMany(v => v)
    .Subscribe(Console.WriteLine)
    ;
```

I don't think such processing is common enough to get an operator in Rx.NET proper.

**Comment by akarnokd** [comment]
Closing as uncommon behavior achievable via existing operators.
