### ISSUE TITLE
[NuGet] NETStandard System.Reactive.dll overwrites the NETCore System.Reactive.dll causing runtime errors

### ISSUE THREAD

**Issue by aprice-dev** [dotnet/reactive#1292]
#### Bug

> Which library version?

System.Reactive 4.4.1

> What are the platform(s), environment(s) and related component version(s)?

Windows WPF applications. Specifically using ReactiveUI.WPF to access Reactive features.

> What is the use case or problem?

A solution has three projects, a netcoreapp3.1 Console App, a netcoreapp3.1 WPF app, and a netstandard2.1 shared Library that both projects reference. All three projects output to a shared common directory. Because reactive creates direct assembly references I end up with an assembly reference to System.Reactive.dll in both the console and WPF app, but *the console app references the netstandard System.Reactive.dll and the WPF app references the netcore version.*

When using a library that needs the netcore version of System.Reactive.dll (in this case ReactiveUI.WPF) if the Console app was the last thing built, the project will throw the following exception:
```
System.TypeInitializationException
  HResult=0x80131534
  Message=The type initializer for 'ReactiveUI.RxApp' threw an exception.
  Source=ReactiveUI
  StackTrace:
   at ReactiveUI.RxApp.get_MainThreadScheduler() in D:\a\1\s\src\ReactiveUI\RxApp.cs:line 143
   at ReactiveUI.ReactiveCommand.Create(Action execute, IObservable`1 canExecute, IScheduler outputScheduler) in D:\a\1\s\src\ReactiveUI\ReactiveCommand\ReactiveCommand.cs:line 103
   at WpfApp1.MainWindow..ctor() in C:\Users\User\source\repos\ConsolePlayground\WpfApp1\MainWindow.xaml.cs:line 29

Inner Exception 1:
TypeLoadException: Could not load type 'System.Reactive.Concurrency.DispatcherScheduler' from assembly 'System.Reactive, Version=4.4.0.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263'.
```

**Essentially in a shared output directory the netstandard System.Reactive.dll will overwrite the required netcore System.Reactive.dll causing runtime errors depending on your build order**

Perhaps the two versions of the DLL could be given different names? I'm not sure why this nuget package creates an direct assembly reference compared to every other nuget package I've used, but that might not be desired behavior either.

This issue is similar to another issue that's already open here:
https://github.com/dotnet/reactive/issues/1074

**Comment by clairernovotny** [comment]
You can't put the different versions of Rx into the same folder for the reason you describe. There are targets that have Rx use the correct implementation for WPF vs .NET Core.

**Comment by clairernovotny** [comment]
This is by design. You need to put the different apps into different folders with their appropriate references.

**Comment by aprice-dev** [comment]
A common output for a several projects is not too unusual, what's the motivation to design the system to be incompatible with that? I have a rather large project which requires a common output directory where these assembly references are popping up all over the place causing lots of build errors.

**Comment by clairernovotny** [comment]
There's no intentional design but different implementations support different features, that's why the package provides multiple TFM's. The version that the WPF one uses is a superset of the netstandard 2.0 one. If you're going to put multiple things into the same output folder, that adds a burden to ensure the right packages get copied too.

**Comment by aprice-dev** [comment]
Is there actually a way to ensure that the right package is copied to the output directory? Because the assembly reference is created by the nuget package, I can't edit or delete it. There really seems to be no solution if a shared output directory is required by the project.

**Comment by clairernovotny** [comment]
I'm not sure, sorry. You may be able to control your project's build order by setting a build dependency in Visual Studio.

**Comment by aprice-dev** [comment]
Unfortunately changing the build order still introduces the issue whenever you change a non-WPF project and compile without a full rebuild. Thanks for the responsiveness and help though, I really appreciate it. I guess I'll have to work around the issue for now.
