### ISSUE TITLE
Rx 5 preview missing DispatcherScheduler.Current for WPF net5.0?

### ISSUE THREAD

**Issue by tomasfabian** [dotnet/reactive#1315]
I tried the preview version of Rx and it seems that System.Reactive.Concurrency.DispatcherScheduler.Current is not available for WPF net5.0 RC1. For NetCoreApp 3.1 it works correctly. 
```
<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFrameworks>net5.0-windows;netcoreapp3.1</TargetFrameworks>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Reactive" Version="5.0.0-preview.16" />
  </ItemGroup>

</Project>
```

Based on this commit the HAS_WPF constant should be defined: https://github.com/dotnet/reactive/commit/db8e159c5f1f297b7bc2165ffd77505f391aba4f#

My dotnet version is 5.0.100-rc.1.20452.10. I'm using VS 16.8.0 Preview 3.1.

What am I doing wrong?

Thank you Tomas

**Comment by clairernovotny** [comment]
You must use the 19041 SDK. Your .NET 5 TFM must be `net5.0-windows10.0.19041`. You can target a lower version by setting a min version.

**Comment by tomasfabian** [comment]
Interesting. Thank you @clairernovotny for you quick response/advice

**Comment by ekgurney14** [comment]
Does anybody know why we need to use the 19041 SDK for this capability?
