### ISSUE TITLE
Enumerable overload of Zip does not synchronize enumerator disposal

### ISSUE THREAD

**Issue by glopesdev** [dotnet/reactive#132]
Iterators are synchronized structures that do not expect to be called reentrantly.

The current implementation of **Zip** that takes in an **IEnumerable** source calls the **Dispose** method of the iterator directly when the subscription is disposed. However, this raises the possibility that active **MoveNext** calls are still being executed asynchronously on another thread.

The example below illustrates this scenario.

``` csharp
static IEnumerable<int> MyEnum()
{
    try
    {
        Console.WriteLine("start");
        Thread.Sleep(2000);
        Console.WriteLine("yield");
        yield return 0;
    }
    finally
    {
        Console.WriteLine("dispose");
    }
}

static void Main(string[] args)
{
    var timer = Observable.Timer(TimeSpan.Zero, TimeSpan.FromSeconds(1));
    var handle = timer.Zip(MyEnum(), (x, y) => y).Subscribe();
    Thread.Sleep(500);
    handle.Dispose();
    Console.ReadLine();
}
```

**Comment by akarnokd** [comment]
Sounds like a forgotten bug. I'll look into it for 4.x.
