### ISSUE TITLE
Delaying a sequence by TimeSpan.Zero changes its behaviour

### ISSUE THREAD

**Issue by mjolka** [dotnet/reactive#140]
If I understand correctly, `x` and `x.Delay(TimeSpan.Zero)` should behave indistinguishably.

The following code prints 1:

```
var scheduler = new TestScheduler();
Observable.Return(Unit.Default, scheduler)
    .Timestamp(scheduler)
    .Subscribe(ts => Console.WriteLine(ts.Timestamp.Ticks));
scheduler.Start();
```

If we delay by `TimeSpan.Zero` the output is 2:

```
var scheduler = new TestScheduler();
Observable.Return(Unit.Default, scheduler)
    .Delay(TimeSpan.Zero, scheduler)
    .Timestamp(scheduler)
    .Subscribe(ts => Console.WriteLine(ts.Timestamp.Ticks));
scheduler.Start();
```

**Comment by akarnokd** [comment]
`Delay` has executes an internal step of scheduling before emitting any delayed items. When run with a `TestScheduler`, the `TestScheduler` adds 1 tick to a task when it happens to be scheduled with zero delay. Thus a plain `x` will have 1 task and 1 tick and a delayed `x` will have 2 tasks and 2 ticks.
