### ISSUE TITLE
System.Reactive.xml copied to published output

### ISSUE THREAD

**Issue by ahopper** [dotnet/reactive#1411]
**Which library version?**
4.4.1

**What are the platform(s), environment(s) and related component version(s)?**
Avalonia 0.10 beta6 ,net5.0 rc2, windows 10

**What is the use case or problem?**
Publishing my Avalonia app results in the 2.3M System.Reactive.xml in the build output https://github.com/AvaloniaUI/Avalonia/issues/4987 The file does not appear to be used or needed.

**What is the expected outcome?**
no xml files in the output

**What is the actual outcome?**
System.Reactive.xml in the output

**Comment by bartdesmet** [comment]
@clairernovotny, do you know what's the standard way of dealing with packages that should have XML docs to help developers (IntelliSense) but these shouldn't get copied upon publication of the library or app that consumes the package?

**Comment by ahopper** [comment]
Appears fixed
