### ISSUE TITLE
System.Reactive.Windows.Forms does not work in .NET 5.0

### ISSUE THREAD

**Issue by erinloy** [dotnet/reactive#1436]
#### Feature request

Please implement "System.Reactive.Windows.Forms" for .NET 5.0.

Although it was not specifically targeted at .NET Core 3.1, I was able to get it working with warnings.  However, the same code (when targeted at .NET 5.0) does not compile at all.

Example:
Observable.FromEventPattern<MouseEventHandler, MouseEventArgs>(e => control.MouseMove += e, e => control.MouseMove -= e).ObserveOn(control);
Error:
CS1503	Argument 2: cannot convert from 'System.Windows.Forms.Control' to 'System.Reactive.Concurrency.IScheduler'

**Comment by clairernovotny** [comment]
Do you have small repro project? Windows Forms is supported in `System.Reactive`; the other libraries are older shims for compat.

**Comment by erinloy** [comment]
> Do you have small repro project? Windows Forms is supported in `System.Reactive`; the other libraries are older shims for compat.

See here:
https://github.com/erinloy/ReactiveForms5

**Comment by clairernovotny** [comment]
You must target `net5.0-windows10.0.19041` to get the Windows version. That's the SDK version, your app can target and run on lower Windows versions.

**Comment by erinloy** [comment]
That works, thank you!  For future reference, where can I find more on the targeting requirements?
