### ISSUE TITLE
ForEachAsync that accepts a Func<TSource, Task> onNext and awaits

### ISSUE THREAD

**Issue by Andrew-Hanlon** [dotnet/reactive#144]
The current `ForEachAsync` does not properly allow for an asynchronous `onNext` action. This would be quite handy in two related cases: 
1. where the observable returns an awaitable object, 
2. where the action contains awaitable code.

You can of course currently use an async lambda for the action however since it is not awaited in the `ForEachAsync` implementation, the continuations are not awaited, and exceptions are not propagated.

I would be happy to provide a pull, but perhaps this type of async handling is not in the curent plan for rx.net? It would seem to make sense in this limited usage since the overall ForEachAsync method is async.

**Comment by cactuaroid** [comment]
Maybe this is same for `ForEach`.

My concern is that simply adding overload is a breaking change. The behavior change can be difficult to be noticed without build error. I made different name method for my use, `ForEachTask` and `ForEachTaskAsync`.

**Comment by onovotny** [comment]
These are now available in the 4.0 preview
