### ISSUE TITLE
Bug Sequence contains no elements

### ISSUE THREAD

**Issue by dalton5** [dotnet/reactive#1453]
Hi,

I use Akavache and I have a bug related to Rx.net

I have also created a bug report in Akavache https://github.com/reactiveui/Akavache/issues/635

To summarize:

I try to save an object and I have the exception Sequence contains no elements

In the stacktrace I have: System.Reactive.Subjects.AsyncSubject`1[T].GetResult () [0x00056] in /_/Rx.NET/Source/src/System.Reactive/Subjects/AsyncSubject.cs:441

My code issue

await BlobCache.UserAccount.InsertObject(DataStorageKey.CurrentSession_TokenInfo, authenticateResultPersistanceModel);

My exception

image
![image](https://user-images.githubusercontent.com/8339768/101789005-0e8c1680-3b01-11eb-8981-2797c649d189.png)

The object I save (access token modified):

image
![image](https://user-images.githubusercontent.com/8339768/101789055-19df4200-3b01-11eb-995e-fbc0a63cbf4f.png)

Stack trace:

**at System.Reactive.Subjects.AsyncSubject`1[T].GetResult () [0x00056] in /_/Rx.NET/Source/src/System.Reactive/Subjects/AsyncSubject.cs:441**

**Comment by akarnokd** [comment]
I presume `BlobCache.UserAccount.InsertObject` completes without producing any value hence the failure. Try using `DefaultIfEmpty` with some value as a workaround.

**Comment by dalton5** [comment]
Yes. it did the trick.

Thanks,

**Comment by eli191** [comment]
I did a `BlobCache.UserAccount.Vacuum()` and it started working again.
