### ISSUE TITLE
Add new Disposables.LambdaDisposable

### ISSUE THREAD

**Issue by infogulch** [dotnet/reactive#1457]
> Which next library version (i.e., patch, minor or major)?

.next

> What are the platform(s), environment(s) and related component version(s)?

all

> How commonly is this feature needed (one project, several projects, company-wide, global)?

This would enable quickly creating a new kind disposable inline without requiring the user to declare a new class.

> Please describe the feature.

To hook into the disposable system currently requires creating a new class for every new kind of disposable object. But this spreads out the implementation details of the construction and disposal of said objects and requires the user to be cognizant of all the peculiarities of using disposables in .NET.

What if Rx implemented a new type of disposable whose implementation details are vetted once, allowing the user to implement just the Dispose action itself? Perhaps something like:

``` c#
public sealed class LambdaDisposable : IDisposable
{
    private Action _onDispose;

    public LambdaDisposable(Action onDispose)
    {
        _onDispose = onDispose ?? throw new ArgumentNullException(nameof(onDispose));
    }

    public void Dispose()
    {
        _onDispose?.Invoke();
        _onDispose = null;
    }
}
```

This could be useful to easily define a method or extension that hooks into the disposable lifetime system to ensure that an API is used correctly.  For example, one could use this to create an easily correctly-used Stopwatch + TelemetryEvent recording system like this:

```c#
public static IDisposable TimeEvent(this TelemetryClient telemetryClient, string eventName)
{
    var stopwatch = new Stopwatch();
    var trackEventDisposable = new LambdaDisposable(() =>
    {
        // Stop the stopwatch as soon as possible after dispose is called to exclude the time
        // taken to call TrackEvent
        stopwatch.Stop();
        telemetryClient.TrackEvent(eventName, null, new Dictionary<string, double> {
            { "duration", stopwatch.Elapsed.TotalSeconds }
        });
    });
    // Start the stopwatch as late as possible to exclude the time taken to execute this function.
    stopwatch.Start();
    return trackEventDisposable;
}
```

Which could in turn be used by adding a few simple lines to the method or block scope you want to track:

```c#
using var _timeit = telemetryClient.TimeEvent("MyMethod");
doSomeTimedOperation();
```

```c#
using (telemetryClient.TimeEvent("MyBlock"))
{
    doSomeTimedOperation();
}
```

Compare to the complexity and boilerplate required to do the same thing without IDisposable mentioned in the official docs: https://docs.microsoft.com/en-us/azure/azure-monitor/app/api-custom-events-metrics#trackdependency

Note that the TimeEvent extension doesn't have to specify nit-picky details such as making sure its only called once, or making sure that the dispose method nullifies its references to ease GC, etc.  Also, note in the TimeEvent examples that by using IDisposable we can ensure that the stopwatch and telemetry is finalized even in the event of an exception, and there was no mention of try/catch/finally which would otherwise be necessary and add even more boilerplate.

Thoughts?

**Comment by akarnokd** [comment]
`IDisposable` is a standard library component and nothing Rx-specific, thus it is unclear why you'd want to have this utility feature in Rx.

**Comment by infogulch** [comment]
Rx implements other helper classes related to IDisposable such as [CompositeDisposable](https://github.com/dotnet/reactive/blob/bc39c015bcdb6d2d2f6a648feff599f5ce9ecaf2/Rx.NET/Source/src/System.Reactive/Disposables/CompositeDisposable.cs), or do I misunderstand the source code relationship here?

**Comment by quinmars** [comment]
You can use [`Disposable.Create()`](https://github.com/dotnet/reactive/blob/61aaedac1bbde66f2c26d566bc24757306c80a2b/Rx.NET/Source/src/System.Reactive/Disposables/Disposable.cs#L48):

```csharp
    var trackEventDisposable = Disposable.Create(() =>
    {
        // ....
    });
```

**Comment by infogulch** [comment]
Oh! That does what I'm looking for, thanks @quinmars! I also noticed that there is an (internal) [AnonymousDisposable](https://github.com/dotnet/reactive/blob/bc39c015bcdb6d2d2f6a648feff599f5ce9ecaf2/Rx.NET/Source/src/System.Reactive/Disposables/AnonymousDisposable.cs) that's implemented almost identically to my suggestion.

Thank you for your attention! Closing. 😄

**Comment by akarnokd** [comment]
> Rx implements other helper classes related to `IDisposable` [...] do I misunderstand the source code relationship here

Yes, Rx has helper components for its own use, some of them are public for enabling external use. This doesn't mean that Rx is now the prime host for any utility extensions targeting `IDisposable` that itself has no use of. Especially if those utility extensions can live independently in any library.
