### ISSUE TITLE
Consider adding higher-order overloads to Zip and CombineLatest

### ISSUE THREAD

**Issue by glopesdev** [dotnet/reactive#149]
Specifically:

``` csharp
static IObservable<IList<TSource>> Zip<TSource>(this IObservable<IObservable<TSource>> sources);

static IObservable<IList<TSource>> CombineLatest<TSource>(this IObservable<IObservable<TSource>> sources);
```

This would make everything symmetric with operators like Merge, Concat and Switch which already take higher-order operations. It is also very useful for situations where combined sequences are generated dynamically.

**Comment by akarnokd** [comment]
Note that this is semi-dinamic because both `Zip` and `CombineLatest` works only with known and fixed number of sources which only happens once the outer `IObservable` completes. Besides, you can achieve this behavior with the existing operators:

```cs
source.ToList().SelectMany(list => Zip(list, array => array))
```

You are lucky with C# and extension methods because you don't have to wait for a library extension unlike RxJava; you just have your default method somewhere, import it and apply it fluently.

**Comment by glopesdev** [comment]
Yes, that is exactly what I did as a workaround.

However, it is important to realize that using **ToList** prevents you from being able to start collecting elements from each of the sequences right away in truly reactive fashion.

**Comment by akarnokd** [comment]
That you can do by fiddling with Replay() a bit before ToList:

```cs
sources
.Select(o =>
{
    IConnectableObservable<int> co = o.Replay();
    co.Connect();
    return co;
})
.ToList().SelectMany(list => Observable.Zip(list, arr => arr))
.Subscribe(Console.WriteLine);
```

Of course, the drawback is that `Replay` will keep everything forever. To fix that, you'd need an `UnicastSubject` which allows only a single `IObserver` and queues up values until subscription and a bit after once the client (the Zip's `IObserver`) catches up.

**Comment by glopesdev** [comment]
This is a nice workaround. Unfortunately it looks like ```UnicastSubject``` is not available in Rx.NET. Anyway, nice call. I still think it would still be nice if this was part of Rx though.

**Comment by akarnokd** [comment]
Writing one is [quite simple](https://gist.github.com/akarnokd/1413f4a64558dd07c1c2), although I'm not experienced with the .NET world and what is available where (such as `Volatile` or `Interlocked`).

**Comment by glopesdev** [comment]
Cool, thanks for the reference code. I may end up cooking something like that for my own workaround.

**Comment by danielcweber** [comment]
I think these higher order operators are definitely a cool thing, but should be evaluated for all operators where applicable. Should be a separate issue/WIP-PR then. Closing for now.
