### ISSUE TITLE
Why is there no direct support for net5.0-windows as TargetFramework?

### ISSUE THREAD

**Issue by czdietrich** [dotnet/reactive#1497]
#### Question

After migrating from .NET Core 3.1 to .NET 5.0, compilation fails due to the missing definition for `ObserveOnDispatcher` in WPF projects.

To enable Windows desktop (including WPF) one has to target `net5.0-windows`, but unfortunately `System.Reactive` does not directly support `net5.0-windows`.
The NuGet will fallback to `net5.0` so Windows desktop extensions are not included.
To enable Windows desktop extensions one has to target at least `net5.0-windows10.0.19041`.

If you check the related [Directory.Build.props](https://github.com/dotnet/reactive/blob/fd3902d8f8ac81b033891ee40d4d8c3afb35d4eb/Rx.NET/Source/Directory.build.targets#L27) targeting `net5.0-windows` would enable WPF extensions, but this `TargetFramework` is not defined in [System.Reactive.csproj](https://github.com/dotnet/reactive/blob/fd3902d8f8ac81b033891ee40d4d8c3afb35d4eb/Rx.NET/Source/src/System.Reactive/System.Reactive.csproj#L3).

I simply wonder why this is and if it would be possible to add direct support for `net5.0-windows` without a specific Windows version?

**Comment by jlanng** [comment]
I was caught out by this too. It's quite surprising behavior

**Comment by michaelmairegger** [comment]
Same here. I want to ObserveOn(DispatcherScheduler.Current) or ObserveOnDispatcher on net5.0-windows. If I copy the reuired code to my solution then those methods work. So why the decision was made to limit to net5.0-10.0.19041?

**Comment by runceel** [comment]
I'm facing the same issue.
My project is targeting `net5.0-windows-10.0.19041` with `<TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>`,

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net5.0-windows10.0.19041.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
    <RootNamespace>App4</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Platforms>x86;x64</Platforms>
    <RuntimeIdentifiers>win10-x86;win10-x64</RuntimeIdentifiers>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.ProjectReunion" Version="0.5.0" />
    <PackageReference Include="Microsoft.ProjectReunion.Foundation" Version="0.5.0" />
    <PackageReference Include="Microsoft.ProjectReunion.WinUI" Version="0.5.0" />
    <PackageReference Include="System.Reactive" Version="5.0.0" />
    <Manifest Include="$(ApplicationManifest)" />
  </ItemGroup>
</Project>
```

I would like to support all Windows 10 versions that are supported now. However, System.Reactive supports only the latest Windows 10 10.0.19041. So, the following waring is occurred:

![image](https://user-images.githubusercontent.com/79868/114141669-ded50a00-994c-11eb-8972-846f50b69878.png)

Could you add `TargetPlatformMinVersion` to System.Reactive package?

**Comment by MichaeIDietrich** [comment]
Hi @clairernovotny, sorry for pinging you directly, but you seem to be the last one who committed to this repo.
I would like to get this issue resolved, since it adds an undesirable dependency to the project and the fix might be pretty straight forward. Is there any chance this issue could be prioritized a bit?

**Comment by clairernovotny** [comment]
The Windows 10 19041 SDK is required for building apps that use Rx. They can target earlier versions of Windows. The version number in the TFM indicates the SDK required, not the OS minimum version.

**Comment by MichaeIDietrich** [comment]
Thank you for your response. I guess it is clear that this version number is not the minimum OS version, but it forces all consumers to set at least the same version number (which is over 250 projects in our solution btw.), but there seems to be no need for this specific version number, so I guess most developers would prefer if the NuGet then would only specify `net5.0-windows` as TFM. 

I did not see any other NuGet that specifies the full TFM version if not actually needed.

**Comment by lszczygielek** [comment]
Hi Claire, you said:
> 
> 
> The Windows 10 19041 SDK is required for building apps that use Rx. They can target earlier versions of Windows. The version number in the TFM indicates the SDK required, not the OS minimum version.

How it impacts application on Windows 7? Probably it would be safer to use Rx 5 on Windows 7 but using .NET Framework, not .NET 5 - am I right?

**Comment by clairernovotny** [comment]
Rx does not explicitly support Win7 as Win7 has been out of support for quite some time. If it happens to work, then it works. The full framework target should work there as not much has changed.

**Comment by runceel** [comment]
@clairernovotny 

> The Windows 10 19041 SDK is required for building apps that use Rx. They can target earlier versions of Windows. The version number in the TFM indicates the SDK required, not the OS minimum version.

In my understanding, you can set range of supported windows versions using `TargetPlatformMinVersion` on .csproj files.

For example:
```xml
<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net5.0-windows10.0.19041.0</TargetFramework>
		<TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="System.Reactive" Version="5.0.0" />
	</ItemGroup>
</Project>
```

In this case, Visual Studio reports warnings.
![image](https://user-images.githubusercontent.com/79868/118630072-2763cb00-b809-11eb-825a-e45ff5ae25fc.png)

So I think that setting TargetFramework to `net5.0-windows`(I guess it is prefer in this case) or adding `TargetPlatformMinVersion` on System.Reactive need.

**Comment by MatthewKing** [comment]
@runceel Did you ever get a resolution for this? I'm in the same situation as you - wanting to have a `TargetFramework` of `net5.0-windows10.0.19041` and a `TargetPlatformMinVersion` of `10.0.17763.0`.

**Comment by clairernovotny** [comment]
The TFM only refers to the SDK version used to compile and, not the min version. Rx was built against, and requires the 19041 SDK, but it can run on all supported versions of Windows 10 by using the TPMV. That is the correct way to do it.

**Comment by runceel** [comment]
@clairernovotny 
Thanks! Could you check my understanding?
Does your answer mean the warning messages are ignorable?
If so, it is .NET SDK or other tools issue, correct?

**Comment by aesalazar** [comment]
Sorry to resurrect this, if people prefer I create a new issue, let me know.

I am trying to understand the implications fix the OS version in the moniker but allowing support for older OS (which we need on our project).  According to MS:

https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/desktop-to-uwp-enhance#supporting-multiple-windows-os-versions

```Note that setting the TargetPlatformMinVersion to a version below the TargetPlatformVersion creates the potential for calling unavailable APIs.```

Is that a risk we need to worry about for the Reactive library?  Even if it is not, I suppose it opens the door for other non-Reactive library calls. that are unavailable in older OSs  At the very least, the compile Warning list will light up like a Christmas tree :).

**Comment by a44281071** [comment]
Still have using bug whith "net6.0-windows" and window7/windows10.

**Comment by ScarletKuro** [comment]
@a44281071 Sadly, I think, this problem will not be solved until reactive will target .net6.0 in TargetFramework directly.
Personally, for now, I just  copy-pasted DispatcherScheduler  and DispatcherObservable for my .net6 library.

**Comment by Brascal** [comment]
A relatively painless way I found (thanks to the idea from @ScarletKuro) was to simply add the ReactiveUI.WPF package to my WPF projects. This allowed me to advance to `net6.0-windows`, and also to use `DispatcherScheduler`. I am not using anything from ReactiveUI library, so this is technically a hack, but took 5 minutes of my time and added only a few hundred kilobytes to the shipped binaries, so it was worth it for me to be able to move on from previously being held back on net5.0-windows10.0.19041 because of RX
