### ISSUE TITLE
Fix warning when using nullable reference types with OfType operator

### ISSUE THREAD

**Issue by pellet** [dotnet/reactive#1525]
#### Bug

Despite our best efforts, bugs can slip into releases or corner cases forgotten about. We will try our best to remedy the situation
and/or provide workarounds. Note that certain (odd) behaviors are by design and as such are not considered bugs.

> Which library version?
v5.0

> What are the platform(s), environment(s) and related component version(s)?
.net5.0

> What is the use case or problem?
I want to use the OfType operator for filtering out nulls like so:
```
Observable
    .Return<string?>("blah")
    .OfType<string>()
    .SelectMany(this.audioService.PlayAudioPair)
    .Subscribe();
```

> What is the expected outcome?
No warnings

> What is the actual outcome?
When compiled has a warning:
`warning CS8620: Argument of type 'IObservable<string?>' cannot be used for parameter 'source' of type 'IObservable<object>' in 'IObservable<string> Observable.OfType<string>(IObservable<object> source)' due to differences in the nullability of reference types.`

**Comment by pellet** [comment]
I've found the operator `.WhereNotNull()` is working for me without warnings, it would be nice to have the OfType() operator handling nulls too though if possible.

**Comment by JakenVeina** [comment]
I'll second that this still needs fixed.

**Comment by wmanning** [comment]
@JakenVeina Maybe open up a new issue so it doesn't get lost.  It's been four months since the other person asked the same question so maybe the question got missed.
