### ISSUE TITLE
GroupBy and GroupByUntil have faulty dispose semantics

### ISSUE THREAD

**Issue by glopesdev** [dotnet/reactive#153]
To reproduce:

``` csharp
var subject = new Subject<int>();
var obs = subject
    .Finally(() => Console.WriteLine("Disposed"))
    .GroupBy(x => x % 2)
    .SelectMany(x => x);

var s1 = obs.Subscribe();
subject.OnNext(1);

Console.Write("Dispose one subscription?");
Console.ReadLine();
s1.Dispose();

var s2 = obs.Subscribe();
var s3 = obs.Subscribe();
subject.OnNext(1);

Console.Write("Dispose one subscription?");
Console.ReadLine();
s3.Dispose();

Console.Write("Dispose one subscription?");
Console.ReadLine();
s2.Dispose();

Console.ReadLine();
```

Basically what happens is that the subscription to **`GroupBy`** shares a **`RefCountDisposable`** variable across the multiple groups. Unfortunately the way this is done is through a class variable in the **`Producer`**, which as expected will not work for multiple subscriptions.

Operator implementations should never share class variables across nested subscriptions, but always make sure they scope their variables independently to each subscription.

I have submitted a fix in pull request #125.

**Comment by danielcweber** [comment]
>I have submitted a fix in pull request #125.

#125 has been rendered obsolete.
@ghuntley Please close.
