### ISSUE TITLE
Incomplete support for .NET 4.6

### ISSUE THREAD

**Issue by wldevries** [dotnet/reactive#1530]
#### Bug

Despite our best efforts, bugs can slip into releases or corner cases forgotten about. We will try our best to remedy the situation
and/or provide workarounds. Note that certain (odd) behaviors are by design and as such are not considered bugs.

> Which library version?

System.Reactive 5.0.0

> What are the platform(s), environment(s) and related component version(s)?

.NET Framework 4.6.1 on Windows 10 (in my case, customers have other OS versions)

> What is the use case or problem?

I want to use `DispatcherScheduler` and the accompanying `ObserveOnDispatcher`.

> What is the expected outcome?

Both types can be resolved and they work.

> What is the actual outcome?

The project targets the .NET Standard 2.0 version of System.Reactive which does not include `DispatcherScheduler`.

It seems the ReactiveUI project has solved it by including a copy of the code in their own library targeting .NET Framework 4.6.1.

> What is the stacktrace of the exception(s) if any?

N/A

> Do you have a code snippet or project that reproduces the problem?

Code for my .csproj
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net461</TargetFramework>
    <UseWPF>true</UseWPF>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.Reactive" Version="5.0.0" />
  </ItemGroup>
</Project>
```

**Comment by clairernovotny** [comment]
Rx 5.0 does not directly support .NET 4.6. The minimum .NET Framework version it supports is 4.7.2. You'll find the dispatchers in there if you update your .NET version to at least 4.7.2. On lower .NET versions, it falls back to the .NET Standard 2.0 implementation, which cannot have dispatchers as those are tied to .NET Framework.

**Comment by wldevries** [comment]
Okay thanks for the quick reply. The readme in this repository does mention NET Framework 4.6 support for 5.0, but I guess it's fair such an old version would come with limitations.
