### ISSUE TITLE
TakeUntil values loss

### ISSUE THREAD

**Issue by nikitazharkovsky** [dotnet/reactive#1600]
System.Reactive.Linq 5.0.0
netcoreapp3.1

I try to send values to subject from different threads. If subscriber:
1) use .TakeUntil(unsubscribeSubject) 
2) unsubscribeSubject never produce the values 

then we will lose some values.

The code above prints 10 thread * 1000 values = 10.000 values as expected:

```
class Program
    {
        private static readonly object _sync = new object();
        private static int _count = 0;

        static void Main(string[] args)
        {
            var subject = new Subject<int>();

            subject
                .Buffer(TimeSpan.FromSeconds(.3), 1000)
                .Subscribe(values =>
                {
                    lock (_sync)
                    {
                        _count += values.Count;
                    }
                });

            // Start from different threads
            Enumerable.Range(0, 10).ToList().ForEach(_ =>
            {
                var thread = new Thread(new ThreadStart(() => 
                { 
                    Enumerable.Range(0, 1000).ToList().ForEach(subject.OnNext);
                }));
                thread.Start();
            });

            // Wait for threads completion
            Task.Delay(1000).Wait();

            // Print total number of values
            Console.WriteLine("Count = " + _count);
        }
}
```

If add .TakeUntil() we will lose ~0.3% of values:
```
class Program
    {
        private static readonly object _sync = new object();
        private static int _count = 0;

        static void Main(string[] args)
        {
            var unsubscribeSubject = new Subject<object>();
            var subject = new Subject<int>();

            subject
                .TakeUntil(unsubscribeSubject)  // The problem
                .Buffer(TimeSpan.FromSeconds(.3), 1000)
                .Subscribe(values =>
                {
                    lock (_sync)
                    {
                        _count += values.Count;
                    }
                });

            // Start from different threads
            Enumerable.Range(0, 10).ToList().ForEach(_ =>
            {
                var thread = new Thread(new ThreadStart(() => 
                { 
                    Enumerable.Range(0, 1000).ToList().ForEach(subject.OnNext);
                }));
                thread.Start();
            });

            // Wait for threads completion
            Task.Delay(1000).Wait();

            // Print total number of values
            Console.WriteLine("Count = " + _count);
        }
}
```

**Comment by theodorzoulias** [comment]
@akarnokd unfortunately the outdated [documentation](https://docs.microsoft.com/en-us/previous-versions/dotnet/reactive-extensions/hh229173(v=vs.103)#remarks) of the `Subject<T>` class gives misleading information about this:

> Regular subjects do synchronize outgoing calls to subcribed observers using a scheduler.

According to [my experiments](https://dotnetfiddle.net/q4Bqyr) the `ReplaySubject<T>` is synchronized. The other built-in `ISubject<T>` implementations are not.

**Comment by idg10** [comment]
Those old docs are misleading on two fronts:

1. as @theodorzoulias notes, only one of the subjects uses a scheduler
2. schedulers wouldn't help with this issue anyway

That second one isn't technically an error, but it's clearly misleading because it leads people to think that going via a scheduler will ensure that it's OK to call `OnNext` from multiple threads. But that's not actually what schedulers are for. Unfortunately, this repo has no control over those old docs, so this isn't something we can really fix.

Meanwhile, the behaviour described is not a bug—you're just not allowed to call into `OnNext` simultaneously on multiple threads, so the behaviour of this example is undefined.
