### ISSUE TITLE
WinUI project referencing Reactive causes issues

### ISSUE THREAD

**Issue by Pizzahd88** [dotnet/reactive#1607]
#### Bug

> Which library version?

5.0.0

> What are the platform(s), environment(s) and related component version(s)?

.Net 5.0, WinUI3 application using newest WindowsAppSDK (v1.0.0 Preview1)

`<OutputType>WinExe</OutputType>`
`<TargetFramework>net5.0-windows10.0.19041.0</TargetFramework>`
`<TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>`
`<RootNamespace>WinUI3S2</RootNamespace>`
`<ApplicationManifest>app.manifest</ApplicationManifest>`
`<Platforms>x86;x64</Platforms>`
`<RuntimeIdentifiers>win10-x86;win10-x64</RuntimeIdentifiers>`
`<UseWinUI>true</UseWinUI>`

> What is the use case or problem?

Usage of WinUI results in ex. designer issues, since System.Reactive library references System.Windows.Controls.
This results in Ambiguous reference exceptions for UserControl, Window and the other shared control names.

> What is the expected outcome?

Referencing System.Reactive library will not import System.Windows.Controls interfering with WinUI.

> What is the actual outcome?

**Comment by Pizzahd88** [comment]
For anyone finding themselves with the same issue as I.

The issue were not caused by the Reactive library but an extension in Visual studio that I was using.
So try to disable your extensions to see if that fixes the issue for you.

Resharper extension was the culprit in my case.

**Comment by dojo90** [comment]
I have exactly the same problem. Have you opened an issue on YouTrack?
