### ISSUE TITLE
System.Linq.Async NET6

### ISSUE THREAD

**Issue by tomasfil** [dotnet/reactive#1645]
#### Question

Hello, I would like to ask if there are any plans when .NET 6 will be supported for System.Linq.Async.

Thanks

**Comment by clairernovotny** [comment]
The current version should already work with 6.0; what issues are you encountering?

**Comment by tomasfil** [comment]
I am for some reason unable to install the package into NET 6 project. Visual studio doesnt give any specific error.

**Comment by clairernovotny** [comment]
What kind of project, what are you targeting?

**Comment by hjrb** [comment]
Same for me. It installs but when using System.Linq.Async - I get a compiler error.

**Comment by clairernovotny** [comment]
Fixed in #1660

**Comment by clairernovotny** [comment]
This should be fixed in 5.1.
