### ISSUE TITLE
Ix.Async Select with selector returning Task<TResult>

### ISSUE THREAD

**Issue by fubar-coder** [dotnet/reactive#168]
It would be very convenient to have a `Select(Func<TInput, Task<TResult>>)` out of the box.

The only way to do this is by creating your own `Select` function or by using `.SelectMany(x => ConvertItemAsync(x).ToAsyncEnumerable())`, which probably isn't as optimized as it could've been?

**Comment by aelij** [comment]
This is missing for ALL of the operators. This entire Async library should be revisited and implemented much more simply using async/await (see SelectAsync and WhereAsync [in this Gist](https://gist.github.com/aelij/987d974c811865029564f1bbeffb6b47#file-asyncenumerableex-cs-L603) for example.)

**Comment by oliverjanik** [comment]
I was just looking for a ForEach version of this where the callback should be `Func<TInput,Task>`and not `Action<TInput>`.

**Comment by bartdesmet** [comment]
We'll sync up with the C# team on future directions for `IAsyncEnumerable<T>` and LINQ. See https://github.com/dotnet/roslyn/issues/261 for a discussion on that end. The observation that we'd need sync and async overloads for operators is quite right; for operators that take in 2 or more functions that need async variants, this starts to add up quite a bit in terms of API surface though.

**Comment by aelij** [comment]
@bartdesmet For operators that take in 2 or more functions, can't we have just Task-returning functions and use Task.FromResult if needed (possibly at the cost of an allocation)? I may be wrong but I think this use-case is fairly rare (needing a sync and async functions together in the same call).

Must you really wait for C# to implement this feature? It could take a while. As I mentioned in my PR (#170) there's currently a real need for this library in [Service Fabric](https://azure.microsoft.com/en-us/services/service-fabric/), which only exposes an async enumerable over Reliable Collections. And the async versions of the operators are really needed for cross-collection queries.

**Comment by onovotny** [comment]
These are now available in the 4.0 preview

**Comment by softlion** [comment]
> "These are now available in the 4.0 preview"

What is "these" ?
