### ISSUE TITLE
Support Trim

### ISSUE THREAD

**Issue by timeshift92** [dotnet/reactive#1683]
Thank you for such a cool library.

#### Question
i searched in stackoverflow and issues but couldn't find an answer

> What is the context of your question or problem?

is trimming supported?

> What is the question or problem you try to solve?

reduce size for blazor wasm

> What were the (original) requirements you tried to solve?
i have small size for blazor wasm project

> What have you tried so far, what code have you written so far?
i'm beginner

**Comment by czdietrich** [comment]
It would be really great to invest in trimming. Else it will be hard to use this library in Blazor projects, since its uncompressed size is around 1.5 MB which is a lot for a library in a web project.

**Comment by Sewer56** [comment]
Well, it's a lot for a library in general I suppose.  
Sure, these days this amount of storage doesn't matter that much, but support for trimming a library which in many cases (especially if used as a dependency) will be largely unused would be neat.  

If anything, it's the sentiment that's important; projects under the .NET Foundation should aim to set a standard for other projects.

**Comment by idg10** [comment]
This is now available in Rx [6.0.0-preview.9](https://www.nuget.org/packages/System.Reactive/6.0.0-preview.9) on NuGet.
