### ISSUE TITLE
Easily half the methods on reactivex.io are listed as TBD under Rx.NET

### ISSUE THREAD

**Issue by jcotton42** [dotnet/reactive#180]
As the title says, they really need to be filled in

**Comment by desertrambler** [comment]
It feels like this project has been abandoned - was it rolled into mainstream .NET, or is it just that everybody is focused on RxJS instead?

**Comment by bartdesmet** [comment]
We don't own reactivex.io. These methods exists and are documented in the XML documentation files that ship with Rx.NET.

**Comment by mattpodwysocki** [comment]
@bartdesmet @desertrambler I am a part of the reactivex.io team.  The problem has been the lack of MSDN or markdown documentation to point to which is why things are TBD.  We hope to work on that soon

**Comment by bartdesmet** [comment]
https://msdn.microsoft.com/en-us/library/system.reactive.linq.observable(v=vs.103).aspx would be a start.

**Comment by mattpodwysocki** [comment]
@bartdesmet it would be if it were on 2.x instead of 1.x as quite a few things are missing like `TakeLastBuffer` etc.  We can talk about this offline

**Comment by akarnokd** [comment]
The reactivex.io site is driven by https://github.com/ReactiveX/reactivex.github.io which is not that easy to contribute to and has been outdated for many years. I'm not 100% certain but the maintainer(s) are subcontractors of Netflix who left the project in limbo some time ago.

**Comment by jcotton42** [comment]
Where should we go then for documentation?

**Comment by akarnokd** [comment]
https://github.com/dotnet/reactive/issues/180#issuecomment-220158992 . The rest is search engines and StackOverflow questions.

Everything else is a massive undertaking in any project. In a similar situation, we've been slowly expanding the RxJava [documentation](https://github.com/ReactiveX/RxJava/wiki/Combining-Observables) beyond the docs in the source, but it is a lot, tedious and not the highest priority.
