### ISSUE TITLE
IReactiveProcessing

### ISSUE THREAD

**Issue by grahamehorner** [dotnet/reactive#181]
what is the status of Rx v3 and the IReactiveProcessing that @bartdesmet demoed approx. 2yrs ago ?
please provide update

**Comment by bartdesmet** [comment]
We're hoping to release a new batch of functionality later this year, based on internal developments that took place within the Bing organization. As part of this, we're looking at doing future developments in the area of our reactive programming cloud platform in the open here on GitHub. Currently, we're working out the details to transition parts of the technology to the .NET Foundation.

**Comment by shaggygi** [comment]
Glad to see you're still around @bartdesmet.  Hope to see rx.net support for .net core soon.

**Comment by grahamehorner** [comment]
@bartdesmet that's great; really excited to think what this can bring to the table with #ServiceFabric and #Cloud complex event processing at scale; will the new functionality be available for coreclr and/or able to run on #ServiceFabric / #NanoServer ?

**Comment by grahamehorner** [comment]
@bartdesmet in the meantime are there any samples of remote Qservable<T> and/or QservableProvider like mentioned in @ch9 #techdays https://channel9.msdn.com/Events/TechDays/Techdays-2014-the-Netherlands/Event-processing-at-all-scales-with-Reactive-Extensions

**Comment by HowardvanRooijen** [comment]
Any update on progress or at least a roadmap?

**Comment by leonmeijer** [comment]
@bartdesmet  Hi Bart, any update on IReactiveProcessing ?

**Comment by grahamehorner** [comment]
@bartdesmet any updates, understand your very busy; but if there is any more resources or information with regards the timeline and/or  development or even an private preview program I’d be really interested? Oh and which branch should I be following as I can see there have be a few check ins with regard to work in progress in the last few weeks/months?

**Comment by grahamehorner** [comment]
closed in error

**Comment by grahamehorner** [comment]
any update on this ?

**Comment by grahamehorner** [comment]
almost 3yrs past and nothing and no updates? guys will this even see the light of day ? even if it's a dead project an update would nice? also anthing around bonsi and weather this is also a dead-end ?

**Comment by akarnokd** [comment]
I don't know what `IReactiveProcessing` is. Do you have some details about it, the video perhaps, or some short description of the expected functionality?

**Comment by grahamehorner** [comment]
@akarnokd IReactiveProcessing relates to Reactor in the very early days IReactiveProcessing was the interface that represented the cloud based process for the event stream created/referenced on the client; this more than likely has changed the name but I've not seen anything regards reactor or bonsi etc. or IReactiveProcessing …

**Comment by akarnokd** [comment]
It sounds out of scope to me. Rx.NET is about in-memory reactive data processing. Network/cloud/DB drivers are better suited in their own respective libraries.

**Comment by grahamehorner** [comment]
@akarnokd I think you should review the above as it is a RX.NET and core project that @bartdesmet has been conducting and uses IQbservable for bing; its most definitely not out of scope for Rx

**Comment by grahamehorner** [comment]
@akarnokd see https://channel9.msdn.com/Shows/Going+Deep/Bart-De-Smet-Rx-and-Cortana?term=bart%20de%20smet&lang-en=true approx. 29m 30sec

**Comment by grahamehorner** [comment]
any updates ?

**Comment by davidglassborow** [comment]
Here is another video by Bart going into more information about bonsai tree serialisation of IQbservable at NDC 2015 - https://vimeo.com/132192255

@bartdesmet did the bonsai tree code ever get released do you know ?

**Comment by grahamehorner** [comment]
I've not seen anything with regard bonsitree, IMHO this is growing in importance especially with IoT devices data processing of IOT telemetry on the devices before sending to cloud.

**Comment by davidglassborow** [comment]
Related - https://twitter.com/reactivex/status/627300773886472193

**Comment by grahamehorner** [comment]
2015 is a extremely long time ago in software development terms this is like a decade or two in real life. So I guess it dead or not happening :'l

**Comment by akarnokd** [comment]
I doubt anything will happen anytime soon in Rx.NET from our side in this respect.

**Comment by grahamehorner** [comment]
This should be re-opened IMHO,  @bartdesmet said above that a release was forthcoming and I would be very interested to know if/why that hasn't happened or if these features have been deemed obsolete in favor of a newer approach.  IMHO I would truly love the ability to run RX in the cloud as a AzureFunction (with checkpointing) as was discussed.

**Comment by 3GDXC** [comment]
@bartdesmet any update? @akarnokd this surely shouldn't have been closed? the question is still valid and without any update or feedback to suggest what can/would be recommended to any remote rx in the cloud as shown by @bartdesmet

**Comment by akarnokd** [comment]
I'm not actively involved with Rx.NET at the moment and defer to @bartdesmet on the topic.

**Comment by davidglassborow** [comment]
It looks like a new version of Rx from inside MS has been released at https://reaqtive.net/.

There are various blog entries, but here is a description of how they extended the IObservable / IQbservable dimensions with new concepts around stateful subscription etc: https://reaqtive.net/blog/2021/05/sequences-linq-rx-reaqtor-part-04-reaqtive

Here is @bartdesmet discussing it in a video from Sep 2021 - https://reaqtive.net/talks/on-dotnet-live-scalable-event-processing-with-reaqtor

**Comment by davidglassborow** [comment]
and here is the src https://github.com/reaqtive/reaqtor

**Comment by HowardvanRooijen** [comment]
Yes, open sourcing this was the work of @bartdesmet @idg10, myself and the .NET Foundation. 

There are a number of .NET Interactive Notebooks in the repo which show different features. There's also a PR with a community submitted example:

https://github.com/reaqtive/reaqtor/pull/125

I'd also recommend watching this talk for a good overview with examples:

https://reaqtive.net/talks/reaqtor-reliable-rx-at-scale-for-high-performance-event-processing

**Comment by NickDarvey** [comment]
Thanks for sharing this @davidglassborow. I'd managed to completely miss this despite having Google alerts set up and subscribing to so many GitHub issues 😅
