### ISSUE TITLE
Remove dependency on Microsoft.Bcl.AsyncInterfaces for net6.0

### ISSUE THREAD

**Issue by owns** [dotnet/reactive#1834]
#### Feature request

Considering the points above, please describe the feature or behavior you would like dotnet/reactive included:

> Which subcomponent library (Ix, Async.Ix)?

lx

> Which next library version (i.e., patch, minor or major)?

patch

> What are the platform(s), environment(s) and related component version(s)?

Microsoft.Bcl.AsyncInterfaces

> How commonly is this feature needed (one project, several projects, company-wide, global)?

global

> Please describe the feature.

I noticed the dependency on `Microsoft.Bcl.AsyncInterfaces` for `net6.0` on NuGet. I found that odd since, from `Microsoft.Bcl.AsyncInterfaces`'s README (below):
> This package is not required starting with .NET Standard 2.1 and .NET Core 3.0.

So it makes sense to only explicitly include the dependency for the older frameworks.

Looking at the PR history, it looks like this was just auto version bump-ed to the current state.

I found an open PR to address this: #1719

>**NOTE**: I call issue a FR since it technically doesn't break anything to leave the dependency.

**Comment by owns** [comment]
Hello 😁
Merry Christmas and happy holidays!
I just wanted to check in on this issue. Please let me know if there's any details or testing needed.  The PR to fix this #1719 is still open with no conflicts 🤞

**Comment by HowardvanRooijen** [comment]
I'm still working on getting admin rights for the org. I'm hoping this might happen over the festive break.

**Comment by danielcweber** [comment]
This has been fixed in #1719.

**Comment by owns** [comment]
thank you!
