### ISSUE TITLE
[New Maintainers] Becoming GitHub Admins

### ISSUE THREAD

**Issue by HowardvanRooijen** [dotnet/reactive#1869]
Ian Griffiths (@idg10) and Howard van Rooijen (@HowardvanRooijen) from [endjin](https://endjin.com) have volunteered to become project maintainers.

With the support of @jglozano & @richlander from the .NET Foundation, a meeting was convened with @clairernovotny, @bartdesmet on 2023-01-20 

Based on their existing maintenance of [reaqtor](https://github.com/reaqtive/reaqtor) it was agreed and they were assigned access.

**Comment by richlander** [comment]
Congratulations! It was obvious talking to both of you that you deserve to be maintainers and have a lot of passion for the project.

I'm glad that @jglozano and I could help, if in a small way.
