### ISSUE TITLE
[New Maintainers] Becoming Azure DevOps Admins

### ISSUE THREAD

**Issue by HowardvanRooijen** [dotnet/reactive#1870]
In order to be able to maintain Rx, @idg10 and @HowardvanRooijen need admin access to the Azure DevOps infrastructure which currently runs the build and release pipelines for the project.

Can @clairernovotny or @bartdesmet make this assignment, otherwise can @richlander or @jglozano from the .NET Foundation help?

**Comment by richlander** [comment]
I just checked. You already seem to be an admin (and Ian, too).

Is it for this project? https://dev.azure.com/dotnet/Rx.NET/

**Comment by HowardvanRooijen** [comment]
Amazing. I didn't get a notification for that. I've just double checked and we're still not NuGet admins.
