### ISSUE TITLE
[New Maintainers] Becoming NuGet.org Admins

### ISSUE THREAD

**Issue by HowardvanRooijen** [dotnet/reactive#1871]
In order to be able to maintain Rx, @idg10 and @HowardvanRooijen need admin access to the [rxteam](https://www.nuget.org/profiles/rxteam) profile on nuget.org.

Can @clairernovotny or @bartdesmet make this assignment, otherwise can @richlander or @jglozano from the .NET Foundation help?

**Comment by richlander** [comment]
Given that those folks are available, it would be greatly preferable if they did it. I am hoping that we can make that happen. Please remind us if you cannot get traction within one week.

**Comment by HowardvanRooijen** [comment]
Hi @richlander - no traction as yet.

**Comment by HowardvanRooijen** [comment]
Hi @richlander - still nothing. How can we get unblocked?

**Comment by richlander** [comment]
Sorry. Just saw this. I will push on it.

**Comment by HowardvanRooijen** [comment]
Thank you. Issue https://github.com/dotnet/reactive/issues/1870 is also related!

**Comment by HowardvanRooijen** [comment]
Invitation accepted! Thanks @clairernovotny (& @richlander) 🎉
