### ISSUE TITLE
Catch not work

### ISSUE THREAD

**Issue by wangbo4020** [dotnet/reactive#1895]
Hello and thank you for using dotnet/reactive. Please select a category and detail your issue by answering the questions there:

#### Bug

Despite our best efforts, bugs can slip into releases or corner cases forgotten about. We will try our best to remedy the situation
and/or provide workarounds. Note that certain (odd) behaviors are by design and as such are not considered bugs.

> Which library version?
> **5.0**

> What are the platform(s), environment(s) and related component version(s)?
> **Window11 22H2 22621.1265，Visual Studio 2022(64 bit); .Net Framework 4.8**

### Exception not catch.

```Csharp
            Observable.Defer(() => Observable.Return("aac"))
            .ObserveOn(SynchronizationContext.Current)
            .Select(_ =>
            {
                throw new Exception("test execption");
                return _;
            })
            .Catch<string, Exception>(ex => Observable.Throw<string>(ex))
            .Subscribe(str =>
            {
                //Log("Response: " + response.ToString());
                log.Info("test " + str);
            }, err =>
            {
                log.Warn("test ", err);
            }, () =>
            {
                log.Warn("test completed");
            });
```
![image](https://user-images.githubusercontent.com/5559403/224994798-e10ea33a-0832-4d50-9b78-00dc733364db.png)

**Comment by idg10** [comment]
`SynchronizationContext.Current` is `null` by default, and is generally only set if you're using a framework that supplies a `SynchronizationContext` (e.g., WPF or Windows Forms), if if you've set one yourself.

So I'm guessing this code probably runs in the context of some UI framework? Could you tell me which framework you are using?

**Comment by wangbo4020** [comment]
> `SynchronizationContext.Current` is `null` by default, and is generally only set if you're using a framework that supplies a `SynchronizationContext` (e.g., WPF or Windows Forms), if if you've set one yourself.
> 
> So I'm guessing this code probably runs in the context of some UI framework? Could you tell me which framework you are using?

Yes, I'm using on winform

**Comment by wangbo4020** [comment]
I need to changed the code this way to be catched

```
            Observable.Defer(() => Observable.Return("aac"))
            .ObserveOn(SynchronizationContext.Current)
            .Select(_ =>
            {
                try {
                    throw new Exception("test execption");
                } catch(Exception ex) {
                    return Observable.Throw(ex);
                }
                return _;
            })
            .Catch<string, Exception>(ex => Observable.Throw<string>(ex))
            .Subscribe(str =>
            {
                //Log("Response: " + response.ToString());
                log.Info("test " + str);
            }, err =>
            {
                log.Warn("test ", err);
            }, () =>
            {
                log.Warn("test completed");
            });
```

**Comment by wangbo4020** [comment]
**Thank you for your valuable time, This is indeed the case.**

![image](https://user-images.githubusercontent.com/5559403/229460511-e47e9006-9d03-448f-add6-937a5d8974fa.png)
