### ISSUE TITLE
Observable.Merge(IObservable<IObservable<TSource>>) seems to be broken. Version 6.0.0

### ISSUE THREAD

**Issue by wilbennett** [dotnet/reactive#1982]
Hello and thank you for using dotnet/reactive. Please select a category and detail your issue by answering the questions there:

#### Bug

Despite our best efforts, bugs can slip into releases or corner cases forgotten about. We will try our best to remedy the situation
and/or provide workarounds. Note that certain (odd) behaviors are by design and as such are not considered bugs.

> Which library version? 6.0.0

> What are the platform(s), environment(s) and related component version(s)? Windows

> What is the use case or problem?

I am attempting to merge multiple observable sequences.  I would like to be able to add and remove sequences as needed.  There is an overload of the Merge operator that takes an IObservable<IObservable<TSource>> that is perfect for my needs.  This used to work previously (the last time I checked was using Rx-Main v2.2.5) but now I get no messages after subscribing.

> What is the expected outcome?

Ability to add and remove streams to a subject that merges the data of the currently active streams.

> What is the actual outcome?

Adding the streams seems to be working but no data is being produced.

> What is the stacktrace of the exception(s) if any? N/A

> Do you have a code snippet or project that reproduces the problem?

```c#
var stream1 = Observable.Interval(TimeSpan.FromSeconds(1)).Take(5)
var stream2 = Observable.Interval(TimeSpan.FromSeconds(1.5)).Take(3)
```
Scenario 1 (Works):
```c#
stream1.Merge(stream2)
```
Scenario 2 (Works):
```c#
Observable.Merge(stream1, stream2)
```
Scenario 3 (Fails - nothing is emitted):
```c#
var streams = new Subject<IObservable<long>>();
var result = streams.Merge(); // or Observable.Merge(streams);
// doing Publish().RefCount() here still fails
// doing Publish() and then Connect() works! You lose the behavior of some observables I believe though.

streams.OnNext(stream1);
streams.OnNext(stream2);
return result;
```

**Comment by akarnokd** [comment]
I don't think it ever worked the Subject way you described.

Subjects are hot so if there are no observers, signaling items to them get ignored. This is true if you attach a chain onto them. If the chain is not subscribed to, nothing flows through.

```cs
var streams = new Subject<IObservable<long>>();
var result = streams.Merge(); // or Observable.Merge(streams);

result.Subscribe(Console.WriteLine); // <-------------------------

streams.OnNext(stream1);
streams.OnNext(stream2);
return result;
```

**Comment by wilbennett** [comment]
Thanks @akarnokd!

You are correct.  I am converting from old code and inadvertently changed the ordering of the Subscribe and OnNext calls.

This can be closed.

Thanks again,
Wil
