### ISSUE TITLE
Serializable Bonzai Tree Support

### ISSUE THREAD

**Issue by ronnyek** [dotnet/reactive#207]
In a video long ago, Bart De Smet talked about the integration of serializable bonzai tree support in rx.net. https://vimeo.com/132192255

I'd really like to be able to pass expressions in their serialized forms over the wire, additionally persisting the expressions themselves to disk (and be able to load).

Gitter discussion about it:
https://gitter.im/Reactive-Extensions/Rx.NET/archives/2015/07/01

Now that it's been > 1yr, and many of the other rx libraries (for other languages RxJs : https://github.com/Reactive-Extensions/RxJS/commit/9a813e4dea7ce488422a90cf9b84adc4f4763db9) are starting to support this, is there any chance of seeing this in rx.net as something _I_ can consume without having to worry about licensing or ability to distribute binaries that were bundled with windows 10?

**Comment by ronnyek** [comment]
Is this something that could be contributed by community? I realize something exists, but if plans are not to have this stuff in place any time soon, wondering if some of the pre-made libraries to support serializing linq expressions could be integrated or something.

**Comment by shiftkey** [comment]
cc @bartdesmet @mattpodwysocki

**Comment by bartdesmet** [comment]
This is something we want to look into publishing, pending a transfer of these components to OSS. One tricky part is the dependency on an internal JSON framework, which we may need to get out as well. I'm having sync meetings with the .NET team on some of these libraries and our plan going forward. It's much more generic than just Rx, so it really belongs in the corefx or corefxlabs area.

**Comment by RxDave** [comment]
+1  I'm also interested in this.

**Comment by galvesribeiro** [comment]
We would make a REALLY good use of it in [Orleans](github.com/dotnet/orleans/) :) 

Looking forward for progress on this issue...

**Comment by HowardvanRooijen** [comment]
Any progress to report?

**Comment by glopesdev** [comment]
Also, what is the exact serialization format for expression trees? Is it source code? Will this finally allow for full scripting with expression trees from text?

**Comment by akarnokd** [comment]
Is there any actionable change with this request?

**Comment by grahamehorner** [comment]
@bartdesmet @akarnokd any updates with regards this? can this move forward given publication of System.Text.Json or is this still dependent on a different internal Json framework ?

**Comment by 3GDXC** [comment]
@bartdesmet any updates regards this ?

**Comment by 3GDXC** [comment]
also hoping that an update for https://github.com/dotnet/reactive/issues/181 may come given these may be interlinked ?

**Comment by idg10** [comment]
This was published in May 2021 in the https://github.com/reaqtive/reaqtor repo.

The Bonsai bits are in https://github.com/reaqtive/reaqtor/tree/main/Nuqleon/Core/LINQ
