### ISSUE TITLE
PageNotFoundError about https://www.reactiveui.net/slack

### ISSUE THREAD

**Issue by BoysheO** [dotnet/reactive#2076]
Is alive?

**Comment by BoysheO** [comment]
I'm instersting about rx in Unity,and I hope for join in the development.But what the way I should go?

**Comment by mwadams** [comment]
Hi - 

You can find the intro documentation in book form at https://introtorx.com/
And the slack channel (#rxnet) can be found here: https://reactivex.slack.com
