### ISSUE TITLE
Union doesn't dispose enumerator for empty lists

### ISSUE THREAD

**Issue by Bouke** [dotnet/reactive#2112]
`UnionAsyncIterator` has the same issue as [reported for `UnionIterator`][0] and [fixed in .NET 5][1]. It seems as simple as moving the call to `SetEnumeratorAsync` up just before the `if`. 

https://github.com/dotnet/reactive/blob/bc3472840e7093d8bee84828b84360949701cb50/Ix.NET/Source/System.Linq.Async/System/Linq/Operators/Union.cs#L127-L134

vs

```cs
        IEnumerator<TSource> enumerator = enumerable.GetEnumerator();
        SetEnumerator(enumerator);
        
        ++_state;
        if (enumerator.MoveNext())
        {
            StoreFirst();
```
(source: https://github.com/dotnet/runtime/blob/714a4420805ed53c311b05381c83c88894100fa9/src/libraries/System.Linq/src/System/Linq/Union.cs#L172-L178)

[0]: https://github.com/dotnet/runtime/issues/30607#issuecomment-522198937
[1]: https://github.com/dotnet/corefx/commit/e78caf82ce13b6e1d1359cc239bf0535943cc386

**Comment by idg10** [comment]
Thanks. I added a few tests to confirm the problem, and then verified that the fix you suggest does seem to fix it.

There are a fair few items on the backlog for Async LINQ. I'm hoping to get through a few more of them before doing another release, but if this is blocking you, let me know, and I can do a release without waiting to get any other fixes in.
