### ISSUE TITLE
Synchronize() and Schedulers do the same?

### ISSUE THREAD

**Issue by llehn** [dotnet/reactive#224]
To prevent overlapping OnNext calls, you would use Syncronize() on an observable. 

However when I use any kind of a scheduler on that observable (ThreadPoolScheduler for example), the OnNext calls are serialized without calling Synchronize()

So I have an observable, which does not adhere to Rx contracts and calls OnNext in an overlapping manner.

This code fixes that: 

```
observable.Synchronize().Subscribe(...
```

This code fixes it too:

```
observable.ObserveOn(ImmediateScheduler.Default).Subscribe(...
```

So essentially this behaviour:

```
observable.Synchronize().ObserveOn(ThreadPoolScheduler.Instance).Subscribe(...
```

is equivalent (in my testing) to this:

```
observable.ObserveOn(ThreadPoolScheduler.Instance).Subscribe(...
```

BUT, the variant with `Synchronize()` is around 40% slower in my test case (Subject, 5 producers, 10 consumers, 100 mio messages)

Q: Is the implicit synchronization by using schedulers a feature or a bug? can we rely on it? It's not documented anywhere I looked.

**Comment by bartdesmet** [comment]
`Synchronize()` is your best shot at curing a potentially ill-behaving observable, and you preferably do it as soon as possible before using any operators. Other than for this single operator, all of Rx assumes that observable sequences are indeed sequences and do not exhibit overlapping behavior.

FWIW, the `Synchronize(object)` overload is a different animal altogether; it can be used to write operators that have multiple observable sequences as inputs and synchronize them on a common lock object. This can be a useful first step in writing a new operator, before looking into finer-grained synchronization amongst the input sequences.
