### ISSUE TITLE
Possible race condition in WithLatestFrom when setting the latest

### ISSUE THREAD

**Issue by akarnokd** [dotnet/reactive#227]
If I understand C# memory model correctly (should be very similar to Java's), there is a potential race when [reading _latest](https://github.com/Reactive-Extensions/Rx.NET/blob/1ad21f5a853f2b7be5f3a7e4a8d276e7d28f0d73/Rx.NET/Source/System.Reactive.Linq/Reactive/Linq/Observable/WithLatestFrom.cs#L95) in the main 'rail' and [writing _latest](https://github.com/Reactive-Extensions/Rx.NET/blob/1ad21f5a853f2b7be5f3a7e4a8d276e7d28f0d73/Rx.NET/Source/System.Reactive.Linq/Reactive/Linq/Observable/WithLatestFrom.cs#L143) it from the other 'rail'.

Since the `value` is not volatile here, if `hasLatest` has been set for a previous element, a partially setup/constructed object may be visible on the reader side. For example:

``` cs
class MyValue {
   int field;
}

MyValue v = new MyValue()
v.field = 5;
// other.onNext(v);
_parent._latest = v; // this is plain write
// <-- writer gets interrupted here
_parent._hasLatest = true;
```

Even if constructing `v` has a full barrier, it is possible `v.field = 5` gets reordered with `_parent._latest = v` and reading `_latest.field` on the other side may yield 0.

A solution would be to wrap `TSecond` into an object that is written via volatile write to the _latest field. Then, there is no need for `hasLatest` but check for `null` (or other special value) to see if there is one latest available or not.

**Comment by akarnokd** [comment]
Related PR: #247.

**Comment by danielcweber** [comment]
#247 was merged, closing.
