### ISSUE TITLE
MSDN page update

### ISSUE THREAD

**Issue by vbjay** [dotnet/reactive#242]
[MSDN Page ](https://msdn.microsoft.com/en-us/data/gg577610) still mentions older rx-\* nuget packages.

**Comment by onovotny** [comment]
@martinwoodward @mattpodwysocki @bartdesmet, how do we update that page?

**Comment by vbjay** [comment]
It would be nice if the specific packages were listed like this [page ]([url](http://getglimpse.com/Docs/#download))for glimpse.

**Comment by EamonNerbonne** [comment]
The [RX.net repo's](https://github.com/Reactive-Extensions/Rx.NET) README.md doesn't list updated package names either.

How *do* you install rx, nowadays?

**Comment by vbjay** [comment]
Yes it does.  https://github.com/Reactive-Extensions/Rx.NET#breaking-changes says https://www.nuget.org/packages/System.Reactive/

**Comment by martinwoodward** [comment]
Let me go see about updating that page. In the meantime, would someone be able to make a first go at the page the equivalent page on our side?  I can then see about either getting the content updated to be a copy of the page we have here or ideally just make it redirect to GitHub for us.

**Comment by martinwoodward** [comment]
Take it we would want this page updating too?  https://msdn.microsoft.com/en-us/data/gg577609

**Comment by vbjay** [comment]
Yes please.

**Comment by EamonNerbonne** [comment]
Ahh, to me those looked like namespaces at first (and subsequent) glances.

**Comment by vbjay** [comment]
That is the whole point of their renaming.  The package now matches the
main namespace of the library.

**Comment by akarnokd** [comment]
That page is pretty outdated but [this](https://docs.microsoft.com/en-us/previous-versions/dotnet/reactive-extensions/hh242986(v%3dvs.103)) looks like at least the assembly names are recent. Is this MSDN page within the control of this project even?

**Comment by vbjay** [comment]
I do wish they would link to the GitHub repo.

**Comment by akarnokd** [comment]
The site is no longer updated I'm afraid so we can't do much about that.
