### ISSUE TITLE
What's the logic of CurrentThreadScheduler.IsScheduleRequired?

### ISSUE THREAD

**Issue by Sathyaish** [dotnet/reactive#253]
It seems counter-intuitive that a caller be asked to schedule a work item if the said thread has not had its "scheduled item queue" initialized yet, and that the caller be allowed to run the task immediately on the current thread if the thread _does_ have a queue with items in it.

Or am I reading it wrong? Could you please explain the logic behind determining if a work item must be scheduled on the scheduler or not?

**From CurrentThreadScheduler:**

```
public static bool IsScheduleRequired
{
    get
    {
        return GetQueue() == null;
    }
}
```

**From `Producer<T>`**

```
public IDisposable SubscribeRaw(IObserver<TSource> observer, bool enableSafeguard)
{
    ...

    if (CurrentThreadScheduler.IsScheduleRequired)
    {
        CurrentThreadScheduler.Instance.Schedule(state, Run);
    }
    else
    {
        state.subscription.Disposable = this.Run(state.observer, state.subscription, state.Assign);
    }

    ...
}
```

**Comment by bartdesmet** [comment]
We need to ensure a trampoline exists to avoid run-away recursion when the current-thread scheduler is used. The property just checks that, whether the trampoline (effectively a queue) exists. If it doesn't a call to Schedule is required to set one up.

**Comment by akarnokd** [comment]
@bartdesmet do you see a way that a subsequent major release of Rx.NET switches to injecting `IDisposable` instead of these swing-arounds with schedulers and disposable containers?

```cs
interface ISubscriber<in T> : IObserver<T> {
    void OnSubscribe(IDisposable disposable);
}
```
It would allow synchronous cancellation of typically synchronous sources such as `Range` and `IEnumerable` and no need for recursive scheduling for them.
