### ISSUE TITLE
Asymetrical Subject - Feature suggestion

### ISSUE THREAD

**Issue by bryanerayner** [dotnet/reactive#257]
I am working on a Redis Pub/Sub implementation at my job, where instead of calling `SUBSCRIBE`, `UNSUBSCRIBE`, and `PUBLISH` directly, this will be handled using a Subject.

This is a rough implementation:

``` c#

class RedisSubjects {

    Subject<RedisValue> GetChannel(RedisChannel channel) {
        var subject = new Subject<RedisValue>();
        ISubscriber subscriber = redis.GetSubscriber();

        // When a message is received on the channel, alert subscribers to the subject
        subscriber.Subscribe(channel, (redisChannel, redisValue)=>{
            subject.OnNext(redisValue);
        });

        // ...... In the real implementation, UNSUBSCRIBE is handled by Dispose();

        // This is the tricky part:
        subscription.Subscribe((value)=>{
              // This implementation will cause an endless loop, 
              // as the message published to Redis, will eventually come back
              // through to this code path.
              subscriber.Publish(channel, value);
        });
    }

}

```

What would be ideal, is to have a single Subject, which circumvents this looping problem. The ideal design would be to have two Subjects under the hood, which appear as a single Subject to the outside world. When the outside world calls `OnNext` on this Asymetrical subject, which internal Subject receives the message, would be able to be configured.

```
Subject A (Is a subject in its own right)
===#==== 

Subject B (Is a subject in its own right)
=#====#=

// External callers see only:

AsymetricalSubject
=#=#==#=

// The creator of the Asymetrical Subject, configures Subject A to be the external "inlet"

// This code is called:
AsymetricalSubject.OnNext(@)

// Results in:
Subject A
===#====@
Asymetrical Subject
=#=#==#=@


```

Would this sort of feature have any value to anyone else? Or am I approaching this problem poorly?

**Comment by akarnokd** [comment]
I think this is too peculiar for your case and can be achieved with existing Rx building blocks.
