### ISSUE TITLE
Concat<TSource>(IEnumerable<IObservable<TSource>>) loads eagerly

### ISSUE THREAD

**Issue by kmusick** [dotnet/reactive#267]
[StackOverflow Link](http://stackoverflow.com/questions/39043336/c-sharp-reactive-extensions-rx-firstordefault-enumerates-entire-collection?noredirect=1#comment65440742_39043336)

The following code enumerates all of the objects in the Enumerable even though FirstOrDefault is used

``` csharp
void Main()
{
    var entities = Observable.Defer(() => GetObservable().Concat());
    Entity result = null;
    var first = entities.FirstOrDefaultAsync(i => i.RowId == 1).Subscribe(i => result = i);
    result.Dump();
    buildCalled.Dump();
}

// Define other methods and classes here

public IEnumerable<IObservable<Entity>> GetObservable()
{
    var rows = new List<EntityTableRow>
    {
        new EntityTableRow { Id = 1, StringVal = "One"},
        new EntityTableRow { Id = 2, StringVal = "Two"},
    };
    return rows.Select(i => Observable.Return(BuildEntity(i)));
}

public int buildCalled = 0;
public Entity BuildEntity(EntityTableRow entityRow)
{
    buildCalled++;
    return new Entity { RowId = entityRow.Id, StringVal = entityRow.StringVal };
}

public class Entity
{
    public int RowId { get; set; }
    public string StringVal { get; set; }
}

public class EntityTableRow
{
    public int Id { get; set; }
    public string StringVal { get; set; }
}
```

Shlomo on StackOverflow found that changing GetObservable() to the following enables lazy loading:

``` csharp
public IObservable<IObservable<Entity>> GetObservable()
{
    var rows = new List<EntityTableRow>
    {
        new EntityTableRow { Id = 1, StringVal = "One"},
        new EntityTableRow { Id = 2, StringVal = "Two"},
    };
    return rows.ToObservable().Select(i => Observable.Return(BuildEntity(i)));
}
```

> It appears the implementation of `Concat<TSource>(IEnumerable<IObservable<TSource>>)` is eager in evaluating the enumerable, whereas the implementation of `Concat<TSource>(IObservable<IObservable<TSource>>)` and `ToObservable<TSource>(IEnumerable<TSource>)` maintain laziness appropriately. I can't say I know why.

Is this the intended behavior? There doesn't seem to be any documentation regarding the difference in behavior

**Comment by danielcweber** [comment]
This is (at least partly) by design: since everything (subscribing, observing the immediate values) happens on the same thread (no operator in your example introduces concurrency), there's no chance for anything subscribing to the concatenated observable to unsubscribe - `Subscribe` doesn't even get to return an `IDisposable`. Please verify whether your code even reaches the `result.Dump();` line.

What's odd is that, while inserting a `SubscribeOn(Scheduler.Default)` causes the code to leave the current thread, it still doesn't properly unsubscribe, and the `IEnumerable` is indeed enumerated ad infinitum, or so it seems. Still investigating.

**Comment by danielcweber** [comment]
As far as I can tell, this should be considered a bug for the lack of a workaround, as long as `SchedulerDefaults.TailRecursion` defaults to `ImmediateScheduler.Instance` and `Concat` does not allow overriding the Scheduler for calling `MoveNext`.

**Comment by akarnokd** [comment]
This is likely due to the inability to synchronously cancel an observable. The workaround is to use `CurrentTheadScheduler.Instance` on the `Return` operator and the enumeration will stop:

```cs
class Program
{
    static void Main(string[] args)
    {
        var entities = Observable.Defer(() => GetObservable().Concat());
        Entity result = null;
        var first = entities.FirstOrDefaultAsync(i => i.RowId == 1)
            .Subscribe(i => result = i);
        Console.WriteLine(result);
        Console.WriteLine(buildCalled);

    }
        
    public static IEnumerable<IObservable<Entity>> GetObservable()
    {
        var rows = new List<EntityTableRow>
        {
            new EntityTableRow { Id = 1, StringVal = "One"},
            new EntityTableRow { Id = 2, StringVal = "Two"},
        };
        return rows.Select(i => Observable.Return(BuildEntity(i)
        // vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
           , CurrentThreadScheduler.Instance
        // ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        ));
    }

    public static int buildCalled = 0;
    public static Entity BuildEntity(EntityTableRow entityRow)
    {
        buildCalled++;
        return new Entity { RowId = entityRow.Id, StringVal = entityRow.StringVal };
    }

    public class Entity
    {
        public int RowId { get; set; }
        public string StringVal { get; set; }

        public override string ToString()
        {
            return RowId + " " + StringVal;
        }
    }

    public class EntityTableRow
    {
        public int Id { get; set; }
        public string StringVal { get; set; }
    }
}
```
