### ISSUE TITLE
IStopwatch doesn't provide a Stop or Dispose

### ISSUE THREAD

**Issue by niemyjski** [dotnet/reactive#278]
I think that a stop method or dispose should be implemented on the stop watch. If I'm using a stopwatch or some kind of timer I'd want to be able to stop it so it's not doing any extra work...

https://github.com/Reactive-Extensions/Rx.NET/blob/master/Rx.NET/Source/System.Reactive.Interfaces/Reactive/Concurrency/IStopwatch.cs

https://github.com/Reactive-Extensions/Rx.NET/blob/1ad21f5a853f2b7be5f3a7e4a8d276e7d28f0d73/Rx.NET/Source/System.Reactive.Core/Reactive/Concurrency/Stopwatch.Default.cs

**Comment by shiftkey** [comment]
@niemyjski how are you using this currently in the context of Rx.NET?

**Comment by niemyjski** [comment]
![screen shot 2016-09-15 at 9 33 11 pm](https://cloud.githubusercontent.com/assets/1020579/18573743/0aa1fa96-7b8c-11e6-9a09-6a69e595293c.png)

**Comment by niemyjski** [comment]
We start and stop timers for execution time and I'm a bit worried that a timer may be expensive to leave running (especially high resolution timer...). To me if I don't need it, I should be able to ensure it's not running (e.g., a stopwatch instance).

**Comment by Sathyaish** [comment]
@niemyjski Just curious: what's that a picture of?

**Comment by Thraka** [comment]
@Sathyaish that looks like the GitHub pull request review page.

**Comment by akarnokd** [comment]
Do you think there are resources behind Rx' `IStopwatch`?

What I've seen so far is that they are just exposing system time sources such as the Windows performance counters. Those are independent and they can't be stopped.

**Comment by bartdesmet** [comment]
Stopwatches are merely means to calculate the different between two absolute times to result in a relative time. They are not supposed to hold resources, so there's no need for `IDisposable`.

As for `Stop`, that'd be interesting but add some cost to the implementation to keep track of the cumulative relative time and the last start time given that it'd have to support `[Re]Start` and `Stop` many times. That wasn't a design point for the abstraction in Rx though, and adding it would be a breaking change.

I'll close this issue as there's no resource leak issue. If someone feels strong about stopwatches and virtualized time, it may be worth writing up a proposal that may even entertain .NET Core folks; I've personally found an abstraction over stopwatches (and other "watches" that support measurements of resources, e.g. `MemoryWatch` over `GC.*` APIs) and an algebra to compose these (e.g. combine memory and CPU stopwatches to get allocation rates) to be of use.
