### ISSUE TITLE
Allow IEnumerable "Inputs" for IAsyncEnumerable (enhancement for Ix)

### ISSUE THREAD

**Issue by StephenCleary** [dotnet/reactive#280]
Kind of related to #194 

I'd like to be able to combine `IAsyncEnumerable` and `IEnumerable` in ways that aren't currently straightforward.

Example:

```
class Outer
{
  IEnumerable<Inner> Items { get; }
}

IAsyncEnumerable<Outer> asyncEnumerable = ...;

// What I'd like to do
using (var enumerator = asyncEnumerable.SelectMany(x => x.Items).GetEnumerator())
{
  while (await enumerator.MoveNext())
  {
    Inner item = enumerator.Current;
    ...
  }
}

// What I have to do right now
using (var enumerator = asyncEnumerable.GetEnumerator())
{
  while (await enumerator.MoveNext())
  {
    foreach (Inner item in enumerator.Current.Items)
    {
      ...
    }
  }
}
```

A real-world use case (enumerating packages in the NuGet catalog): https://github.com/StephenClearyApps/NetStandardTypes/blob/c900a812ee636c062078eb8ce35479144c0df771/src/CreateInfrastructure/Program.cs#L27

I believe `SelectMany` (and other) overloads consuming `IEnumerable<T>` are acceptable design-wise. This would be the sequence equivalent of `async`/`await` with synchronous code following the `await` point.

Also, this particular operation (`SelectMany` over an `IEnumerable<T>`) would be common in any kind of batched/paged processing.

**Comment by onovotny** [comment]
@StephenCleary is this scenario the current 4.0 preview and async streams? I think it might be?

**Comment by StephenCleary** [comment]
I'd say it's safe to close this issue. Async streams should remove all my former pain points with Ix.

**Comment by thomaslevesque** [comment]
Has this been solved somehow? Maybe I'm missing something, but I don't see any `SelectMany` overload that does that @StephenCleary described.

Generally speaking, is there a plan to provider methods that mix `IEnumerable<T>` and `IAsyncEnumerable<T>`? For instance:

```csharp
public static IAsyncEnumerable<T> SelectAwait<T, U>(
    this IEnumerable<T> source,
    Func<T, Task<U>> selector);
```

**Comment by StephenCleary** [comment]
I'm comfortable with explicit lifting via `ToAsyncEnumerable`. I think extension methods for `IEnumerable<T>` like the above would:

1. Cause a *lot* of trivial overloads to be added.
2. Be confusing for end users, since they would then get an asynchronous enumerable rather than a regular one.

**Comment by thomaslevesque** [comment]
Fair enough 👍
