### ISSUE TITLE
Easier to use creation methods for IAsyncEnumerable

### ISSUE THREAD

**Issue by StephenCleary** [dotnet/reactive#281]
`Generate` in particular should have a `Func<TState, Task<TResult>> resultSelector` overload, at least. Currently, `Generate` (and all the other shorthand creation methods) only generate synchronous sequences.

This will take some more thought, to determine which overloads are best for `AsyncEnumerator`. They may end up looking very different than the ones for `Enumerator`/`Observable`.

**Comment by BenjaminHolland** [comment]
I agree. Id also add:

A conversion between IEnumerable<Task<T>> and IAsyncEnumerable<T> that preserves the sequence of the source enumerable.

A conversion between IEnumerable<Task<T>> and IAsyncEnumerable<T> that orders the given tasks by completion.

**Comment by onovotny** [comment]
Now that 4.0 preview 1 is out, it could be worth adding a `Generate` that takes a `Func<TState, ValueTask<TResult>> resultSelector`

/cc @bartdesmet

**Comment by StephenCleary** [comment]
I haven't had a chance to play with async streams yet, but the language feature itself may render this issue moot.

**Comment by onovotny** [comment]
Very possibly, if you think this isn't necessary anymore, feel free to close the issue.

**Comment by StephenCleary** [comment]
Closing this. With async streams, the desired API may be quite different.
