### ISSUE TITLE
WithLatestFrom: unexpected behavior when both observables behave as if ended by StartWith

### ISSUE THREAD

**Issue by sramshaw** [dotnet/reactive#300]
What would one expect from the following test, pass or fail?

        [TestMethod]
        public void TestWithLatestFrom()
        {
            var t = Observable.Return(0)
                //.Delay(TimeSpan.FromMilliseconds(100))
                .WithLatestFrom(Observable.Never(3)
                                    .StartWith(2),
                    (a,b) =>a+b)
                .ToEnumerable().ToArray();
            Assert.AreEqual(1,t.Length);
        }

Now what would one expect after uncommenting the one line in the above?

I am in the camp that would expect to have the test pass without the ".Delay"
Order of subscriptions in WithLatestFrom may need to be changed.

**Comment by danielcweber** [comment]
This was proposed by #152. Current behavior is probably preserved for compatibility reasons.

**Comment by sramshaw** [comment]
I would like to contrast this with TakeUntil.
Somehow the implementation of **TakeUntil** is not true to its operator name **for the better**, while **WithLatestFrom** is not true to its operator name **for the worse**. It seems that TakeUntil was especially fixed for subscription order according to a comment in the code on line 46:
> //  COMPAT - Order of Subscribe calls per v1.0.10621

What could justify not maximizing the effect of the WithLatestFrom operator when it was done for TakeUntil?


More details on TakeUntil:

TakeUntil does not have this issue. See this passing test:

        [TestMethod]
        public void TestTakeUntil()
        {
            var t = Observable.Return(0)
                .TakeUntil(Observable.Return(1))
                .ToEnumerable().ToArray();
            Assert.AreEqual(0, t.Length);
        }


More details on the naming:

Somehow the implementation of TakeUntil is not true to its operator name for the better, while WithLatestFrom is not true to its operator name for the worse:

- TakeUntil: the chosen words seems to indicate a preference for taking first, which in fact does not match the implementation which fits rather TakeUnless: 'take unless the secondary observable emits'
- WithLatestFrom: the chose words seems to indicate that the context observable was ready by the time something emits on the source observable. This would make for a better operator but is somehow not implemented as such.

**Comment by sramshaw** [comment]
Daniel,
If compatibility is the reason, closing the related issue(s) would be preferred as well as and a comment in code, as was done for TakeUntil. Leaving these open smells of abandonment rather than decision.

**Comment by danielcweber** [comment]
The actual reasons are unclear to me. I agree about the impression that unresponded issues and pull requests leave. To be fair, there are issues and pull requests that do get attention, let's see if we can get some 'official' opinion here.

**Comment by danielcweber** [comment]
Fixed by #152.

**Comment by sramshaw** [comment]
Thanks!
