### ISSUE TITLE
Strange behavior with Observable.Create<T>(async subscription)

### ISSUE THREAD

**Issue by softeering** [dotnet/reactive#304]
Hi there,

I'm totally new to Rx and there is something I don't understand when trying to create an observable with an ASYNC subscription.
Let's assume I have a console app and I run the code below:
```
class Program
{
	static void Main(string[] args)
	{
		new Program().Run();
		Console.WriteLine("FULL COMPLETE");
		Console.ReadLine();
	}

	public void Run()
	{
		Console.WriteLine("BEFORE SYNC SUB");
		this.SyncObservable().Subscribe(i =>
		{
			Console.WriteLine($"SYNC {i}");
		});
		Console.WriteLine("AFTER SYNC SUB");

		Console.WriteLine("BEFORE ASYNC SUB");
		this.AsyncObservable().Subscribe(i =>
		{
			Console.WriteLine($"ASYNC {i}");
		});
		Console.WriteLine("AFTER ASYNC SUB");
	}

	public IObservable<int> SyncObservable()
	{
		return Observable.Range(0, 10);
	}

	public IObservable<int> AsyncObservable()
	{
		return Observable.Create<int>(async (observer, cancellationToken) =>
		{
			// let's say this lambda connects to a SQL db and asynchronously executes a reader
			for (int i = 0; i < 10; i++)
			{
				await Task.Delay(50);
				observer.OnNext(i);
			}
			observer.OnCompleted();
		});
	}
}
```
The output is the following:
```
BEFORE SYNC SUB
SYNC 0
SYNC 1
SYNC 2
SYNC 3
SYNC 4
SYNC 5
SYNC 6
SYNC 7
SYNC 8
SYNC 9
AFTER SYNC SUB
BEFORE ASYNC SUB
AFTER ASYNC SUB
FULL COMPLETE
ASYNC 0
ASYNC 1
ASYNC 2
ASYNC 3
ASYNC 4
ASYNC 5
ASYNC 6
ASYNC 7
ASYNC 8
ASYNC 9
```
But I would have expected this:
```
BEFORE SYNC SUB
SYNC 0
SYNC 1
SYNC 2
SYNC 3
SYNC 4
SYNC 5
SYNC 6
SYNC 7
SYNC 8
SYNC 9
AFTER SYNC SUB
BEFORE ASYNC SUB
ASYNC 0
ASYNC 1
ASYNC 2
ASYNC 3
ASYNC 4
ASYNC 5
ASYNC 6
ASYNC 7
ASYNC 8
ASYNC 9
AFTER ASYNC SUB
FULL COMPLETE
```

I understand that the lambda passed to Create<int> is asynchronous but why is .Subscribe not waiting for the .OnCompleted() method to be called to go back to the normal flow?

I don't want Subscribe() to be executed "in the background", I just need to create an Observable on top of an ASYNC IO operation (read from database for example). I'd like the Subscribe method to behave as the one called on the Observable created via Observable.Range(...)

Other question: is there a way to call some async code in the .Subscribe(..) lambda and await?

Thanks in advance for your help

-David

**Comment by danielcweber** [comment]
First of all, there's no such thing as a sync observable and an async observable. It's true that `SyncObservable` completes synchronously (that is, before `Subscribe` returns) in this case, however, it's not due to `Subscribe` 'waiting' on completion. `Subscribe` itself never waits for anything. It's just that `Observable.Range` starts generating the values on the same thread that `Subscribe` was called on, therefore you have a completely synchronous flow. Experiment with `Range`, see if you can pass it an `IScheduler`, pass in `Scheduler.Default` and see what happens.

I don't get what you are really trying to achieve with `AsyncObservable`. Do you want to block the calling thread until it has completed? Do you want to extract a single value from it?

**Comment by softeering** [comment]
Thanks Daniel
You're right, it must be because of the used scheduler.

What I'd like is that the "AsyncObservable" above behaves like the Observable.Range case - i.e. subsribe callback should complete going back to the console app flow
Which scheduler should I use when generating the Observable from async lamda? where do I need to define this?

Thanks

**Comment by softeering** [comment]
FYI, I'd like to have a SYNCHRONOUS flow even when the Observable is created from a async / await lambda
And it seems I should use a specific scheduler and Subscribe on it but I don't know which one to use and where to put this

Thanks

**Comment by danielcweber** [comment]
You can achive synchronous flow, but not by subscribing yourself but by using e.g. the blocking `First`, `FirstOrDefault`, `Last`, `LastOrDefault` methods. Note that this will most certainly block your main thread, which is probably what you want in your program entry point but is generally discouraged.

**Comment by softeering** [comment]
Ok thanks
There is something I don't get here but why not. I don't understand why it is not possible to subscribe "synchronously" to a Observable when it has been created from an ASYNC lambda.
ASYNC / AWAIT here are simply IO operations and not about "creating" a thread.

Also about ConfigureAwait, I don't think that deadlock can happen in a console app because of this. There is no synchronization context in a console app (opposed to ASP.NET of WinForms)

Thanks again for your time

**Comment by danielcweber** [comment]
As I said, `Subscribe` registers an `IObserver` to the observable that is called back when it produces a value. (The overload of `Subscribe` is merely an extension that throws all values away). `Subscribe` will not block, it will not wait, in your case, it will return as soon as the first `Task.Delay(50);` returns a task that is not completed, thus scheduling its continuation on the thread pool.

**Comment by softeering** [comment]
OK let's take this code
```
using System;
using System.Data.SqlClient;
using System.Reactive.Disposables;
using System.Reactive.Linq;

namespace ConsoleApplication2
{
	class Program
	{
		private const string ConnectionString = "server=localhost; database=TEST; integrated security=true";
		private const string Query = "select top 50 ID from TESTKEY";

		static void Main(string[] args)
		{
			new Program().Run();
			Console.WriteLine("FULL COMPLETE");
			Console.ReadLine();
		}

		public void Run()
		{
			Console.WriteLine("BEFORE SYNC READ");
			this.SyncRead().Subscribe(i =>
			{
				Console.WriteLine($"SYNC {i}");
			});
			Console.WriteLine("AFTER SYNC READ");

			Console.WriteLine("BEFORE ASYNC READ");
			this.AsyncRead().Subscribe(i =>
			{
				Console.WriteLine($"ASYNC {i}");
			});
			Console.WriteLine("AFTER ASYNC READ");
		}

		public IObservable<int> SyncRead()
		{
			return Observable.Create<int>(observer =>
			{
				using (var connection = new SqlConnection(ConnectionString))
				{
					connection.Open();

					using (var command = connection.CreateCommand())
					{
						command.CommandText = Query;
						using (var reader = command.ExecuteReader())
						{
							while (reader.Read())
							{
								observer.OnNext(reader.GetInt32(0));
							}

							observer.OnCompleted();
						}
					}
				}

				return Disposable.Empty;
			});
		}

		public IObservable<int> AsyncRead()
		{
			return Observable.Create<int>(async (observer, cancellationToken) =>
			{
				using (var connection = new SqlConnection(ConnectionString))
				{
					await connection.OpenAsync().ConfigureAwait(false);

					using (var command = connection.CreateCommand())
					{
						command.CommandText = Query;
						using (var reader = await command.ExecuteReaderAsync().ConfigureAwait(false))
						{
							while (await reader.ReadAsync().ConfigureAwait(false))
							{
								observer.OnNext(reader.GetInt32(0));
							}

							observer.OnCompleted();
						}
					}
				}
			});
		}
	}
}
```
And here is the output
```
BEFORE SYNC READ
SYNC 1
SYNC 1
SYNC 1
SYNC 1
SYNC 1
...
SYNC 1
SYNC 1
SYNC 1
SYNC 1
SYNC 1
AFTER SYNC READ
BEFORE ASYNC READ
AFTER ASYNC READ
FULL COMPLETE
ASYNC 1
ASYNC 1
ASYNC 1
ASYNC 1
ASYNC 1
...
ASYNC 1
ASYNC 1
ASYNC 1
ASYNC 1
ASYNC 1
```

I don't get why they behave differently in terms of flow.
I don't want the second one to be executed in the background, I'm just using ASYNC / AWAIT IO operations.
Why is the underlying Task passed to Observable.Create not awaited until the .OnCompleted call? (same as the synchronous code does)

Thanks

**Comment by danielcweber** [comment]
As I said, you have a misunderstanding of what Subscribe actually does. For a good introduction, check out https://channel9.msdn.com/Blogs/codefest/DC2010T0100-Keynote-Rx-curing-your-asynchronous-programming-blues

**Comment by akapoo11** [comment]
Hi, AsyncObservable is behaving as async because of await keyword, which basically returns the flow to the caller and then once Task.Delay(50) is complete, it runs the next lines on callback.

remove await from following and you would see same behavior
await Task.Delay(50);

**Comment by softeering** [comment]
Thanks akapoo11 but I don't want to remove "await" from the code. That's exactly what I want to have: be able to call IO async code within a subscribe lambda.

**Comment by aalmada** [comment]
@softeering I suggest you watch the following presentation. Paul shows how observables and async/await can work together. https://www.youtube.com/watch?v=5DZ8nC0ENdg

**Comment by softeering** [comment]
Thanks aalmada. Interesting video even if it does not apply to my use-case.
I don't have one TASK returning an item but would like to "stream" items generated by an asynchronous method as shown in the code above

-David

**Comment by shiftkey** [comment]
@softeering

> FYI, I'd like to have a SYNCHRONOUS flow even when the Observable is created from a async / await lambda

This is not going to be possible with `async`/`await`, as the usage of `await` is not intended to block.  Let's look at this example:

```csharp
public void Run()
{
  // this is the caller to the asynchronous subscription
  Console.WriteLine("BEFORE ASYNC SUB");

  // the return value from a subscribe is a disposable
  // you can dispose of this to dispose of the subscription
  var disposable = AsyncObservable().Subscribe(i =>
  {
    Console.WriteLine($"ASYNC {i}");
  });

  Console.WriteLine("AFTER ASYNC SUB");
  Console.ReadLine();
}

public IObservable<int> AsyncObservable()
{
  return Observable.Create<int>(async (observer, cancellationToken) =>
  {
    // this is the asynchronous subscription method
    for (int i = 0; i < 10; i++)
    {
      await Task.Delay(50);
      observer.OnNext(i);
    }
    observer.OnCompleted();
  });
}
```

The IL generated by the compiler when you use `async`/`await` is a state machine. I'll defer to @fekberg's blog post on the details - http://www.filipekberg.se/2013/01/16/what-does-async-await-generate/ - but all this is here for is to determine when the task is completed. 

When the runtime encounters the `await` keyword, this is the approximate flow:

 - task created, i.e. `Task.Delay` starts counting
 - the caller (the subscription method) sets up state machine to wrap the task
 - set up callback to continue method execution when the task completes
 - attaches callback to task awaiter 
 - yields execution of the subscription method to it's caller - the `Run` method
 - program execution continues
 - it reaches the `Console.ReadLine()` and pauses, waiting for input
 - _... we still have some time to wait around..._
 - the `Task.Delay` completes
 - the callback is invoked, and we return to the subscription method

This is why you are seeing `AFTER ASYNC READ` and `FULL COMPLETE` printed out before the `Task.Delay` has completed.

@softeering instead of trying to mash these asynchronous concepts into synchronous code, are you able to walk through the problem you're trying to solve? Perhaps there's a different way to tackle this...

**Comment by softeering** [comment]
@shiftkey Thanks for the detailed explanation - and happy new year by the way

**Comment by michaeldz** [comment]
Hello !

To wait the enumeration of the sequence you can use something like:
`await observable`  

But there is one problem ...  
  
`using System;
using System.Reactive.Linq;
using System.Reactive.Threading.Tasks;
using System.Threading;
using System.Threading.Tasks;

namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            //Task.Run(Run);
            Run();
            Console.ReadLine();
        }

        static readonly Random Rnd = new Random();

        public static async Task Run()
        {
            Console.WriteLine("BEFORE ASYNC SUB");

            var source1 = AsyncObservable();
            var disposable1 = source1.Subscribe(i =>
            {
                Console.WriteLine($"ASYNC1 {i}");
            }, () =>
            {
                Console.WriteLine("ASYNC1 COMPLETED");
            });

            var source2 = AsyncObservable();
            var disposable2 = source2.Subscribe(i =>
            {
                Console.WriteLine($"ASYNC2 {i}");
            }, () =>
            {
                Console.WriteLine("ASYNC2 COMPLETED");
            });

            Task.WaitAll(source1.ToTask(), source2.ToTask());

            //await source1;
            //await source2;

            Console.WriteLine("AFTER ASYNC SUB");
        }

        private static int cnt1, cnt2;

        public static IObservable<int> AsyncObservable()
        {
            Console.WriteLine($"cnt1 {Interlocked.Increment(ref cnt1)}");

            return Observable.Create<int>(async (observer, cancellationToken) =>
            {
                Console.WriteLine($"cnt2 {Interlocked.Increment(ref cnt2)}");

                Console.WriteLine();

                await Task.Delay(100);

                var to = Rnd.Next(30, 100);

                Console.WriteLine($"Enmerate until {to} ...");

                for (int i = 0; i < to; i++)
                {
                    await Task.Delay((i*5+50)%300);
                    observer.OnNext(i);
                }
                observer.OnCompleted();
            });
        }
    }
} `

If you execute the code you will see some interesting results:  

BEFORE ASYNC SUB
cnt1 1
cnt2 1
cnt1 2
cnt2 2
**cnt2 3
cnt2 4**

Enmerate until 50 ...
Enmerate until 33 ...
**Enmerate until 70 ...
Enmerate until 71 ...**
ASYNC1 0
ASYNC2 0
ASYNC1 1
ASYNC2 1
...
ASYNC1 49
ASYNC1 COMPLETED
ASYNC2 53
...
ASYNC2 69
**AFTER ASYNC SUB**
ASYNC2 70
ASYNC2 COMPLETED

I don't know how to fix this.

**Comment by danielcweber** [comment]
@ghuntley Please close, issue was based on a misunderstanding of what `Subscribe` does.
