### ISSUE TITLE
Publish does not notify all subscribers on error

### ISSUE THREAD

**Issue by aliveli186** [dotnet/reactive#306]
Publish seems to notify **only the first** subscriber on error, the others are left unaware of the error.
This makes the situation unrecoverable from the side of the unaware subscribers.
Since on completion all of the subscribers are notified this seems to be a bug. If not then could you please show a workaround.

The code to reproduce the issue:
```
private static void Main(string[] args)
{
    var source = Observable.Range(1, 5, TaskPoolScheduler.Default)
                            .SelectMany(i => i == 4 /*i == 0*/
                                                ? Observable.Throw<int>(new InvalidOperationException("Something went wrong."), CurrentThreadScheduler.Instance)
                                                : Observable.Return(i, CurrentThreadScheduler.Instance));
    var multicastSource = source.Spy("Source").Publish();
    var onMessageReceived = multicastSource.AsObservable();

    Console.WriteLine("{0}Subscribing.{0}", Environment.NewLine);

    var disp1 = onMessageReceived.Spy("   1st Subscriber").Subscribe();
    var disp2 = onMessageReceived.Spy("     2nd Subscriber").Subscribe();

    Console.WriteLine("{0}Connecting.{0}", Environment.NewLine);

    multicastSource.Connect();

    Console.WriteLine("{0}Press any key to unsubscribe.{0}", Environment.NewLine);
    Console.ReadKey();

    disp1.Dispose();
    disp2.Dispose();

    Console.WriteLine("{0}Press any key to exit.{0}", Environment.NewLine);
    Console.ReadKey();
}
```

Output:

> Source: Observable obtained on Thread: 9
> 
> Subscribing.
> 
>    1st Subscriber: Observable obtained on Thread: 9
>    1st Subscriber: Subscribed to on Thread: 9
>    1st Subscriber: Subscription completed.
>      2nd Subscriber: Observable obtained on Thread: 9
>      2nd Subscriber: Subscribed to on Thread: 9
>      2nd Subscriber: Subscription completed.
> 
> Connecting.
> 
> Source: Subscribed to on Thread: 9
> Source: Subscription completed.
> 
> Press any key to unsubscribe.
> 
> Source: OnNext(1) on Thread: 11
>    1st Subscriber: OnNext(1) on Thread: 11
>      2nd Subscriber: OnNext(1) on Thread: 11
> Source: OnNext(2) on Thread: 11
>    1st Subscriber: OnNext(2) on Thread: 11
>      2nd Subscriber: OnNext(2) on Thread: 11
> Source: OnNext(3) on Thread: 11
>    1st Subscriber: OnNext(3) on Thread: 11
>      2nd Subscriber: OnNext(3) on Thread: 11
> **Source: OnError(System.InvalidOperationException: Something went wrong.) on Thread: 11
>    1st Subscriber: OnError(System.InvalidOperationException: Something went wrong.) on Thread: 11
>    1st Subscriber: Cleaned up on Thread: 11
> Source: Cleaned up on Thread: 11**

When there is no exception (modify the source code line: i == 4 to i == 0) the on complete notification is received by all subscribers.

Output:

> Source: Observable obtained on Thread: 10
> 
> Subscribing.
> 
>    1st Subscriber: Observable obtained on Thread: 10
>    1st Subscriber: Subscribed to on Thread: 10
>    1st Subscriber: Subscription completed.
>      2nd Subscriber: Observable obtained on Thread: 10
>      2nd Subscriber: Subscribed to on Thread: 10
>      2nd Subscriber: Subscription completed.
> 
> Connecting.
> 
> Source: Subscribed to on Thread: 10
> Source: Subscription completed.
> 
> Press any key to unsubscribe.
> 
> Source: OnNext(1) on Thread: 12
>    1st Subscriber: OnNext(1) on Thread: 12
>      2nd Subscriber: OnNext(1) on Thread: 12
> Source: OnNext(2) on Thread: 12
>    1st Subscriber: OnNext(2) on Thread: 12
>      2nd Subscriber: OnNext(2) on Thread: 12
> Source: OnNext(3) on Thread: 12
>    1st Subscriber: OnNext(3) on Thread: 12
>      2nd Subscriber: OnNext(3) on Thread: 12
> Source: OnNext(4) on Thread: 12
>    1st Subscriber: OnNext(4) on Thread: 12
>      2nd Subscriber: OnNext(4) on Thread: 12
> Source: OnNext(5) on Thread: 12
>    1st Subscriber: OnNext(5) on Thread: 12
>      2nd Subscriber: OnNext(5) on Thread: 12
> **Source: OnCompleted() on Thread: 12
>    1st Subscriber: OnCompleted() on Thread: 12
>    1st Subscriber: Cleaned up on Thread: 12
>      2nd Subscriber: OnCompleted() on Thread: 12
>      2nd Subscriber: Cleaned up on Thread: 12
> Source: Cleaned up on Thread: 12**

You can get the Spy extension from: http://stackoverflow.com/a/20220756

**Comment by danielcweber** [comment]
That's probably due to the `Subscribe` extension you are using (the one without overloads). They register an onError-handler that simply rethrows the exception. The exception will bubble up the whole call stack (on one of the threadpool threads since you're using `TaskPoolScheduler.Default`) preventing any other onError-handlers from being called.

Try using the `Subscribe`-extension that takes explicict handlers for all three notifications, then ignore errors, see what happens.

**Comment by aliveli186** [comment]
When the 3 notifications are added to subscribe it works OK.
```
var disp1 = onMessageReceived.Spy("   1st Subscriber").Subscribe(i => { }, ex => { Console.WriteLine("   1st Error!"); }, () => { Console.WriteLine("   1st Completed"); });
var disp2 = onMessageReceived.Spy("     2nd Subscriber").Subscribe(i => { }, ex => { Console.WriteLine("     2nd Error!"); }, () => { Console.WriteLine("    2nd Completed"); });
```

Output:
> Source: OnError(System.InvalidOperationException: Something went wrong.) on Thread: 11
>    1st Subscriber: OnError(System.InvalidOperationException: Something went wrong.) on Thread: 11
>    1st Error!
>    1st Subscriber: Cleaned up on Thread: 11
>      **2nd Subscriber: OnError(System.InvalidOperationException: Something went wrong.) on Thread: 11
>      2nd Error!
>      2nd Subscriber: Cleaned up on Thread: 11**
> Source: Cleaned up on Thread: 11

But normally inside my code I don't call Subscribe like that, there are lots of chained codes.
It's used in many places like;
`source.SelectMany(value => onMessageReceived.Where(i => i == value));`
So how exactly I need to proceed?

1. I tried to wrap onMessageReceived with `Observable.Create<int>` to add the 3 notifications, it doesn't work.
2. I tried to put `SubscribeOn(TaskPoolScheduler.Default)` before `Subscribe()` but this time only the second subscriber receives the on error event, the first one does not.
3. I tried to put `ObserveOn(TaskPoolScheduler.Default)` before `Subscribe()` and it works but the first subscriber doesn't receive stack trace of the exception. If I use ObserveOn how can I know which scheduler to observe on to?
Output:

> Source: OnError(System.InvalidOperationException: Something went wrong.) on Thread: 11
>    1st Subscriber: OnError(System.InvalidOperationException: Something went wrong.) on Thread: 11
>    1st Subscriber: Cleaned up on Thread: 11
>      **2nd Subscriber: OnError(System.InvalidOperationException: Something went wrong.
>    at System.Reactive.PlatformServices.ExceptionServicesImpl.Rethrow(Exception exception)
>    at System.Reactive.Stubs.<>c.<.cctor>b__2_1(Exception ex)
>    at System.Reactive.AnonymousSafeObserver`1.OnError(Exception error)
>    at System.Reactive.ScheduledObserver`1.Dispatch(ICancelable cancel)
>    at System.Reactive.Concurrency.Scheduler.<>c.<ScheduleLongRunning>b__72_0(Action`1 a, ICancelable c)
>    at System.Reactive.Concurrency.TaskPoolScheduler.<>c__DisplayClass7_0`1.<ScheduleLongRunning>b__0()
>    at System.Threading.Tasks.Task.InnerInvoke()
>    at System.Threading.Tasks.Task.Execute()) on Thread: 11
>      2nd Subscriber: Cleaned up on Thread: 11**
> Source: Cleaned up on Thread: 11

**Comment by danielcweber** [comment]
If you are really not interested in the exceptions (which you should be unless there's logging somewhere else), you could use `Catch` before `Subscribe`.

**Comment by aliveli186** [comment]
I want to Retry the whole chain but I can't get any notification of error so it doesn't retry.
The chain is like this:
Connect to server.
Start reading the network stream till the stream is disposed. (This reading part is published.)
- A subscriber subscribes to listen to some administrative commands which is the 1st subscriber.
- Another subscriber subscribes to listen to some other messages which is the 2nd subscriber.

Most of the operations are done over the 2nd subscriber. And when it receives an exception (like disconnection) it wants to retry the whole chain, to reconnect to the server and start the reading.
Since it can't receive any notifications it's orphaned.

**Comment by danielcweber** [comment]
Well, what about using `Catch` for the first subscriber and using `Retry` for the second?

**Comment by aliveli186** [comment]
I solved the issue with an `ObserveOn(TaskPoolScheduler.Default)` after  `AsObservable()` before `Subscribe()`.

`var onMessageReceived = multicastSource.AsObservable().ObserveOn(TaskPoolScheduler.Default);`

As far as I understood it the source produces values and each subscriber receives the notifications on the same thread. When and exception is fired since all notifications are received in the same thread only the first subscriber is able to process it others don't.
Observe on makes all subscribers to receive the notifications from different threads and then each one is able to receive the OnError event. This makes it possible to Retry the whole chain.
