### ISSUE TITLE
Cancellation in Ix.Async introduces subtle race conditions

### ISSUE THREAD

**Issue by danielcweber** [dotnet/reactive#319]
Currently, `AsyncIterator`, the base class of most implementations of `IAsyncEnumerable` [registers a callback](https://github.com/Reactive-Extensions/Rx.NET/blob/master/Ix.NET/Source/System.Interactive.Async/AsyncIterator.cs#L87) in its `MoveNext` method on the `CancellationToken` that was passed in.

Overrides of `Dispose` regularly dispose and nullify inner instances of `IAsyncEnumerable`, [e.g. in the TakeWhile operator](https://github.com/Reactive-Extensions/Rx.NET/blob/b84974db5d4940b88308b98723893cce9f10f386/Ix.NET/Source/System.Interactive.Async/Take.cs#L87).

This introduces race conditions. While `MoveNextCore` might observe the current iterator state to be ` AsyncIteratorState.Iterating`, it may be cancelled at the very next moment, throwing a `NullReferenceException` ([e.g. here](https://github.com/Reactive-Extensions/Rx.NET/blob/b84974db5d4940b88308b98723893cce9f10f386/Ix.NET/Source/System.Interactive.Async/Take.cs#L108)). I've been runnng into those repeatedly since upgrading to v3.

There might be conflicting views on this. One might state that, when you cancel an async iterator, all bets are off. I believe that the only thing that should be thrown are `TaskCanceledExceptions`, and such things as `NullReferenceExceptions` cannot be anticipated or handled well. As a result, you cannot write good async software that properly supports cancellation.

A possible workaround might be avoid the `CancellationToken` callback and check `IsCancellationRequested` in `MoveNext` before and after the call to `MoveNextCore`, disposing the iterator if necessary. There might, however, be code around that relies on the iterator being disposed immediately.

Any thoughts on this?

**Comment by onovotny** [comment]
Do you have a repro of this? Are the iterator and `Dispose` being called on different threads?

The iterator itself is not thread-safe, and was never intended to be so far. That said, I agree we should never be throwing `NullReferenceException`'s. Once `Dispose` is called, `Current` will be `default(T)`, so essentially useless. In the case you highlighted, the fix could be just to do `enumerator?.Current` to protect against the condition you describe, but I'd like to understand how you got there if the iterator was only "touched" by a single thread?

>There might, however, be code around that relies on the iterator being disposed immediately.
I'm fairly sure there is....but I'd have to check.

**Comment by danielcweber** [comment]
Yes, `MoveNext` and its cancellation will have to happen on different threads. It's the case e.g. if you have `ct` cancelled after some amount of time (by `CancellationTokenSource.CancelAfter(time)).

I will try to setup a repro although it will be very nondeterministic.

**Comment by danielcweber** [comment]
Here's a repro unit test that fails after a few seconds on my machine:

    [Fact]
    public async Task CancellationBug_in_Ix()
    {
        var rnd = new Random();

        var source = AsyncEnumerable
            .Repeat(42)
            .TakeWhile(x => x > 0);

        while (true)
        {
            using (var e = source.GetEnumerator())
            {
                while (true)
                {
                    var cts = new CancellationTokenSource();
                    cts.CancelAfter(rnd.Next(0, 20));
 
                    try
                    {
                        if (!await e.MoveNext(cts.Token).ConfigureAwait(false))
                            break;
                    }
                    catch (ObjectDisposedException)
                    {
                        break;
                    }
                }
            }
        }
    }

**Comment by onovotny** [comment]
@danielcweber I haven't tested the fix totally yet, but thoughts on the PR, #320?

**Comment by danielcweber** [comment]
@onovotny I filed an additional PR (#321) that mitigates the issue at least in one place.

**Comment by danielcweber** [comment]
@onovotny #321 fixes a related issue.

**Comment by danielcweber** [comment]
@bartdesmet Could you please weigh in on this discussion? I see Rx 4 has had a preview released with no development or clear decision on this issue. It is of great interest for us that these race conditions are fixed in some future version of Ix.Async. Thanks a lot.

**Comment by letrec** [comment]
I second that. This bug breaks normal cancellation handing pattern in user code and requires ugly workarounds that break compositionality.

**Comment by letrec** [comment]
I believe that AsyncIterator.Dispose shouldn't dispose it's instance of CancellationTokenSource. This causes the ObjectDisposedException in the first place. Another option is to make all related code ObjectDisposedException resistant, but it doesn't look reasonable to me.

**Comment by letrec** [comment]
I'm getting NullReferenceExceptions from Scan in exactly the same way as described by the topic originator.

**Comment by letrec** [comment]
It would be much appreciated to at least resume this conversation.

**Comment by Sumo-MBryant** [comment]
Is this the issue you are referring to @letrec ?

```csharp
[Fact]
public async Task ObjectDisposedTest()
{
    var enumerator = new[] { 0 }.ToAsyncEnumerable().GetEnumerator();

    using (var cancellationTokenSource = new CancellationTokenSource())
    {
        cancellationTokenSource.Cancel();
        await enumerator.MoveNext(cancellationTokenSource.Token);
    }
}
```

This throws ```ObjectDisposedException```.

**Comment by letrec** [comment]
@Sumo-MBryant, yes. It also fails with a NRE.

**Comment by letrec** [comment]
I've given up on this. Waiting for implementation of github.com/dotnet/csharplang/blob/master/proposals/async-streams.md - I'm sure Mr. Toub will get it right.

**Comment by danielcweber** [comment]
C# 8's async iterators will handle cancellation differently.

**Comment by stukselbax** [comment]
> C# 8's async iterators will handle cancellation differently.

We have faced the problem when passing `CancellationToken` from aspnetcore action (which use `HttpContext.RequestAborted` actually) to EFCore and get the following error: (we are using 2.2)

```
System.ObjectDisposedException: The CancellationTokenSource has been disposed.
at System.Threading.CancellationTokenSource.ThrowObjectDisposedException()
at System.Linq.AsyncEnumerable.AsyncIterator`1.MoveNext(CancellationToken cancellationToken) in D:\a\1\s\Ix.NET\Source\System.Interactive.Async\AsyncIterator.cs:line 91
at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext(CancellationToken cancellationToken)
at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteSingletonAsyncQuery[TResult](QueryContext queryContext, Func`2 compiledQuery, IDiagnosticsLogger`1 logger, Type contextType)
```

this is probably because of the following:

```c#
                using (cancellationToken.Register(Dispose))
                using (var cts = CancellationTokenSource.CreateLinkedTokenSource(cancellationToken, cancellationTokenSource.Token))
```

The [documentation for `cancellationToken.Register(Action)`](https://docs.microsoft.com/en-us/dotnet/api/system.threading.cancellationtoken.register?view=netcore-2.2) states:

> If this token is already in the canceled state, the delegate will be run immediately and synchronously. Any exception the delegate generates will be propagated out of this method call.

Will you fix that?

**Comment by danielcweber** [comment]
That's Ix.Async 3.x code. It'll probably not be changed anymore, especially since the "right" way of how to deal with cancellation there was already subject of this thread and unresolved. I highly recommend migrating to EFCore 3.x (and Ix.Async 4.x) where Cancellation is handled at a different place (not in MoveNext anymore).
