### ISSUE TITLE
Thread safety of Observable.Buffer(int) method overload

### ISSUE THREAD

**Issue by NikGovorov** [dotnet/reactive#323]
Hi Rx.NET Team,

I'm encountering the issue of Observable.Buffer(int) method overload not being thread safe. According to the implementation it's not supposed to be thread safe:  https://github.com/Reactive-Extensions/Rx.NET/blob/master/Rx.NET/Source/System.Reactive.Linq/Reactive/Linq/Observable/Buffer.cs#L79. 

Is there any explanation for it? Is it by design and why?

Thanks.

**Comment by akarnokd** [comment]
Not sure why you need thread safety there. The source of `Buffer` should provide the `OnNext` calls in a non-concurrent, non-overlapping manner as required by the observable protocol. This guarantees that buffer manipulation in the `OnXXX` methods should be safe to perform without further synchronization. 

Do you by any chance use a `Subject` from multiple threads before such a `Buffer` operation? A `Subject`s `OnNext` method should not be called concurrently either.

**Comment by NikGovorov** [comment]
@akarnokd,  I don't believe that what you wrote is correct, I think it's actually opposite. @onovotny, @ghuntley could you please comment this?

**Comment by akarnokd** [comment]
How can you even use `Buffer` concurrently?

**Comment by NikGovorov** [comment]
In the same way as other Buffer method overloads are implemented: simple lock.

**Comment by akarnokd** [comment]
With size-based buffers, it makes no sense. There is nothing else but the upstream signaling items sequentially, and once the buffer gets full, it is emitted and replaced by a new buffer - all done sequentially and there is no need for a lock.

The timed versions, however, need a lock because there is another party that can interfere: the timer thread triggering the end of a buffer which could happen at any time and from any thread. Changing the buffer or emitting it while there is work being done on it is unsafe and can lead to memory visibility issues, half-constructed objects and missing references. The lock ensures correct publication and ensures mutual exclusion between the publication and manipulation of the buffer.

**Comment by NikGovorov** [comment]
Thanks, I see the rationale behind your explanation. I checked other operators that don't involve timers and looks like you're right because they are all non thread safe, so it's by design. Does  Observable.FromEventPattern generate synchronised observer?

**Comment by danielcweber** [comment]
What can be said about notifications (OnNext etc) that, albeit happening sequentially, occur on different threads? Will the latest state be visible to all threads?

**Comment by akarnokd** [comment]
The operator is responsible for ensuring non-overlapping, non-concurrent invocation of the downstream observer if said operator has a potential asynchronous boundary. In addition, crossing this boundary must establish a happens-before relation with the memory changes before and after the boundary.

If you queue up items into a `ConcurrentQueue`, schedule a task via `IScheduler.Scheduler`, use certain atomics such as `Interlocked.Increment`, you will get this happens-before relationship. 

```cs
IObserver<T> downstream = ...

public void OnNext(T item) {
    // <-------------- boundary here
    scheduler.Schedule(item, (s, i) => {
        downstream.OnNext(i);
        return Disposables.Empty();
    });
}
```

When calling this `OnNext` with the following struct/class:

```cs
T item = new T();
item.field_A = 1;
item.field_B = 2;

OnNext(item);
```

It is guaranteed the `downstream` will see `item` fully initialized and committed to memory and `item.field_A == 1 && itemfield_B == 2` to be true.

Note, however, that this requires items that are effectively immutable at the point of crossing the boundary. For example, if we mutate `item` after `OnNext`, all bets are off and can lead to any output:

```cs
T item = new T();
item.field_A = 1;
item.field_B = 2;

OnNext(item);

item.field_A = 3;
item.field_B = 4;
```

The `downstream` may now see `field_A` as either 1 or 3 and see `field_B` as either 2 or 4, independent of each other.

**Comment by NikGovorov** [comment]
@akarnokd, thanks for answering my question. 

Just to conclude:

> The source of Buffer should provide the OnNext calls in a non-concurrent, non-overlapping manner as required by the observable protocol. 

Use ```Synchronize``` extension method if you want to call ```Observer``` methods in concurrent manner.

I wrote a simple test:
```C#
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reactive;
using System.Reactive.Linq;
using System.Reactive.Subjects;
using System.Threading;
using System.Threading.Tasks;
using NUnit.Framework;

// ReSharper disable CommentTypo

namespace RxNetConcurrentOnNext
{
    [TestFixture]
    public class RxNetConcurrentOnNextFixture
    {
        public event EventHandler Notified = (sender, args) => { };

        [Test]
        public void Demonstrate()
        {
            var signal = new AutoResetEvent(false);

            var subject = new Subject<Unit>(); // not safe

            var observable = subject;

            // var observable = subject.Synchronize(); // safe

            // var observable = Observable.FromEventPattern(handler => Notified += handler, handler => Notified -= handler); // not safe

            // observable = observable.Synchronize(); safe

            observable.Buffer(10000).Subscribe(x => signal.Set());

            Enumerable.Range(1, 4).ForEach(x => Task.Run(() => Enumerable.Range(1, 2500).ForEach(y => subject.OnNext(Unit.Default))));

            // Enumerable.Range(1, 4).ForEach(x => Task.Run(() => Enumerable.Range(1, 2500).ForEach(y => Notified(null, null))));

            // Enumerable.Range(1, 4).ForEach(x => Enumerable.Range(1, 2500).ForEach(y => subject.OnNext(Unit.Default))); // works, sequential

            signal.WaitOne();
        }
    }

    public static class EnumerableExtensions
    {
        public static void ForEach<T>(this IEnumerable<T> self, Action<T> action)
        {
            foreach (var item in self) action(item);
        }
    }
}
````
