### ISSUE TITLE
Race condition in SkipUntil(..)

### ISSUE THREAD

**Issue by cptjazz** [dotnet/reactive#327]
There seems to be a race condition when using the `SkipUntil(IObservable<T> other)` method with `source` observables that produce values immediately on subscribe, _even_ if the `other` observable also produces immediately. 
The first emitted item of `source` gets lost:

```
var source = Observable.Return(5);
var trigger = Observable.Return(Unit.Default);

var result = source.SkipUntil(trigger);
result.Subscribe(
        x => Console.WriteLine($"result = {x}"),
        () => Console.WriteLine("result completed"));
```

The expectation would be that we print out `result = 5` because the `trigger` observable should never skip items of the original `source`.
However, nothing is printed out.

IMHO  the problem is the order of subscriptions in the implementation of `SkipUntil`, because we already consume from the `source` and skip items until we realise that the `other` observable would already have had an item for us:

https://github.com/Reactive-Extensions/Rx.NET/blob/371c83c621562a2259580a03f0cb5bf8680ea720/Rx.NET/Source/System.Reactive.Linq/Reactive/Linq/Observable/SkipUntil.cs
```
46:    var sourceSubscription = _parent._source.SubscribeSafe(sourceObserver);
47:    var otherSubscription = _parent._other.SubscribeSafe(otherObserver);
```
But this is only a first guess from reading the source;

The documentation on `SkipUntil(..)` is not very precise on this very situation, but I think losing items when the `other` sequence is already "completed" (in this context: an item on `OnNext()` is already available) is not an option.

This behaviour happens in both the 2.x and 3.x versions of Rx (tested with 2.2.5 and 3.1.1).

**Comment by akarnokd** [comment]
The ordering of subscription is somewhat unfortunate, but you can swap it by introducing a subject as an indirection: https://github.com/dotnet/reactive/issues/469#issuecomment-388355451

**Comment by akarnokd** [comment]
The 4.0.0 release has changed the order to be other -> main. This can be closed.
