### ISSUE TITLE
RFE: EnumerableEx.Do overload that takes an onStart parameter

### ISSUE THREAD

**Issue by fsateler** [dotnet/reactive#330]
Originally posted in https://github.com/morelinq/MoreLINQ/issues/253 , but there is already the `Do` method here, so maybe it makes sense to add that here instead.

The proposal is to add a `Do` overload with the following signature:

```csharp
public static IEnumerable<T> Do<T, TState>(this IEnumerable<T> source,
    Func<TState> onStart,
    Action<TState, T> onNext,
    Action<TState> onCompleted,
    Action<TState, Exception> onError);
```

The idea being that a state is generated when the sequence is first enumerated, and that state is passed to the `onNext`, `onCompleted` and `onError` callbacks. My particular use case is to do the same as in:

```csharp
using (CreateADisposable()) {
    foreach(var item in src) {
        yield return item;
    }
}
```

This use case becomes easily done with Ix if the `onStart` parameter is added:

```csharp
src.Do(CreateADisposable, (_,__) => {}, d => d.Dispose(), (_,__) => {});
```

A wrapper that simply omits the unused parameters (as specific to the use case) is easily done locally.

If you think this would be an interesting addition, I can post a PR adding the overload.

**Comment by fsateler** [comment]
On second thought, I think it best if the callback signatures also have `T` as first argument, so that it more closely matches the already existing overloads.

**Comment by bartdesmet** [comment]
While some `onSubscribe` callback may make sense, it begs for a companion `onDispose`. It seems you can already achieve these behaviors using `Observable.Defer` and `Observable.Finally`, composing them with `Observable.Do`. In addition, `Observable.Using` can be used to achieve the behavior described in your example for disposal of some resource.
