### ISSUE TITLE
There is no information on how to build the Rx.NET sources.

### ISSUE THREAD

**Issue by npolyak** [dotnet/reactive#336]
clicking on "Building, testing and debugging the sources" link takes me to an empty page.

**Comment by colombod** [comment]
same, and I can't get it to build with visual studio 2017, the only one I have installed on the development machine.

**Comment by JimSEOW** [comment]
I have to install visual studio 2017 and yet it is buggy. 
The project samples I am interested is using System.Reactive pre-release 4.0, 
Please put that 4.0 version to Nuget so we can avoid the building of the develop branch

**Comment by onovotny** [comment]
The 4.0 alpha builds are on MyGet already, just add this feed to your local nuget.config: `https://dotnet.myget.org/F/rx/api/v3/index.json`

**Comment by bartdesmet** [comment]
We should have all packages available now, and building from source looks pretty straightforward now as well. Closing this issue.
