### ISSUE TITLE
Reduce object layout size of producers

### ISSUE THREAD

**Issue by bartdesmet** [dotnet/reactive#366]
Some producers (implementing `IObservable<T>`) such as `SelectMany` have a ton of fields to accommodate for the different overloads of the operator. Upon subscribing, the sink gets a reference to the producer, thus keeping a big object alive. We should consider increasing the granularity of producers to reduce object layouts.

**Comment by akarnokd** [comment]
`SelectMany` appears to be split up nicely, `Merge` is okay, `Window` is okay. I'd think this happened [not long after this issue](https://github.com/dotnet/reactive/commits/master/Rx.NET/Source/src/System.Reactive/Linq/Observable/SelectMany.cs).

**Comment by akarnokd** [comment]
Probably no longer relevant.
