### ISSUE TITLE
Consider using ThreadLocal<T> in CurrentThread scheduler

### ISSUE THREAD

**Issue by bartdesmet** [dotnet/reactive#370]
In lieu of `ThreadStatic`, potentially improving performance.

**Comment by akarnokd** [comment]
I wonder what performance benefits you think of. Based on [this](https://stackoverflow.com/a/18337158/61158) and the current implementation, changing to `ThreadLocal` has no practical benefit as the content queue will set and cleared over and over, so the auto-init benefit of the `ThreadLocal` is irrelevant.

I can see, however the reduction of some indirection, for example, if `ScheduledItem` implemented `IDisposable` there would be no need to wrap it.

**Comment by akarnokd** [comment]
Closing due to likely not worth it after the changes to 4.x
