### ISSUE TITLE
Async unfold?

### ISSUE THREAD

**Issue by mausch** [dotnet/reactive#399]
Hi,

The only unfold-like method I've found in System.Interactive.Async is `AsyncEnumerable.Generate`, which doesn't take any async functions.
So I looked at its source code and it seemed easy enough to write a class similar to [GenerateAsyncIterator](https://github.com/Reactive-Extensions/Rx.NET/blob/master/Ix.NET/Source/System.Interactive.Async/Generate.cs#L26) but with an async iterator func. 
However `AsyncIterator` is internal, so it seems I shouldn't write my own iterators after all? How should I go about this (barring the obvious brute force of copying and pasting the AsyncIterator code into my own codebase)?

Thanks

**Comment by onovotny** [comment]
Right now none of the Ix methods take async parameters. There are several open issues on this, #144, #168, #194, # 280. This will be added eventually, but we're also looking at the C# async streams features to see how the design relates.

**Comment by BenjaminHolland** [comment]
> Right now none of the Ix methods take async parameters. There are several open issues on this, #144, #168, #194, #280. This will be added eventually, but we're also looking at the C# async streams features to see how the design relates.

Could you please point to these "C# async streams features"? I haven't been able to find them.

**Comment by onovotny** [comment]
Hi @BenjaminHolland, there are two threads. The really long original one here: https://github.com/dotnet/roslyn/issues/261 that was then closed/moved over to here: https://github.com/dotnet/csharplang/issues/43

**Comment by danielcweber** [comment]
Closing this for now, defering to C# 8.

**Comment by mausch** [comment]
FWIW if anyone happens to land on this issue: I gave up trying to use Ix.NET long ago and switched to https://github.com/Dasync/AsyncEnumerable where it is trivial to write an async unfold.
