### ISSUE TITLE
The "How to contribute" link in README.md is dead

### ISSUE THREAD

**Issue by jonstodle** [dotnet/reactive#407]
The "How to contribute" link points to https://github.com/Reactive-Extensions/Rx.NET/wiki/Contributing-Code, which doesn't point to an actual page in the wiki. It just shows the interface for creating a new page.

Not sure where it's supposed to point, so not able to PR it.

**Comment by shiftkey** [comment]
> Not sure where it's supposed to point, so not able to PR it.

Looking at the wiki history, the `Contributing Code` page never existed there 🤔 . Guess we need to write one ourselves...

**Comment by akarnokd** [comment]
Posted an issue containing the proposed contents: #1108

Unfortunately, one can't PR a wiki so the most flexible way is to iterate the text in an issue, then create the Wiki page once ready.

**Comment by akarnokd** [comment]
The page has been created. https://github.com/dotnet/reactive/wiki/Contributing-Code
