### ISSUE TITLE
Observable.OnErrorResumeNext not propagating exception

### ISSUE THREAD

**Issue by alek5k** [dotnet/reactive#412]
When using OnErrorResumeNext, I expect that if it concatenates a stream that throws an error, that the error will be propagated downstream. This is not occurring. Please see code sample below:

```
Observable
      .Throw<int>(new Exception("Causing Error"))
      .OnErrorResumeNext(Observable.Throw<int>(new Exception("Continuing With Error")))
      .Subscribe(x =>
      {
            Console.WriteLine("onnext");
      },
      e =>
      {
            Console.WriteLine($"onerror: {e}");
      },
      () =>
      {
            Console.WriteLine("oncomplete");
      });
```

The output when I run this is "oncomplete", however I would have expected it to output "onerror".

**Comment by RxDave** [comment]
I agree, this seems like a bug.

If you continue with `Observable.Return(123)`, then OnNext(123) is called, followed by OnCompleted. But if you continue with `Observable.Return(1).Concat(Observable.Throw<int>(new Exception("Continuation Error")))`, then it's the same result: OnNext(123), OnCompleted. I would've expected to see OnNext(123) followed by OnError.

Note that introducing concurrency doesn't workaround the issue either; e.g., `Observable.Return(1).Delay(TimeSpan.FromSeconds(0.1)).Concat(Observable.Throw<int>(new Exception("Continuation Error")))`

**Comment by jc211** [comment]
Please check .Catch as well for potentially similar problem.

**Comment by alek5k** [comment]
@jc211 Observable.Catch seems to propagate the error correctly
