### ISSUE TITLE
Scheduler.CurrentThread is confusing

### ISSUE THREAD

**Issue by wavebit** [dotnet/reactive#417]
Hello,
I am new ot Rx.NET, I thought ObserveOn(Scheduler.CurrentThread) can block the caller thread, but the result is not.  How to onserve on(block) the caller thread?

        public static void Main(string[] args)
        {
            Console.WriteLine("Caller " + Thread.CurrentThread.ManagedThreadId);
            var o = Observable.Interval(TimeSpan.FromSeconds(1)).Take(3);
            o.ObserveOn(Scheduler.CurrentThread).Subscribe(l =>
            {
                Console.WriteLine("Current " + Thread.CurrentThread.ManagedThreadId);
            });
            Console.WriteLine("Press any key to exit...");
            Console.ReadKey();
        }

Output:
Caller 1
Press any key to exit...
Current 4
Current 4
Current 4

**Comment by akarnokd** [comment]
You'd need a blocking scheduler or a blocking subscribe method, neither is currently provided by Rx.NET. I've been recently writing up some operators for potential 4.x inclusion where there is a [`BlockingSubscribe`](https://github.com/akarnokd/reactive-extensions#blockingsubscribe) that will block the caller thread and execute the observer/delegates there.

**Comment by Deni35** [comment]
Has anything changed since then? 
I saw ObserveOnDispatcher method, but looks like System.Reactive.Windows.Threading.dll doesn't work with .net core. I didn't manage to use it.

**Comment by onovotny** [comment]
You should be able to use the preview System.Reactive package with the dispatcher overloads on .NET Core 3 on Windows. Note that those won't be in any stable packages for some time as .NET Core 3 is still in preview.

**Comment by Deni35** [comment]
Sorry, I do not understand. What should I use in preview version to observe on my current thread?
