### ISSUE TITLE
Add Prepend and Append to Rx

### ISSUE THREAD

**Issue by bartdesmet** [dotnet/reactive#420]
To be on par with LINQ to Objects, we should add these.

**Comment by mattpodwysocki** [comment]
@bartdesmet let's go even further to rename `StartWith` to `Prepend`, deprecating `StartWith`

**Comment by onovotny** [comment]
Moving to vNext so we can get 4.0 out as per our discussion.

**Comment by quinmars** [comment]
Is this up for grabs? This looks like a nice task to get hands on.

**Comment by akarnokd** [comment]
@quinmars I'd think you can start working on this. Perhaps put it into the `System.Reactive.Observable.Aliases.QueryLanguage` so that you can have fun with its `Qbservable` generated counterpart :)

**Comment by quinmars** [comment]
Remains the question if we should choose the n-ary approach or not. Personally I'd would prefer to exactly mirror the `IEnumerable`/`IQueryable` counter parts (not variadic) and keep `StartsWith()` as it is. Once/if the corefx team decides to add an [`AppendMany()` or `PrependMany()`](https://github.com/dotnet/corefx/issues/14119) we can consider to replace `StartsWith()` with `PrependMany()`.

**Comment by quinmars** [comment]
Since #567 is merged, I think that issue can be closed.
