### ISSUE TITLE
Deprecate StartWith in favor of Prepend for Ix

### ISSUE THREAD

**Issue by mattpodwysocki** [dotnet/reactive#427]
Since there is likely to be confusion over `StartWith` and `Prepend` for Ix, let's standardize on the LINQ standards.  However, there is an issue that `StartWith` is supports n-ary parameters, whereas `Prepend` does not.  Let's standardize by adding `Prepend` with n-ary.  See #426

**Comment by bartdesmet** [comment]
`System.Linq.Async` has all operators from `System.Linq` now, including those. Ix can retain `StartWith` as the dual image of Rx's operator set.
