### ISSUE TITLE
Consider more Ix-Async operators that leverage concurrency

### ISSUE THREAD

**Issue by bartdesmet** [dotnet/reactive#429]
The "ambient" concurrency exposed through the `Task<bool>`-based return value of `MoveNextAsync` can be leveraged to build some new operators that don't apply to the synchronous `IEnumerable<T>` world.

Examples include:

* `Zip` already uses `Task.WhenAll` to await both enumerators.
* `Amb` a la Rx could leverage `Task.WhenAny` to pick the first enumerator as the winner.
* `Merge` operators could concurrently await any sequence being merged to yield a value.
* `Timeout` using `Task.WhenAny(moveNext, Task.Delay(timeout))` for `MoveNextAsync`.

These are just some ideas that could apply to `System.Interactive.Async`.

**Comment by mattpodwysocki** [comment]
@bartdesmet +1 to this, as IxJS already supports `Amb` via [`AsyncIterable.race`](https://github.com/ReactiveX/IxJS/blob/master/src/asynciterable/race.ts) which is akin to `Promise.race` to determine which responds quicker.  Merge would be an interesting one.  Would we support a single merge or n-ary merges?

**Comment by akarnokd** [comment]
I think these enhancements have been applied.
