### ISSUE TITLE
Possible issue with reflection

### ISSUE THREAD

**Issue by risogolo** [dotnet/reactive#431]
I'm using an interface ITelemetry in ReplaySubject like:
`private ReplaySubject<ITelemetry> _subject = new ReplaySubject<ITelemetry>(TimeSpan.FromMinutes(1));`

then in onNext(x) method I'm looking for that type in properties of different object (this object always contains type `IEnumerable<x> List, `
search clause:`var property = GetType().GetRuntimeProperties().FirstOrDefault(p => p.PropertyType == typeof(T) || p.PropertyType == typeof(IEnumerable<T>));` but this is not possible due to issue "The metadata for '9eaae28c287f4ad48ef4567f8ca67942' is invalid. If you are debugging a minidump, you may be able to fix this problem by collecting a new minidump with heap and evaluating the expression again.	System.Reflection.PropertyInfo" so workaround is to cast using "as operator", but then I'm tied to concrete type which I don't like. 
BTW: that message is message from VS, in runtime variable called property is evaluated as null which is basically that issue.

**Comment by bartdesmet** [comment]
This seems unrelated to Rx, which doesn't touch reflection. If it repros consistently, can you try to isolate your reflection code to get a minimal repro?

**Comment by risogolo** [comment]
Please take a look [rx.net issue](https://github.com/risogolo/rxnetissue), please see comments in the code. Also I'd like to mention that the name of the issue maybe wrong, but did not know how to name it.

**Comment by risogolo** [comment]
Nobody interesting to help here?

**Comment by danielcweber** [comment]
@risogolo The repro-app fails with a completely unrelated error. Can you confirm the issue with the latest preview of Rx 4.0 ?

**Comment by danielcweber** [comment]
Closing due to age, complexity of repro app and no answer.
