### ISSUE TITLE
Allow subscription to methods that have no parameter

### ISSUE THREAD

**Issue by xxMUROxx** [dotnet/reactive#433]
Sometimes I have the case that I do not need the information about the item in `IObservable<T>`. This e.g. is the case in following code:

     Observable.Interval(TimeSpan.FromSeconds(2)).Subscribe(_ => OnTimerTick());

I this case I omit the `long`-object produced by `Observable.Interval`. What I do not like is to write a custom subscription method `_=> MethodWithoutParameters()` every time.

With 057c09cec4aa82621b4f495ebb83125a04b2bdf9 following line is possible:

     Observable.Interval(TimeSpan.FromSeconds(2)).Subscribe(OnTimerTick);

Apart from this commit: is there a built in solution that allows the same behavior already present?
If not, what do you think of integrating this commit in Rx.NET?

**Comment by bartdesmet** [comment]
This would be ambiguous with a `Subscribe` method taking in a delegate-based `onCompleted` callback, and it'd also be ambiguous whether this callback is a "forget the exception passed to `OnError`" shortcut. I'd rather keep the delegate signatures for `on*` callbacks isomorphic to the `IObserver<T>.On*` methods; all three are different, allowing one to infer meaning of callbacks from their type:

* `Action<T>` for `OnNext(T)`
* `Action<Exception>` for `OnError(Exception)`
* `Action` for `OnCompleted()`
