### ISSUE TITLE
provide a method in IX allowing batching

### ISSUE THREAD

**Issue by SeanFarrow** [dotnet/reactive#438]
It would be nice if within IX we had a BatchAsync method that takes a size in and batches an IAsyncEnumerable sequence in to sized buckets.

I don't think I can do this with the current Create methods as I need to store state and the AnonymousAsyncEnumerable and the AnonymousAsyncIterator are both private.

Any help apreciated.
Cheers
Sean.

**Comment by quinmars** [comment]
Are you looking for the [Buffer](https://github.com/Reactive-Extensions/Rx.NET/blob/develop/Ix.NET/Source/System.Interactive.Async/Buffer.cs) method?

```csharp
    IAsyncEnumerable<IList<TSource>> Buffer<TSource>(this IAsyncEnumerable<TSource> source, int count)
```

**Comment by SeanFarrow** [comment]
Hi,

Yes, it looks like that will do what I want.
Thanks, feel free to close this.

**Comment by jzabroski** [comment]
Please close this.  @SeanFarrow even said it can be closed.
