### ISSUE TITLE
TestableObservable's messages has count without any observers

### ISSUE THREAD

**Issue by aateeque** [dotnet/reactive#439]
The following test fails:

```C#
[Test]
public void Should_Not_Emit__Unless_Subscribed_To()
{
   var testScheduler = new TestScheduler();
   var sequence = testScheduler.CreateColdObservable(OnNext(5, 1));
   
   sequence.Messages.Should().HaveCount(0, "as there is no subscription");
 }
```

One would expect it to pass as there isn't a subscription created to the Cold observable. The intellisense doc suggests that its notifications sent to observers, but we don't have any observers in this instance.

**Comment by akarnokd** [comment]
I'd think the documentation is either outdated or worder incorrectly as both [hot](https://github.com/dotnet/reactive/blob/d6d954f08a0a38b95ece899834b8f03f0a352f55/Rx.NET/Source/src/Microsoft.Reactive.Testing/HotObservable.cs#L65) and [cold](https://github.com/dotnet/reactive/blob/master/Rx.NET/Source/src/Microsoft.Reactive.Testing/ColdObservable.cs#L57) implementations simply returns the array of notifications you used in the create method.

`sequence.Subscriptions` however is properly zero length in your case.

**Comment by danielcweber** [comment]
@akarnokd is right. Closing.
