### ISSUE TITLE
CoreDispatcherScheduler does not work in UWP Single Process Model Background Activation

### ISSUE THREAD

**Issue by rozele** [dotnet/reactive#441]
The CoreDispatcherScheduler relies on DispatcherTimer for its implementation. DispatcherTimer only works when the app is running in the foreground with an activated main CoreApplicationView CoreWindow.

Repro steps:
1) In a UWP app, override OnBackgroundActivated in App.xaml.cs:
```
        protected override void OnBackgroundActivated(BackgroundActivatedEventArgs args)
        {
            base.OnBackgroundActivated(args);
            Debug.WriteLine($"[App] Background started");
            var deferral = args.TaskInstance.GetDeferral();
            var sas = new SingleAssignmentDisposable();
            sas.Disposable = Observable.Timer(
                    DateTimeOffset.Now,
                    TimeSpan.FromTicks(166666),
                    new CoreDispatcherScheduler(CoreApplication.MainView.Dispatcher))
                .Subscribe(tick =>
                {
                    Debug.WriteLine($"[App] Tick {tick}");
                    if (tick == 10)
                    {
                        sas.Dispose();
                        deferral.Complete();
                    }
                });
        }
```
2) Register the app to trigger a background activation off some system activity (e.g., time zone change):
```
            var requestTask = await BackgroundExecutionManager.RequestAccessAsync().AsTask().ConfigureAwait(false);
            var builder = new BackgroundTaskBuilder();
            builder.Name = "Registration";
            var trigger = new SystemTrigger(SystemTriggerType.TimeZoneChange, false);
            builder.SetTrigger(trigger);
            builder.Register();
```
3) Run the app, register the background task, then close the app
4) Perform the system activity to trigger the background task (e.g., change time zone)

The result is that only the first Timer tick will fire, you can track the activity using DebugView.

**Comment by akarnokd** [comment]
Is this still an issue?

**Comment by rozele** [comment]
It can probably be closed, I don't know if it's still an issue, but it's not a priority bug for the project I was working on anymore.

**Comment by akarnokd** [comment]
Thanks @rozele for the confirmation.
