### ISSUE TITLE
System.ArgumentException : Cannot bind to the target method because its signature or security transparency is not compatible with that of the delegate type.

### ISSUE THREAD

**Issue by Odonno** [dotnet/reactive#447]
I got this exception when subscribing to an observable : `Cannot bind to the target method because its signature or security transparency is not compatible with that of the delegate type.`

Here is the sample code : 

```
var dataGridCopy = Observable.Merge(dataGridKeyDown, dataGridKeyUp)
    .Buffer(2, 1)
    .Where(x => !x[0].EventArgs.KeyStatus.IsKeyReleased && !x[1].EventArgs.KeyStatus.IsKeyReleased)
    .Where(x => x[0].EventArgs.VirtualKey == VirtualKey.Control && x[1].EventArgs.VirtualKey == VirtualKey.C);

dataGridCopy.Subscribe(_ =>
    {
        // TODO
    });
```

I am working on a UWP application under Windows 10 Fall Creators Update with the package System.Reactive 3.1.1.

**Comment by shiftkey** [comment]
@Odonno are you able to provide a more complete example? It's not clear where `dataGridKeyDown` and `dataGridKeyUp` are coming from, and this is a common error on StackOverflow around creating certain kinds of delegates

**Comment by Odonno** [comment]
Of course. Hope it helps.

[ReproBug447.zip](https://github.com/Reactive-Extensions/Rx.NET/files/1501213/ReproBug447.zip)

**Comment by chrisevans9629** [comment]
What was the solution for this?  I'm having this issue as well.

**Comment by Odonno** [comment]
@chrisevans9629 Well, rxjs with electron was the final solution. :)

But seriously, still don't know why..

**Comment by chrisevans9629** [comment]
For me, this happened when using Observable.FromEvent<>(); in Rx.NET
However, it worked fine after I switched to Observable.FromEventPattern<>():

Don't know why, but it did the trick!
