### ISSUE TITLE
ToTask should dispose of the subscription immediately on completion or error

### ISSUE THREAD

**Issue by Lukazoid** [dotnet/reactive#456]
Currently [TaskObservableExtensions.ToTask<TResult>(IObservable<TResult>)](https://github.com/Reactive-Extensions/Rx.NET/blob/0a03db0bee3d80656accff16229a6cd152d82d18/Rx.NET/Source/src/System.Reactive/Threading/Tasks/TaskObservableExtensions.cs#L360) completes or sets the exception on the resulting `Task` before disposing of the subscription, this can be seen [here](https://github.com/Reactive-Extensions/Rx.NET/blob/0a03db0bee3d80656accff16229a6cd152d82d18/Rx.NET/Source/src/System.Reactive/Threading/Tasks/TaskObservableExtensions.cs#L317-L323) and [here](https://github.com/Reactive-Extensions/Rx.NET/blob/0a03db0bee3d80656accff16229a6cd152d82d18/Rx.NET/Source/src/System.Reactive/Threading/Tasks/TaskObservableExtensions.cs#L325-L338).

As `TaskCompletionSource.TrySetResult` and `TrySetException` will often run the task continuations it may not unsubscribe until the next await, this could be disastrous when the original subscription uses any resources which the task continuation will need exclusive access to, for example:

```cs
    async Task Main()
    {
        var filePath = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.Desktop), "ToTaskTest.txt");
    
        var secondLine = await WhenLinesReadFromFile(filePath).Skip(1).FirstOrDefaultAsync().ToTask().ConfigureAwait(false);
        if (secondLine == "DELETE ME")
        {
            File.Delete(filePath);
        }
    }
    
    IObservable<string> WhenLinesReadFromFile(string filePath)
    {
        return Observable.Create<string>(async (obs, ct) =>
        {
            var file = File.OpenText(filePath);
            string line;
            while ((line = await file.ReadLineAsync().ConfigureAwait(false)) != null)
            {
                ct.ThrowIfCancellationRequested();
                
                obs.OnNext(line);
            }
            
            return file;
        });
    }
```

As `WhenLinesReadFromFile` only releases the file handle on unsubscribe the above code will attempt to delete the file while the handle is still open.

I propose that the `_disposable.Dispose();` be moved before the `_tcs.TrySetResult` and `_tcs.TrySetException` calls, there's probably no harm in moving the `_ctr.Dispose()` earlier too (as we know there is already a result/exception). This would ensure that the continuation is only run once the subscription has been disposed.

**Comment by danielcweber** [comment]
@akarnokd Sounds very reasonable, any thoughts?

**Comment by akarnokd** [comment]
It depends, both paths are equally reasonable. For example, the resource is shared deliberately and the continuation still needs it for a bit longer. For this reason, RxJava has an `eager` parameter on the `using()` operator to dispose a resource.

**Comment by akarnokd** [comment]
For reference, [Reactive4.NET](https://github.com/akarnokd/Reactive4.NET/blob/master/Reactive4.NET/subscribers/TaskFirstSubscriber.cs#L68) disposes before setting the cancelled state.

**Comment by Lukazoid** [comment]
@akarnokd When `eager` is set to `true` does the resource get disposed before the final `OnCompleted`/`OnError` call?

**Comment by danielcweber** [comment]
So, will we change this behaviour? Maybe in a next major version?

**Comment by bartdesmet** [comment]
Given that both behaviors are valid, as pointed out higher up, it doesn't matter whether or not

> the current behavior is captured by unit tests or not

People *will* rely on the current behavior, whether they know it or not, and we shouldn't be changing the order of side effects without forcing an explicit opt-in. As such, a flag to opt in to alternative behavior (with the default for the flag being the original behavior) seems like the most desirable way forward.
