### ISSUE TITLE
TestScheduler and Repeat

### ISSUE THREAD

**Issue by apobekiaris** [dotnet/reactive#462]
Hi

for this snippet 

	var testScheduler = new TestScheduler();
	var numbers = testScheduler.CreateColdObservable(OnNext(10,1),OnNext(20,2),OnNext(30,3));
	var strings = testScheduler.CreateColdObservable(OnNext(1,"a"));
	numbers.Zip(strings.Repeat(4), (i, s) => (i, s)).Subscribe(tuple => WriteLine($"{tuple.i}-{tuple.s}"));

	testScheduler.AdvanceBy(100);

I get as output 

>   0-a

while when using the Scheduler.Default the output is 

>   0-a
>   1-a
>   2-a

have I discover a bug or I miss something?

**Comment by akarnokd** [comment]
The problem with your code is that `Repeat` requires a finite source and yours doesn't complete and thus `Repeat` doesn't come into play. It prints one item `1-a` and then stops emitting.

If you add `OnCompleted(2, "")` for example, you'll get 3 lines printed:

```cs
var testScheduler = new TestScheduler();
var numbers = testScheduler.CreateColdObservable(OnNext(10, 1), OnNext(20, 2), OnNext(30, 3));
var strings = testScheduler.CreateColdObservable(OnNext(1, "a"), OnCompleted(2, ""));
numbers.Zip(strings.Repeat(4), (i, s) => (i, s)).Subscribe(tuple => 
    WriteLine($"{tuple.i}-{tuple.s}"));

testScheduler.AdvanceBy(100);
```

```
1-a
2-a
3-a
```
