### ISSUE TITLE
Prepare 4.0 for release

### ISSUE THREAD

**Issue by onovotny** [dotnet/reactive#468]
- [x] UWP metapackage
- [x] NuGet signing?
- [x] NuGet dependency versions
- [x] Remove stale workarounds that are no longer needed
- [x] MSBuild Sdk Extras to SDK with global.json config
- [x] Complete #418

**Comment by godrose** [comment]
@onovotny Any ETA for this release? Any help needed?

**Comment by onovotny** [comment]
"Final" preview 3 build is on NuGet.org now. Will release stable after a little baking.

**Comment by akarnokd** [comment]
Can be closed now.
