### ISSUE TITLE
Failure to load 3.1.1 assembly with reflection from .net core

### ISSUE THREAD

**Issue by jeffras** [dotnet/reactive#473]
This issue is related to the assembly versioning conflicts with 3.1.1

I recently wanted to consume a .net 4.5.1 assembly from aspnetcore. Leveraging the binding redirects allows the assembly to load and use the .net 4.5.1 code without issues. I have the need to leverage reflection to query and register types with a serializer. When loading the 4.5.1 assembly with reflection in the binding redirects seem to be ignored. The reflection code is clearly looking for the .net 4.5.1 assembly version of System.Reactive.Interfaces (3.0.1000.0) as opposed to the .net core version that has been specified in the binding redirect (3.0.0.0).

Are you aware of any way around this versioning conflict? Unfortunately this is a blocker for my team. I have not found any info online regarding binding redirects and reflection.

This is the small bit of reflection code that is causing the incompatibility in core.
`
var assembly = AppDomain.CurrentDomain.GetAssemblies();
var types = assembly.SelectMany(s => s.GetTypes());
var classes = types.Where(t => t.IsClass).ToList();
`

**Comment by onovotny** [comment]
Please try with Rx 4 and reopen if still an issue there.
