### ISSUE TITLE
Add approval tests to the public API surface 

### ISSUE THREAD

**Issue by ghuntley** [dotnet/reactive#479]
We need to make it more accessible and safer for folks to contribute to this project. I would love to do a performance pass but not before basics such as increasing test coverage happen.

So this is a help wanted? Can you help out? Will you.

Deliverables
* Add approval tests to the public API surface (see https://reactiveui.net/blog/2017/09/the-public-api-surface-of-reactiveui-is-now-protected-by-approval-tests)

**Comment by olevett** [comment]
Totally up for helping this along. Is targeting .Net 45/462 to start with, and expand to other platforms if we can make it work a sensible strategy?

**Comment by ghuntley** [comment]
Yup let's start with net471 to Rx/Ix and add other platforms as as seperate PRs as needed as we learn more by adding those platforms as integration tests to ReactiveUI.

**Comment by ryanwersal** [comment]
I'm currently digging into getting this added for the projects under the Rx.NET folder. I'm planning to carry on into the other folders (Ix.NET etc) once I get a PR in for the Rx.NET stuff but I'm happy to collaborate.

**Comment by ghuntley** [comment]
It's yours for next 72 hours.  Good luck. Olly can help if you need a partner. Just ask.

**Comment by danielcweber** [comment]
Fixed by #482
