### ISSUE TITLE
WithCache operator

### ISSUE THREAD

**Issue by Odonno** [dotnet/reactive#495]
For one of my application, I needed to cache response from API calls but no operator exist in rx.net.

Luckily, I found a tutorial (https://asizikov.github.io/2015/07/26/rx-api-with-cache-one/) so I added an extension and a service to cache data in a `Dictionary<string, object>`.

So, my proposition is to add a `WithCache` operator which look like this:

```csharp
public static IObservable<T> WithCache<T>(this IObservable<T> source, Func<T> get, Action<T> put) where T : class
{
    return Observable.Create<T>(observer =>
    {
        var cached = get();
        if (cached != null)
        {
            observer.OnNext(cached);
        }
        else
        {
            source.Subscribe(item =>
            {
                put(item);
                observer.OnNext(item);
            }, observer.OnError, observer.OnCompleted);
        }

        return Disposable.Empty;
    });
}
```

And using it like that:

```csharp
return Observable.Create<A>(async observer =>
{
    var result = await ExtractResponseFromGetRequestAsync<A>("https://myapi.com/a");
    observer.OnNext(result);
})
.WithCache(() => _cacheService.Get<A>("a"), r => _cacheService.Set("a", r));
```

In this version, the developer has to implement his own caching service (in-memory, local storage, or even Cloud storage). By default, I use an in-memory service using a `Dictionary<string, object>`, so I have another proposal for this operator so we can use it like that:

```csharp
return Observable.Create<A>(async observer =>
{
    var result = await ExtractResponseFromGetRequestAsync<A>("https://myapi.com/a");
    observer.OnNext(result);
})
.WithCache(r => r.Key); // Automatically get/set from in-memory storage with a key constructed with the result
```

**Comment by akarnokd** [comment]
A few comments: 

- The signature is quite an odd one compared to the existing Rx operators.
- If an item is cached, the `IObservable` will never complete.
- `T` is limited to classes.
- If the source has multiple items, only the last item will be available as cached.
- Multiple subscriptions running concurrently when there is nothing yet cached may overwrite each other's value.
- The API should require the `get` and `put` lambdas to be thread-safe and/or talk to a thread-safe container.
- The non-cached `source.Subscribe`'s returned `IDisposable` is ignored, making an ongoing flow non-cancellable.

**Comment by Odonno** [comment]
@akarnokd Thanks for the reply. I am not aware of the best practices on this repo for now. I used the example as-is and it works for me because my use case is simple. 1 API call = 1 Observable on a Page.

Maybe I can start with some Unit Tests to check that everything should work fine (no overwrite, no concurrency, etc..).

**Comment by glopesdev** [comment]
@Odonno your described behavior sounds very similar to the [Start](http://reactivex.io/documentation/operators/start.html) operator: this operator also caches the results of an arbitrary async function for future subscriptions. You can combine it with other observables very easily using `async`/`await` or [Defer](http://reactivex.io/documentation/operators/defer.html).

**Comment by bartdesmet** [comment]
Can this issue be closed? It seems an operator like this is very specific to justify inclusion in Rx.

In terms of feedback, I'd say you should always be wary of the following:

- Discarding an `IDisposable` in a no-no.
- `IObservable<T>` operators parameterized by shared state (e.g. the delegates) that will be used across multiple subscriptions.
