### ISSUE TITLE
Extensions for UI events

### ISSUE THREAD

**Issue by Odonno** [dotnet/reactive#496]
In order to create Observable on top of UI events, we need to do this:

```csharp
Observable.FromEventPattern<RoutedEventHandler, RoutedEventArgs>(
    h => IncrementButton.Click += h,
    h => IncrementButton.Click -= h
).Subscribe(…)
```

I think it is a lot of code for a simple action. My proposal is to write Extension methods so we can do this:

```csharp
IncrementButton.ObserveOnClick().Subscribe(…)
```

Here is an the extension method related:

```csharp
public static IObservable<EventPattern<RoutedEventArgs>> ObserveOnClick(this Button button)
{
    return Observable.FromEventPattern<RoutedEventHandler, RoutedEventArgs>(
        h => button.Click += h,
        h => button.Click -= h
    );
}
```

We need to write every Extension method for every event on any platform (UWP, WPF, WInForms, Xamarin, etc..). I think it's feasible but my questions are

1. Is there any existing library that does what I say? I did not find it but maybe it exists.
2. Should this library be in this repository?

**Comment by flagbug** [comment]
Sounds pretty much like the ReactiveUI.Events library from https://github.com/reactiveui/ReactiveUI, it does exactly that

**Comment by Odonno** [comment]
@flagbug Any example? I don't see how to do that with this library.

**Comment by TaviTruman** [comment]
Take look at ReactiveProperty as well; this technology plugs directly into XAML.

**Comment by Odonno** [comment]
Well, the thing is that I do not want to depend on `PropertyChanged` pattern. I want to listen to any kind of `Event` on any kind of `UIElement`.

It is basically syntactic sugar to turn the `Observable.FromEventPattern` into an Extension method based on the sender and the type of Event.

**Comment by benoitjadinon** [comment]
@Odonno see https://reactiveui.net/docs/handbook/events/ and [NuGet](https://www.nuget.org/packages/ReactiveUI.Events/)

**Comment by Odonno** [comment]
Thanks @benoitjadinon. Seems to work pretty fine.
