### ISSUE TITLE
Suggestion: AsObservablesWithPrecedence Operator

### ISSUE THREAD

**Issue by mattpodwysocki** [dotnet/reactive#50]
Copied from https://rx.codeplex.com/workitem/36

Implement an overloaded operator named AsObservablesWithPrecedence that accepts an ISubject<T> and yields a list of observables with the specified subscription precedence, indicating the expected order of observations among the hot observables for a given notification.

Example implementation: 
http://social.msdn.microsoft.com/Forums/en-US/rx/thread/a97a7e97-cb3d-4b42-afcb-8cb2c88c1778

Precedence is only guaranteed if all of the following are true: 
1. The `ISubject` implementation natively ensures subscription precedence.
2. The `ISubject`'s callers obey the Rx Grammar and serialize notifications; e.g., calls to OnNext never overlap.
3. Subscriptions to the `ISubject` are never made concurrently.  (Though subscriptions to the generated observables can be made concurrently.)

Related discussion: 
http://social.msdn.microsoft.com/Forums/en-US/rx/thread/ac721f91-4dbc-40b8-a2b2-19f00998239f

**Comment by akarnokd** [comment]
Looks like this refers to the `SkipUntil` subscription order that has been changed to other -> main. Otherwise the short issue description sounds too peculiar for Rx.NET or the OP needs to work with `Publish(Func)`.
