### ISSUE TITLE
Observable type that doesn't terminate on error

### ISSUE THREAD

**Issue by shyam-s00** [dotnet/reactive#547]
Proposal for adding a new Observable type that doesn't terminate the stream OnError, instead lets us action on the error and continue the same stream. 

Source: [Rex](https://github.com/DanHarman/KodeKandy/blob/master/Source/Core.Async/Rex.cs)

```
public static IDisposable SubscribeRex<T>(this IObservable<Rex<T>> source, Action<T> onNextResult, Action<Exception> onNextError, Action onCompleted)
        {
            return source.Subscribe(x =>
            {
                if (x.IsError)
                {
                    onNextError(x.Exception);
                }
                else
                {
                    try
                    {
                        onNextResult(x.Value);
                    }
                    catch (Exception ex)
                    {
                        onNextError(ex);
                    }
                }
            }, onNextError, onCompleted);
        }
```

**Comment by danielcweber** [comment]
Isn't that roughly the same as `Materialize` ?

**Comment by shyam-s00** [comment]
Almost. Yeah. Materialize calls OnCompleted if exists instead of terminating the sequence and it doesn't continue after the error. 

For instance a sequence of 10 values

> Materialize(): 

**1-2-3-4-[throws-exception]-completed**

> SubscribeRex():

**1-2-3-4-[throws-exception]-6-7-8-9-10-completed**

**Comment by danielcweber** [comment]
How is that a new 'type of observable'?

**Comment by danielcweber** [comment]
Are you proposind a new protocol for push-sequences (not gonna happen), a new interface that would work with a different protocol (don't see that either) or the above Subscribe-method? The latter would just work on `IObservable<Notification<T>>` pretty fine.

**Comment by akarnokd** [comment]
This has come up in lots of Rx libraries and there is no good reason to do it. It complicates and often ambiguates the flows and there is a workaround already. Use `Notification` but do not dematerialize or simply use a struct as your item type:

```cs
struct Signal<T> {
   public T item;
   public Exception error;
}
```

**Comment by shyam-s00** [comment]
Thanks!! Notification and its static methods helped me.
