### ISSUE TITLE
Set up common coding style guidelines.

### ISSUE THREAD

**Issue by danielcweber** [dotnet/reactive#573]
I would like to give the code a good review with ReSharper and align different coding styles throughout the code. Of course, ReSharper's suggestions might not sit well with all the community. So a quick request for comments:

Who is using ReSharper? Who is using something else? How are you handling this in your other repositories? What's currently done in the other dotnet-repos?

Note that you may apply for a free ReSharper license if you are an open source contributor.

**Comment by glopesdev** [comment]
Can you give some examples of what this refactoring would look like? Tbh, I prefer to review my coding styles manually, since it gives me yet another chance to think about the code.

**Comment by danielcweber** [comment]
No refactoring. I would just fix a lot of issues that ReSharper would find, like namings and stuff.

**Comment by danielcweber** [comment]
As part of dotnet, we should adhere to [this coding styles](https://github.com/dotnet/corefx/blob/master/Documentation/coding-guidelines/coding-style.md). They have also a .vssettings file, however, every contributor would have to import it into VS manually and it can't be used to highlight violations in the editor. As far as I can see, there is neither a Roslyn analyzer nor a ReSharper-settings file that enfored the coding style.

What can and should be done is running the codebase through [this formatter tool.](https://github.com/dotnet/codeformatter)
