### ISSUE TITLE
Create(async) Swallows Errors Thrown From OnError

### ISSUE THREAD

**Issue by RxDave** [dotnet/reactive#67]
Unlike typical observables in Rx, the async `Create` overload swallows exceptions that are thrown from within its observer's `OnError` handler.  This has allowed some bugs to almost get by me during development because they didn't crash my application as expected while testing.

Note that this may be related to work item #30, but I have a very simple test case: 

```
try
{
    Observable.Create<bool>(async (observer, cancel) =>
    {
        throw new Exception("Before or after await - it doesn't matter when this is thrown.");

        return Disposable.Empty;
    })
    .Subscribe(
        _ => { }, 
        ex => { throw new Exception(); }); // The default OnError behavior.

    Console.WriteLine("Shouldn't get here."); // This code executes every time.
}
catch (Exception)
{
    Console.WriteLine("Should get here.");  // This code never executes.
}
```

**Comment by shiftkey** [comment]
@RxDave do we still care about this? Are we able to recreate this in the latest release?

**Comment by RxDave** [comment]
@shiftkey Can't repro with my original example. Was it fixed?

**Comment by danielcweber** [comment]
>Was it fixed?

@shiftkey @RxDave So....was it?

**Comment by danielcweber** [comment]
Yes, your sample does no longer reproduce.

@onovotny Please close this, it has apparently been fixed.
