### ISSUE TITLE
Multiple subscriptions if using .Publish().RefCount() in 4.0.0

### ISSUE THREAD

**Issue by mlathan** [dotnet/reactive#768]
Hello guys I have a very strange behavior with using `.Publish().RefCount()` from `System.Reactive v4.0.0`. Please have a look at the following example program:
```
static class Program
{
    static void Main(string[] args)
    {
        var o1 = Observable.Create<string>(observer =>
        {
            Console.WriteLine("Observable.Create<string>()");

            observer.OnNext("A+");
            observer.OnNext("C+");
            observer.OnNext("B+");
            observer.OnNext("B-");
            observer.OnNext("A-");
            observer.OnCompleted();

            return Disposable.Empty;
        });

        var o2 = o1.Publish().RefCount(); // Variant A): Bad
        //var o2 = o1.Publish(); // Variant B): OK

        var s1 = o2.Subscribe(text => Console.WriteLine($"First:  {text}"));
        //var c1 = o2.Connect(); // Variant B): OK
        var s2 = o2.Subscribe(text => Console.WriteLine($"Second: {text}"));

        

        Console.WriteLine("Press any key to exit.");
        Console.ReadKey();

        s1.Dispose();
        s2.Dispose();
        //c1.Dispose(); // Variant B): OK
    }
}
```

Output Variant A):
```
Observable.Create<string>()
First:  A+
First:  C+
First:  B+
First:  B-
First:  A-
Observable.Create<string>()
Press any key to exit.
```

Output Variant B):
```
Observable.Create<string>()
First:  A+
First:  C+
First:  B+
First:  B-
First:  A-
Press any key to exit.
```
Based on the documentation I would expect that `Observable.Create<string>()` is only printed once on the console. Because `s1` subscribed to `o2`; so `s2` should additionally not also subscribe to the underlying observable.
Do I miss something?

However if I change the usage of `.Publish().RefCount()` into `.Publish()` and then `.Connect()`, `Observable.Create<string>()` will be only printed once like expected. Is this a bug in `.RefCount()`?

**Comment by danielcweber** [comment]
On the first subscription, `RefCount` will connect to `o1.Publish()` and then subscribe to it. `o1`, on the other hand, executes synchronously on the same thread that subscribed. It'll print out all the messages, then terminate. Upon termination, all subscriptions will be disposed, `RefCount` will notice that and disconnect.

On the second subscription, everything starts over.

What puzzles me though: are you sure there is no output for 'Second...' before 'Press any key to exit.' ?

**Comment by akarnokd** [comment]
The program prints `Observable.Create<string>()` twice with 3.1.1 and 4.0.0. With 4.1.0-preview.84 and above, it prints that only once. It seems odd to me why it doesn't resubscribe again in any of the versions.

The double printout tells me that the resubscription happens but something does not forward events to to observer 2.

**Comment by danielcweber** [comment]
@akarnokd Do you wanna take it? I could look at it tomorrow morning.

**Comment by akarnokd** [comment]
I can't do it until tomorrow 10am.

**Comment by danielcweber** [comment]
@onovotny How would I add David to the list of possible assignees? He doesn't show up.

**Comment by mlathan** [comment]
@akarnokd 

> It seems odd to me why it doesn't resubscribe and reemit again in any of the versions.

Based on documentation it shouldn't do that. A ref counted Observable counts the subscripions on it self, only the first Subscription will do a Subscription to the underlying sequence. All other subscribers which "come late to the party" will not have a subscribe to the underlying sequence as consequence.

I'm refering to [introtorx.com](http://introtorx.com/Content/v1.0.10621.0/14_HotAndColdObservables.html#HotAndCold), chapter **RefCount**.

**Comment by mlathan** [comment]
You are right. `OnComplete()` makes a difference in the example and leads to the expected behavior. However. The following text is an excerpt from the C# source code documention of `RefCount()`:

> Returns an observable sequence that **stays connected** to the source **as long as** there is **at least one subscription** to the observable sequence.

Neither `s1` nor `s2` unsubscribe. There should be no re-subscription for `s2` in any case.

**Comment by akarnokd** [comment]
Technically, a completion should trigger unsubscriptions but it doesn't happen with the lambda-observer. In fact, the underlying `AnonymousObserver` doesn't even know about the upstream `IDisposable` and can't even dispose. However, even if `s1.Dispose` is called right after `s1`'s subscription, it does reconnect but the items don't arrive again for `s2`.

**Comment by danielcweber** [comment]
@akarnokd It's because the RefCount-Sink is disposed twice, setting the internal counter to garbage. Will have a PR tomorrow.

**Comment by mlathan** [comment]
@akarnokd I gave it a second thought. Because my Observable completes, `s1` should get automatically unsubscribed so that `s2` does a resubscribe. So the correct behavior should be that a second time all the strings should be printed and not "eaten up" by the `.RefCount()`.

I think thats what you meant yesterday.

**Comment by danielcweber** [comment]
>Because my Observable completes, s1 should get automatically unsubscribed
Yes.
>but for s2 also all the strings should be printed
Actually no, the `Subject` that `Publish` creates is not recreated on a subsequent connect and will therefore remain completed.
