### ISSUE TITLE
distinctUntilChanged strange behavior with Join

### ISSUE THREAD

**Issue by mohamedhammad** [dotnet/reactive#791]
have anyone tried using distinctUntilChanged and then using join after it ?
it is not behaving properly.

**Comment by akarnokd** [comment]
How is it not working properly? Please provide more details and code that demonstrates your problem including the actual and expected behavior.

**Comment by mohamedhammad** [comment]
i should simplify the code to make it easier to follow,will do that and post it, thank you.

**Comment by danielcweber** [comment]
Closing until further details are provided.
