### ISSUE TITLE
crash log from appcenter

### ISSUE THREAD

**Issue by haohighview** [dotnet/reactive#792]
Xamarin android 
System.Reactive.Linq 4.0.0

Xamarin Exception Stack:
System.NullReferenceException: Object reference not set to an instance of an object
  at System.Reactive.Linq.ObservableImpl.Select`2+Selector+_[TSource,TResult].OnNext (TSource value) [0x00018] in <ec03606dbdef4b18bd643f9c974f8370>:0
  at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback () <0xe90ccd28 + 0x00033> in <3e3de383c41b4a159d61323508b3da7c>:0

Thread 2:
0   android.support.v7.widget.AppCompatTextHelper.<init>(AppCompatTextHelper.java:73)
1   android.support.v7.widget.AppCompatTextHelperV17.<init>(AppCompatTextHelperV17.java:33)
2   android.support.v7.widget.AppCompatTextHelper.create(AppCompatTextHelper.java:53)
3   android.support.v7.widget.AppCompatEditText.<init>(AppCompatEditText.java:69)
4   android.support.v7.widget.AppCompatEditText.<init>(AppCompatEditText.java:60)
5   android.support.v7.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:112)
6   android.support.v7.app.AppCompatDelegateImplV9.createView(AppCompatDelegateImplV9.java:1016)
7   android.support.v7.app.AppCompatDelegateImplV9.onCreateView(AppCompatDelegateImplV9.java:1073)
8   md5f47a70e27ea357f359ea83a171a8ed42.MvxLayoutInflaterCompat_FactoryWrapper2.n_onCreateView(MvxLayoutInflaterCompat_FactoryWrapper2.java:-2)
9   md5f47a70e27ea357f359ea83a171a8ed42.MvxLayoutInflaterCompat_FactoryWrapper2.onCreateView(MvxLayoutInflaterCompat_FactoryWrapper2.java:32)
10  android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java:189)
11  android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:772)
12  android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
13  android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
14  android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
15  android.view.LayoutInflater.rInflate(LayoutInflater.java:866)
16  android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
17  android.view.LayoutInflater.rInflate(LayoutInflater.java:866)
18  android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
19  android.view.LayoutInflater.inflate(LayoutInflater.java:515)
20  android.view.LayoutInflater.inflate(LayoutInflater.java:423)
21  md55a34d93fdf7e4072c85a7bf6e183fdad.DockChatFragment.n_onCreateView(DockChatFragment.java:-2)
22  md55a34d93fdf7e4072c85a7bf6e183fdad.DockChatFragment.onCreateView(DockChatFragment.java:32)
23  android.support.v4.app.Fragment.performCreateView(Fragment.java:2261)
24  android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1419)
25  android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1750)
26  android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1819)
27  android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797)
28  android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2590)
29  android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2377)
30  android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2332)
31  android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2239)
32  android.support.v4.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:781)
33  md5c2e00ffd157e70fa15d48ef95f58f11c.LazyMvxFragmentPagerAdapter.n_finishUpdate(LazyMvxFragmentPagerAdapter.java:-2)
34  md5c2e00ffd157e70fa15d48ef95f58f11c.LazyMvxFragmentPagerAdapter.finishUpdate(LazyMvxFragmentPagerAdapter.java:57)
35  android.support.v4.view.ViewPager.populate(ViewPager.java:1238)
36  android.support.v4.view.ViewPager.populate(ViewPager.java:1086)
37  android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1616)
38  android.view.View.measure(View.java:23279)
39  android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:715)
40  android.widget.RelativeLayout.onMeasure(RelativeLayout.java:461)
41  android.view.View.measure(View.java:23279)
42  android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6928)
43  android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
44  android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:139)
45  android.view.View.measure(View.java:23279)
46  android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6928)
47  android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1514)
48  android.widget.LinearLayout.measureVertical(LinearLayout.java:806)
49  android.widget.LinearLayout.onMeasure(LinearLayout.java:685)
50  android.view.View.measure(View.java:23279)
51  android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6928)
52  android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
53  android.view.View.measure(View.java:23279)
54  android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6928)
55  android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1514)
56  android.widget.LinearLayout.measureVertical(LinearLayout.java:806)
57  android.widget.LinearLayout.onMeasure(LinearLayout.java:685)
58  android.view.View.measure(View.java:23279)
59  android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6928)
60  android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
61  com.android.internal.policy.DecorView.onMeasure(DecorView.java:898)
62  android.view.View.measure(View.java:23279)
63  android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2836)
64  android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1873)
65  android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2128)
66  android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1742)
67  android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7763)
68  android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
69  android.view.Choreographer.doCallbacks(Choreographer.java:723)
70  android.view.Choreographer.doFrame(Choreographer.java:658)
71  android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
72  android.os.Handler.handleCallback(Handler.java:789)
73  android.os.Handler.dispatchMessage(Handler.java:98)
74  android.os.Looper.loop(Looper.java:164)
75  android.app.ActivityThread.main(ActivityThread.java:6938)
76  java.lang.reflect.Method.invoke(Method.java:-2)
77  com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
78  com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

Thread 1382:
0   java.lang.Object.wait(Object.java:-2)
1   java.lang.Daemons$ReferenceQueueDaemon.runInternal(Daemons.java:178)
2   java.lang.Daemons$Daemon.run(Daemons.java:103)
3   java.lang.Thread.run(Thread.java:764)

Thread 1383:
0   java.lang.Object.wait(Object.java:-2)
1   java.lang.Object.wait(Object.java:422)
2   java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:188)
3   java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:209)
4   java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:232)
5   java.lang.Daemons$Daemon.run(Daemons.java:103)
6   java.lang.Thread.run(Thread.java:764)

Thread 1384:
0   java.lang.Thread.sleep(Thread.java:-2)
1   java.lang.Thread.sleep(Thread.java:373)
2   java.lang.Thread.sleep(Thread.java:314)
3   java.lang.Daemons$FinalizerWatchdogDaemon.sleepFor(Daemons.java:342)
4   java.lang.Daemons$FinalizerWatchdogDaemon.waitForFinalization(Daemons.java:364)
5   java.lang.Daemons$FinalizerWatchdogDaemon.runInternal(Daemons.java:281)
6   java.lang.Daemons$Daemon.run(Daemons.java:103)
7   java.lang.Thread.run(Thread.java:764)

Thread 1393:
0   java.lang.Object.wait(Object.java:-2)
1   java.lang.Object.wait(Object.java:422)
2   com.google.android.gms.internal.zzccv.run

Thread 1394:
0   java.lang.Object.wait(Object.java:-2)
1   java.lang.Thread.parkFor$(Thread.java:2135)
2   sun.misc.Unsafe.park(Unsafe.java:358)
3   java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:230)
4   java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2101)
5   java.util.concurrent.LinkedBlockingQueue.poll(LinkedBlockingQueue.java:467)
6   java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1086)
7   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1147)
8   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
9   java.lang.Thread.run(Thread.java:764)

Thread 1396:
0   java.lang.Object.wait(Object.java:-2)
1   java.lang.Thread.parkFor$(Thread.java:2135)
2   sun.misc.Unsafe.park(Unsafe.java:358)
3   java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:230)
4   java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2101)
5   java.util.concurrent.LinkedBlockingQueue.poll(LinkedBlockingQueue.java:467)
6   java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1086)
7   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1147)
8   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
9   java.lang.Thread.run(Thread.java:764)

Thread 1397:
0   java.lang.Object.wait(Object.java:-2)
1   java.lang.Thread.parkFor$(Thread.java:2135)
2   sun.misc.Unsafe.park(Unsafe.java:358)
3   java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:230)
4   java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2101)
5   java.util.concurrent.LinkedBlockingQueue.poll(LinkedBlockingQueue.java:467)
6   java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1086)
7   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1147)
8   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
9   java.lang.Thread.run(Thread.java:764)

Thread 1398:
0   java.lang.Object.wait(Object.java:-2)
1   java.lang.Thread.parkFor$(Thread.java:2135)
2   sun.misc.Unsafe.park(Unsafe.java:358)
3   java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:230)
4   java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2101)
5   java.util.concurrent.LinkedBlockingQueue.poll(LinkedBlockingQueue.java:467)
6   java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1086)
7   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1147)
8   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
9   java.lang.Thread.run(Thread.java:764)

Thread 1400:
0   java.lang.Object.wait(Object.java:-2)
1   java.lang.Thread.parkFor$(Thread.java:2135)
2   sun.misc.Unsafe.park(Unsafe.java:358)
3   java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:230)
4   java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2101)
5   java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1132)
6   java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1113)
7   java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1087)
8   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1147)
9   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
10  java.lang.Thread.run(Thread.java:764)

Thread 1401:
0   java.lang.Object.wait(Object.java:-2)
1   java.lang.Thread.parkFor$(Thread.java:2135)
2   sun.misc.Unsafe.park(Unsafe.java:358)
3   java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:230)
4   java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2101)
5   java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1132)
6   java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1113)
7   java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1087)
8   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1147)
9   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
10  java.lang.Thread.run(Thread.java:764)

Thread 1403:
0   java.lang.Object.wait(Object.java:-2)
1   com.android.okhttp.ConnectionPool$1.run(ConnectionPool.java:101)
2   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
3   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
4   java.lang.Thread.run(Thread.java:764)

Thread 1408:
0   android.os.MessageQueue.nativePollOnce(MessageQueue.java:-2)
1   android.os.MessageQueue.next(MessageQueue.java:325)
2   android.os.Looper.loop(Looper.java:142)
3   android.os.HandlerThread.run(HandlerThread.java:65)

Thread 1412:
0   java.lang.Object.wait(Object.java:-2)
1   java.lang.Thread.parkFor$(Thread.java:2135)
2   sun.misc.Unsafe.park(Unsafe.java:358)
3   java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:230)
4   java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2101)
5   java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1132)
6   java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1113)
7   java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1087)
8   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1147)
9   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
10  java.lang.Thread.run(Thread.java:764)

Thread 1425:
0   java.lang.Object.wait(Object.java:-2)
1   com.android.okhttp.okio.AsyncTimeout.awaitTimeout(AsyncTimeout.java:323)
2   com.android.okhttp.okio.AsyncTimeout.-wrap0
3   com.android.okhttp.okio.AsyncTimeout$Watchdog.run(AsyncTimeout.java:286)

Thread 1426:
0   java.lang.Object.wait(Object.java:-2)
1   java.lang.Thread.parkFor$(Thread.java:2135)
2   sun.misc.Unsafe.park(Unsafe.java:358)
3   java.util.concurrent.locks.LockSupport.park(LockSupport.java:190)
4   java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2059)
5   java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
6   java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1087)
7   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1147)
8   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
9   java.lang.Thread.run(Thread.java:764)

Thread 1428:
0   android.os.MessageQueue.nativePollOnce(MessageQueue.java:-2)
1   android.os.MessageQueue.next(MessageQueue.java:325)
2   android.os.Looper.loop(Looper.java:142)
3   android.os.HandlerThread.run(HandlerThread.java:65)

Thread 1431:
0   android.os.MessageQueue.nativePollOnce(MessageQueue.java:-2)
1   android.os.MessageQueue.next(MessageQueue.java:325)
2   android.os.Looper.loop(Looper.java:142)
3   android.os.HandlerThread.run(HandlerThread.java:65)

Thread 1436:
0   java.lang.Object.wait(Object.java:-2)
1   java.lang.Thread.parkFor$(Thread.java:2135)
2   sun.misc.Unsafe.park(Unsafe.java:358)
3   java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:230)
4   java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2101)
5   java.util.concurrent.LinkedBlockingQueue.poll(LinkedBlockingQueue.java:467)
6   java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1086)
7   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1147)
8   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
9   java.lang.Thread.run(Thread.java:764)
10  com.google.android.gms.analytics.zzj$zzc.run

Thread 1441:
0   android.os.MessageQueue.nativePollOnce(MessageQueue.java:-2)
1   android.os.MessageQueue.next(MessageQueue.java:325)
2   android.os.Looper.loop(Looper.java:142)
3   android.os.HandlerThread.run(HandlerThread.java:65)

Thread 1443:
0   android.os.MessageQueue.nativePollOnce(MessageQueue.java:-2)
1   android.os.MessageQueue.next(MessageQueue.java:325)
2   android.os.Looper.loop(Looper.java:142)
3   android.os.HandlerThread.run(HandlerThread.java:65)

Thread 1444:
0   java.lang.Object.wait(Object.java:-2)
1   java.lang.Thread.parkFor$(Thread.java:2135)
2   sun.misc.Unsafe.park(Unsafe.java:358)
3   java.util.concurrent.locks.LockSupport.park(LockSupport.java:190)
4   java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2059)
5   java.util.concurrent.PriorityBlockingQueue.take(PriorityBlockingQueue.java:548)
6   java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1087)
7   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1147)
8   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
9   java.lang.Thread.run(Thread.java:764)
10  com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:347)

Thread 1445:
0   java.lang.Object.wait(Object.java:-2)
1   java.lang.Thread.parkFor$(Thread.java:2135)
2   sun.misc.Unsafe.park(Unsafe.java:358)
3   java.util.concurrent.locks.LockSupport.park(LockSupport.java:190)
4   java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2059)
5   java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
6   java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1087)
7   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1147)
8   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
9   java.lang.Thread.run(Thread.java:764)

Thread 1447:
0   java.lang.Object.wait(Object.java:-2)
1   java.lang.Thread.parkFor$(Thread.java:2135)
2   sun.misc.Unsafe.park(Unsafe.java:358)
3   java.util.concurrent.locks.LockSupport.park(LockSupport.java:190)
4   java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2059)
5   java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
6   java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1087)
7   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1147)
8   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
9   java.lang.Thread.run(Thread.java:764)

Thread 1448:
0   java.lang.Object.wait(Object.java:-2)
1   java.lang.Thread.parkFor$(Thread.java:2135)
2   sun.misc.Unsafe.park(Unsafe.java:358)
3   java.util.concurrent.locks.LockSupport.park(LockSupport.java:190)
4   java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2059)
5   java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
6   java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1087)
7   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1147)
8   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
9   java.lang.Thread.run(Thread.java:764)

Thread 1449:
0   java.lang.Object.wait(Object.java:-2)
1   java.lang.Thread.parkFor$(Thread.java:2135)
2   sun.misc.Unsafe.park(Unsafe.java:358)
3   java.util.concurrent.locks.LockSupport.park(LockSupport.java:190)
4   java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2059)
5   java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
6   java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1087)
7   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1147)
8   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
9   java.lang.Thread.run(Thread.java:764)

**Comment by akarnokd** [comment]
What is the delegate you are using in that `Select` statement? I'd guess you dereference a null in your delegate because that `OnNext` should never crash with such exception on its own.

**Comment by danielcweber** [comment]
Closing due to no answer from OP.
