### ISSUE TITLE
CI fails to fetch .NET core sdk 2.1.400-preview-009063

### ISSUE THREAD

**Issue by quinmars** [dotnet/reactive#794]
See https://dotnetfoundation.visualstudio.com/Rx.NET/_build/results?buildId=3261&view=logs from the PR #793.

**Comment by quinmars** [comment]
Same with #795.

**Comment by danielcweber** [comment]
This seems to be related to https://github.com/Microsoft/vsts-tasks/issues/7754.

**Comment by quinmars** [comment]
Seems to be fixed by  7d5254e.
