### ISSUE TITLE
Repeat inside SelectMany does not terminate.

### ISSUE THREAD

**Issue by tompee26** [dotnet/reactive#810]
The subscription inside SelectMany (with repeat) does not terminate when outer subscription is disposed. Below is my code:

```c#
var subscription = Observable.Return("value")
    .SelectMany(resource =>
    {
        return Observable.Defer(() => Observable.Return(resource))
            .Do(Console.WriteLine)
            .Repeat();
    })
    .SubscribeOn(Scheduler.Default)
    .Subscribe(_ => { }, Console.WriteLine, () => Console.WriteLine("Completed"));
subscription.Dispose();
```

The side effect inside SelectMany is still called even though subcription is already disposed. I tried running the same sequence in RxKotlin and it terminates as expected.
```kotlin
val subscription = Observable.just("value")
        .flatMap { resource ->
            Observable.defer { Observable.just(resource) }
                    .doOnNext(::println)
                    .repeat()
        }
        .subscribeOn(Schedulers.computation())
        .subscribe({}, ::println) { println("completed") }

subscription.dispose()
```

Am I missing or misunderstanding something? Any help would be appreciated. Thanks in advance.

**Comment by akarnokd** [comment]
This is likely due to the synchronous cancellation problem that RxJava has solved by switching to a different architecture. We can't do much about it in Rx.NET other than introducing asynchrony/trampolining. Try with `Observable.Return(resource, CurrentThreadScheduler.Instance)`.

**Comment by tompee26** [comment]
Hello David,

Thank you for your suggestion. I tried to use the current scheduler but still it does not terminate. I also tried the repeat overload with scheduler but to no avail. Is this specific only to repeat? I tried interval and it terminates.

**Comment by akarnokd** [comment]
`Interval` uses an async scheduler by default. You could try with `DefaultScheduler.Instance`.
