### ISSUE TITLE
Update System.Reactive.Experimental to target .NET Standard

### ISSUE THREAD

**Issue by atifaziz** [dotnet/reactive#812]
[System.Reactive.Experimental (4.1.0 at time of reporting)](https://www.nuget.org/packages/System.Reactive.Experimental/4.1.0) targets .NET Framework 4.6:

https://github.com/dotnet/reactive/blob/1888ca8e4aced0f7168b5e3e23b40b92fe0a5ec2/Rx.NET/Source/facades/System.Reactive.Experimental/System.Reactive.Experimental.csproj#L3-L5

Any reason it cannot be updated to target .NET Standard 2.0 like System.Reactive?

**Comment by danielcweber** [comment]
Closing since #821 got closed.

**Comment by atifaziz** [comment]
Since #821 was closed without merging, can we re-open this?

**Comment by onovotny** [comment]
Not sure what there is to do here? There is no need for the facades to target .NET standard since they are type-forwarders. The old libraries that could have references to `System.Reactive.Experimental` could have only been .NET framework ones since that's what the original library targeted. Thus the facades only need to match that.

**Comment by atifaziz** [comment]
@onovotny Ah, so looks like the [experimental stuff was moved into the base package](https://github.com/dotnet/reactive/blob/0f837d11385cfaf575861ccc5a5fbcafb22d888f/Rx.NET/Source/facades/System.Reactive.Experimental/TypeForwarders.Experimental.cs), since 4.0? And so the System.Reactive.Experimental package is no longer needed if I am target .NET Standard 2.0? Am I understand the right?

**Comment by onovotny** [comment]
Correct. Those are compatibility packages to support libraries that are built against 3.x but using 4.x where the types were all moved into System.Reactive.

**Comment by atifaziz** [comment]
@onovotny Awesome and thanks for the prompt responses and clarification! Keep up the great work.
