### ISSUE TITLE
[UWP] Stuck on Build started on release mode.

### ISSUE THREAD

**Issue by AwsomeCode** [dotnet/reactive#814]
Step to reproduce
1. Create a blank UWP Project.
2. Verify its building in Release mode.
3. Add System.Reactive.Linq (4.1.0) Nuget package.
4. Run build again in release mode but it never be completed.

**Comment by akarnokd** [comment]
Try `System.Reactive`, not that `Linq` package.

**Comment by AwsomeCode** [comment]
Any specific reasons?

**Comment by onovotny** [comment]
There's a bug in the .NET Native compiler that's being investigated. For now, please use 4.0.

**Comment by AwsomeCode** [comment]
@akarnokd Same issue with `System.Reactive`
@onovotny downgraded to 4.0 is working. Thanks.

**Comment by Lukespacewalker** [comment]
I update UWP to 6.2.2 and System.Reactive to 4.1 and use `<ShortcutGenericAnalysis>true</ShortcutGenericAnalysis>` flag then the application will be succesfully compiled with .net Native compilation.

```
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="15.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" Condition="Exists('$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props')" />
  <PropertyGroup>
    <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
    <Platform Condition=" '$(Platform)' == '' ">x86</Platform>
    ....
    <ShortcutGenericAnalysis>true</ShortcutGenericAnalysis>
  </PropertyGroup>
```

**Comment by bartdesmet** [comment]
Has this been resolved by now?
