### ISSUE TITLE
ToTask doesn't unsubscribe properly

### ISSUE THREAD

**Issue by PawelGerr** [dotnet/reactive#838]
This issue occurs in a combination of an async method with `Concat`, `Take(1)` and with `ToTask` at the end.

Rx version: 4.1.2

Observable setup:
```
Func<Task> asyncMethod = async () =>
                         {
                            await Task.Delay(500);
                            Console.WriteLine("Done");
                         };

var observable = Observable.Interval(TimeSpan.FromMilliseconds(200))
                           .Do(i => Console.WriteLine(i))
                           .Select(_ => Observable.FromAsync(asyncMethod))
                           .Concat()
                           .Take(1)
                           .Finally(() => Console.WriteLine("Finished"));
```

`Subscribe` produces the expected result:

```
observable.Subscribe();

// Output:
0
1
2
Done
Finished
```

The task returned by `ToTask` completes correctly after 1st item when using `await` but the `Interval` keeps emitting values:
```
await observable.ToTask();

// Output:
0
1
2
Done
3
4
5
... and so on
````

**Comment by danielcweber** [comment]
Can you really confirm that the task returned by `ToTask` completes after the first item? It should do the exact opposite, i.e. only complete on termination of the sequence and hold the last observed value.

**Comment by danielcweber** [comment]
Also, I haven't run that code yet, but can you quickly assert the type of `observable` please. Is it `IObservable<long>` or rather `IObservable<IObservable<long>>`?

**Comment by PawelGerr** [comment]
> Also, I haven't run that code yet, but can you quickly assert the type of `observable` please. Is it `IObservable<long>` or rather `IObservable<IObservable<long>>`?

It is `IObservable<Unit>` because the async method doesn't return anything.

I changed the line with the async method so it passes through the number emitted by the interval.

```
Func<Task> asyncMethod = async () =>
                         {
                            await Task.Delay(500);
                            Console.WriteLine("Done");
                         };

IObservable<long> observable = Observable.Interval(TimeSpan.FromMilliseconds(200))
                           .Do(i => Console.WriteLine(i))
                          // added ".Select(_ => i)" at the end
                           .Select(i => Observable.FromAsync(asyncMethod).Select(_ => i))
                           .Concat()
                           .Take(1)
                           .Finally(() => Console.WriteLine("Finished"));

long result = await observable.ToTask();
Console.WriteLine("Result:" + result);
```

The output is:
```
0
1
2
Done
Result:0
3
4
5
...
```

The result is the same with `.NET Core 2.1` and `.NET 4.7.2`

**Comment by akarnokd** [comment]
Does it work with 4.0?

**Comment by PawelGerr** [comment]
> Does it work with 4.0?

Indeed, it does, after downgrade to Rx 4.0.0

The output is:
```
0
1
2
Done
Result:0
3
```

And the issue comes back after going to Rx 4.1.0

**Comment by akarnokd** [comment]
What's the Concat overload's signature picked by the compiler there? (I'm currently not next to my computer).

**Comment by PawelGerr** [comment]
> What's the Concat overload's signature picked by the compiler there? (I'm currently not next to my computer).

![image](https://user-images.githubusercontent.com/7135790/47798685-2c370100-dd29-11e8-9dde-3c8c3c7b6e28.png)

**Comment by danielcweber** [comment]
What happens after you away the task? I could imagine that the task continuation runs synchronously, thus delaying unsubscription.

**Comment by akarnokd** [comment]
Could you place Finally()s around to see where the dispose stops?

I don't think its a synchronous execution due to await Task.Delay thus the various Subscribe returns should be chained up by then.

(It can take another 1.5 hours for me before I can diagnose this myself.)

**Comment by PawelGerr** [comment]
> What happens after you await the task? I could imagine that the task continuation runs synchronously, thus delaying unsubscription.

I'm waiting with `Console.ReadLine()`

I'm printing out the thread id now. It looks like the method is really async because the id changes after `await`
```
Console.WriteLine($"Thread id: {Thread.CurrentThread.ManagedThreadId}");
Console.WriteLine($"Result: {await observable.ToTask()}");
Console.WriteLine($"Thread id: {Thread.CurrentThread.ManagedThreadId}");

Console.ReadLine();
```

Output:
```
Thread id: 1
0
1
2
Done
Result: 0
Thread id: 4
3
4
...
```

**Comment by PawelGerr** [comment]
The issue seems to be gone after switching from `Console.ReadLine();` to a task that never completes
```
var tcs = new TaskCompletionSource<object>();
await tcs.Task;
```
The output is:
```
Thread id: 1
0
1
2
Done
Result: 0
Thread id: 4
Finished
``` 

The unsubscription seems to be delayed by `Console.ReadLine()`

**Comment by danielcweber** [comment]
I guess it's very much related to https://github.com/dotnet/reactive/issues/456. I can get into this tomorrow.

**Comment by PawelGerr** [comment]
> Could you place Finally()s around to see where the dispose stops?
> 
> I don't think its a synchronous execution due to await Task.Delay thus the various Subscribe returns should be chained up by then.
> 
> (It can take another 1.5 hours for me before I can diagnose this myself.)

I'm not sure what you mean with "place Finally()s around". If I add `Finally()`s after each method call I get the same output as before.

```
IObservable<long> observable = Observable.Interval(TimeSpan.FromMilliseconds(200))
                                         .Finally(() => Console.WriteLine("Interval"))
                                         .Do(i => Console.WriteLine(i))
                                         .Select(i => Observable.FromAsync(asyncMethod).Select(_ => i))
                                         .Finally(() => Console.WriteLine("Async"))
                                         .Concat()
                                         .Finally(() => Console.WriteLine("Concat"))
                                         .Take(1)
                                         .Finally(() => Console.WriteLine("Finished"));
```

**Comment by akarnokd** [comment]
I see what's going on: before the await, the code runs on the *MainThread*. When the `Take` completes, the `ToTask` [resumes](https://github.com/dotnet/reactive/blob/master/Rx.NET/Source/src/System.Reactive/Threading/Tasks/TaskObservableExtensions.cs#L404) the `TaskCompletionSource` it gave back which then runs the remainder of the `Main` method on a *worker thread*, which then blocks so `ToTask` can't issue a [Dispose()](https://github.com/dotnet/reactive/blob/master/Rx.NET/Source/src/System.Reactive/Threading/Tasks/TaskObservableExtensions.cs#L412) to stop the whole chain.

When running with 4.0, it still doesn't print "Finished" but the `Interval` stops producing items because in 4.0, `Concat` was `Merge(1)` and `Merge` uses `lock` that is held (by the continuation that is blocked in ReadLine) when number 3 would be emitted, thus stopping the interval thread entirely.

A resolution would be to move [Dispose()](https://github.com/dotnet/reactive/blob/master/Rx.NET/Source/src/System.Reactive/Threading/Tasks/TaskObservableExtensions.cs#L412) to the top of the method so that the resumption is not preventing a dispose call.

**Comment by PawelGerr** [comment]
> I see what's going on: before the await, the code runs on the _MainThread_. When the `Take` completes, the `ToTask` [resumes](https://github.com/dotnet/reactive/blob/master/Rx.NET/Source/src/System.Reactive/Threading/Tasks/TaskObservableExtensions.cs#L404) the `TaskCompletionSource` it gave back which then runs the remainder of the `Main` method on a _worker thread_, which then blocks so `ToTask` can't issue a [Dispose()](https://github.com/dotnet/reactive/blob/master/Rx.NET/Source/src/System.Reactive/Threading/Tasks/TaskObservableExtensions.cs#L412) to stop the whole chain.
> 
> When running with 4.0, it still doesn't print "Finished" but the `Interval` stops producing items because in 4.0, `Concat` was `Merge(1)` and `Merge` uses `lock` that is held (by the continuation that is blocked in ReadLine) when number 3 would be emitted, thus stopping the interval thread entirely.
> 
> A resolution would be to move [Dispose()](https://github.com/dotnet/reactive/blob/master/Rx.NET/Source/src/System.Reactive/Threading/Tasks/TaskObservableExtensions.cs#L412) to the top of the method so that the resumption is not preventing a dispose call.

Good catch!
To move the `Dispose` higher up feels more like a hack because the "user code" (i.e. my `Console.ReadLine` :P ) still hijacks your thread. What if we tell the TCS to continue on a different thread because I can't see any use cases where you want to give up on your thread? Do you see some problems with that solution? 

`TaskObservableExtensions.cs` line 442
```
var tcs = new TaskCompletionSource<TResult>(state, TaskCreationOptions.RunContinuationsAsynchronously);
``` 

With that change I get the output:
```
Thread id: 1
0
1
2
Done
Result: 0
Thread id: 5
Finished
```

**Comment by danielcweber** [comment]
The discussion in #456 didn't really come to a conclusion other than maybe parametrize the behaviour. I guess either way may produce funny results if code blocks somewhere. The thing is, changing that behaviour sounds reasonable and clean to me, but we already got some issues here for behavioral changes we didn't even intend.... 

Can you work around the blocking for now?

**Comment by danielcweber** [comment]
>What if we tell the TCS to continue on a different thread because I can't see any use cases where you want to give up on your thread? Do you see some problems with that solution?

When concurrency is introduced by any Rx-operators, it is made in a controllable way (e.g. through `IScheduler`). The proposed solution would depart from that paradigm. Of course, there could be a parametrized version of `ToTask` in the future.

**Comment by PawelGerr** [comment]
> The discussion in #456 didn't really come to a conclusion other than maybe parametrize the behaviour. I guess either way may produce funny results if code blocks somewhere. The thing is, changing that behaviour sounds reasonable and clean to me, but we already got some issues here for behavioral changes we didn't even intend....

Sound like a mental fight with oneself :)
 
> @thinktecture Can you work around the blocking for now?

Yes, I can work around the issue

**Comment by bartdesmet** [comment]
> Of course, there could be a parametrized version of ToTask in the future, such that concurrency actually can be controlled.

This is a reasonable stance, assuming the parameterization is on `IScheduler` and the default matches current behavior. Any time we have to make decisions about where or when to run something, there should be an `IScheduler` to control such behavior.
