### ISSUE TITLE
OnNext races with OnCompleted using GroupByUntil

### ISSUE THREAD

**Issue by asgerhallas** [dotnet/reactive#839]
Hi, I have this issue that does not seem right, though it might just be me misunderstanding something. It can be replicated like this:

    [Fact]
    public async Task RaceToTheEnd()
    {
        var scheduler1 = new EventLoopScheduler();
        var scheduler2 = new EventLoopScheduler();

        await Observable.Interval(TimeSpan.FromMilliseconds(150))
            .Select(x => x.ToString())
            .GroupByUntil(_ => 0, window => window.Throttle(TimeSpan.FromMilliseconds(100), scheduler2))
            .ObserveOn(scheduler1)
            .Select(window => window
                .Select(x =>
                {
                    output.WriteLine($"Handled on thread {Thread.CurrentThread.ManagedThreadId}: {x}");
                    return x;
                })
                .LastOrDefaultAsync()
                .Select(x =>
                {
                    output.WriteLine($"Completed on thread {Thread.CurrentThread.ManagedThreadId}: {x}");

                    if (x == null) throw new Exception();

                    return x;
                })
            )
            .Take(10)
            .Concat();
    }

This will result in the exception on the line `if (x == null) throw new Exception();` indicating the the group was empty. It looks like the closing-observable fires while the first event of the group is handled and then manages to complete the group before the first OnNext is done. I did not think this should be possible?

This also happens when I move the ObserveOn to later, but only if the handling takes some time like this: 

            .GroupByUntil(_ => 0, window => window.Throttle(TimeSpan.FromMilliseconds(100), scheduler2))
            .Select(window => window
                .ObserveOn(scheduler1)
                .Select(x =>
                {
                    output.WriteLine($"Handled on thread {Thread.CurrentThread.ManagedThreadId}: {x}");
                    Thread.Sleep(140);
                    return x;
                })

And in production it also happens if the ObserveOn is before the GroupByUntil and the system is under load,, though I can't replicate this in the test.

An observation is, that if I replace Concat() with for example LastAsync(), this does not happen. 

Is this a bug or me doing it wrong?

**Comment by akarnokd** [comment]
The behavior of Rx.NET's GroupBy(Until) is that if you don't start observing the group right away, you can miss items on them. Adding that `ObserveOn` as well as using `Concat` instead of `Merge` may all contribute to losing items on general.

**Comment by asgerhallas** [comment]
Thanks for the response. Hmm, yes, I can see that my test case falls into that trap, but I think that's actually just a poor repro, I have made. My production code has ObserveOn before any grouping. Could missing items also happen in that case?

**Comment by akarnokd** [comment]
No. What matters is after the `GroupBy`. Anything that would delay the subscription to the groups is of suspect.

**Comment by asgerhallas** [comment]
Thanks. I'll see if I can make a better reproduction then. The missing value seems to be the last value in a group and it only happens when the group closes on another thread than this last item is handled on.

**Comment by asgerhallas** [comment]
What happens if the group is closed on the throttle-scheduler and concurrently another value arrives on the observed-on scheduler? Will the new group open before the last one was closed? That - together with Concat - would cause missing values, wouldn't it? 

Both are the TaskPoolScheduler.Default in this scenario.

**Comment by akarnokd** [comment]
It can end up in the closing or a new group if asynchrony is involved closing the group. So you may miss items when the groups are being closed. There is no good way to know from inside because you'd need a way to know if the item sent to a group has been received, but where would such a confirmation boundary be?

**Comment by asgerhallas** [comment]
Hmm... I'm not sure I understand. Why can't GroupByUntil lock a given key until the OnCompleted() call has been executed - even though the completion might be initiated on another thread? I can understand that this of course only goes as far as the next ObserveOn in the chain, but I didn't think GroupByUntil was meant to have overlapping groups with the same key in this scenario?

**Comment by asgerhallas** [comment]
It seems like, I can get around it by using an EventLoopScheduler though, like:
    
    var eventLoopScheduler = new EventLoopScheduler();
    stream.ObserveOn(eventLoopScheduler).GroupBy(x => x.type, x => x.commit)
    ...
    .GroupByUntil(_ => 0, window => window.Throttle(throttle, TaskPoolScheduler.Default).ObserveOn(eventLoopScheduler))

Don't know if this has any drawbacks?

**Comment by akarnokd** [comment]
> Why can't GroupByUntil lock a given key until the OnCompleted() call has been executed

This may lead to a deadlock.

Do you have multiple groups in your code or you just wanted to create non-overlapping windows with boundary triggered by some timeout? If so, I'd use `Publish` and `window` instead where there should be no such lost event problem (assuming you still start consuming windows immediately):

```cs
source.Publish(shared =>
   shared.Window(shared.Throttle(time, scheduler))
)
.SelectMany(window => window)
```

**Comment by asgerhallas** [comment]
> This may lead to a deadlock.

You have helped a lot already, but do you care to explain how? :)

> Do you have multiple groups in your code or you just wanted to create non-overlapping windows with boundary triggered by some timeout?

I'd like non-overlapping windows, but with the caveat that they must not open before the first value is observed. I couldn't figure it out using the Window-operator. And then I thought the GroupByUntil was working similarly...

**Comment by asgerhallas** [comment]
I'll close this non-issue now. @akarnokd thank you for your help, it got me over the finish line!

**Comment by strawd** [comment]
@asgerhallas any chance you could share what you did to finally solve this? I believe I am running into the same issue. I too would like to use `GroupByUntil` because of its ability to start a grouping when an item arrives, but I have found that occasionally an item is dropped from the result despite being seen if I log in the functions passed to `GroupByUntil`.

```C#
source.GroupByUntil(_ => 0, group =>
    group.Throttle(quietPeriodDuration)
    .Amb(group.Where((x, index) => (index + 1) >= maximumBatchSize))
    .Amb(group.Delay(maximumProcessingDelay))))
.SelectMany(group => group.ToList());
.Subscribe(subscriptionFunction);
```

I thought based on this discussion that maybe `Publish` was the key, but that did not fix the issue.

```C#
source.Publish(publishedUpdates =>
    publishedUpdates.GroupByUntil(_ => 0, group =>
        group.Throttle(quietPeriodDuration)
        .Amb(group.Where((x, index) => (index + 1) >= maximumBatchSize))
        .Amb(group.Delay(maximumProcessingDelay))))
.SelectMany(group => group.ToList());
.Subscribe(subscriptionFunction);
```

Any tips would be very much appreciated!

**Comment by asgerhallas** [comment]
@strawd looking through the code from then, two things come to mind:

1. Use the same scheduler on the Throttle as you're observing the source on, like:

```
source.ObserveOn(myScheduler)
    .GroupByUntil(_ => 0, group =>
        group.Throttle(quietPeriodDuration, myScheduler)...
```

2. I had two kinds of GroupByUntil in my query: One that I called LazyWindow, which is like yours and done as mentioned above, and then a SerialGroupBy that never allowed two groups to overlap, always closing the first group before starting the next one. That one I had to implement from scratch like:

```
public static class SerialGroupByOperator
{
    public static IObservable<IGroupedObservable<TKey, TElement>> SerialGroupBy<TKey, TSource, TElement>(
        this IObservable<TSource> stream, Func<TSource, TKey> keySelector, Func<TSource, TElement> elementSelector) =>
        Observable.Create<IGroupedObservable<TKey, TElement>>(observer => stream
            .Scan<TSource, GroupedObservable<TKey, TElement>>(null, (current, next) =>
            {
                var key = keySelector(next);

                if (current == null)
                {
                    var nextGroup = new GroupedObservable<TKey, TElement>(key);

                    observer.OnNext(nextGroup);
                    nextGroup.Group.OnNext(elementSelector(next));

                    return nextGroup;
                }

                if (!Equals(key, current.Key))
                {
                    current.Group.OnCompleted();

                    var nextGroup = new GroupedObservable<TKey, TElement>(key);

                    observer.OnNext(nextGroup);
                    nextGroup.Group.OnNext(elementSelector(next));

                    return nextGroup;
                }

                current.Group.OnNext(elementSelector(next));

                return current;
            })
            .LastOrDefaultAsync()
            .Where(x => x != null)
            .Subscribe(x => x.Group.OnCompleted(), observer.OnError, observer.OnCompleted));
}

internal class GroupedObservable<TKey, TElement> : IGroupedObservable<TKey, TElement>
{
    public GroupedObservable(TKey key)
    {
        Key = key;
        Group = new Subject<TElement>();
    }

    public TKey Key { get; }
    public ISubject<TElement> Group { get; }

    public IDisposable Subscribe(IObserver<TElement> observer) => Group.Subscribe(observer);
}
```

Some of my original problems might have been the combination of the two, but I must admit I can't recall the details exactly. But maybe some of the above will help?

PS. I have a set of test cases for the SerialGroupBy implementation. If you end up using it, I can share those too... :)

**Comment by strawd** [comment]
Thanks @asgerhallas - I'll look into those aspects. I appreciate the help!

**Comment by j2ghz** [comment]
Is there a way to guarantee GroupByUntil won't lose items? I'm working with a use case where that must not happen.
