### ISSUE TITLE
Ix.Async: Have Virtual Task.Delay for unit testing (like TestScheduler in Rx)?

### ISSUE THREAD

**Issue by akarnokd** [dotnet/reactive#846]
I've implemented a lot of coordinating/multi-source Async enumerables in my project and testing them sometimes needs tasks executed over time in an interleaved fashion (i.e., source 1 resume after 100ms, source 2 resume after 200ms). This usually works on my local machine but has a few problems:

- the minimum reliable timestep locally and on CI,
- tests take longer to execute as they have to wait 2-3 seconds total in some cases,
- tests may no longer run in parallel with each other, the test suite takes way longer.

Any thoughts or tips?

**Comment by quinmars** [comment]
`Task.Yield()`is the cheapest way to cause non-immediate execution, I know so far. In my [shared state tests](https://github.com/dotnet/reactive/blob/29b57a5b438a41eea663cfaee5aa2a928cdc536c/Ix.NET/Source/System.Linq.Async.Tests/SharedState.cs#L29), however, it didn't forced concurrent excution reliably. So I had to switch to `Task.Delay()`. If you really need timing, something like the Rx test scheduler would be nice, and could work for task coming from outside. Maybe we should take a look how the corefx and roslyn teams test their asynchronous code.

**Comment by akarnokd** [comment]
I've come up with the `TestTaskRunner` that allows creating tasks with delay and is then completed via a `TaskCompletionSource` each when the virtual time is right:

https://github.com/akarnokd/async-enumerable-dotnet/blob/master/async-enumerable-dotnet/TestTaskRunner.cs

Single-step testing is a bit awkward though:

```cs
[Fact]
public async void Second_Win_Sync()
{
    var ttr = new TestTaskRunner();

    var t = AsyncEnumerable.Amb(
                AsyncEnumerable.Range(1, 5)
                    .DoOnNext(async v => { await ttr.CreateCompleteTask(1000); }),
                AsyncEnumerable.Range(6, 5)
                    .DoOnNext(async v => { await ttr.CreateCompleteTask(500); })
            )
            .GetAsyncEnumerator()
        ;

    try
    {
        for (var i = 6; i <= 10; i++)
        {
            var t0 = t.MoveNextAsync();

            await ttr.TaskQueued(); // <----------------------------------

            ttr.AdvanceTimeBy(500); // <----------------------------------

            await t0;

            Assert.Equal(i, t.Current);
        }
        
        Assert.False(await t.MoveNextAsync());
    }
    finally
    {
        await t.DisposeAsync();
    }

}        
```

So basically:
1. fire off `MoveNextAsync`
2. wait for a task being queued
3. move the time forward
4. await the `MoveNextAsync`
5. validate state

From this, 2) is mostly fragile because how to know if the right task has been added to the queue. What if there was a `ttr.CreateCompleteTask(2000)` first somewhere and `ttr.CreateCompleteTask(500)` hasn't happened yet?

**Comment by akarnokd** [comment]
This probably doesn't work well enough, will think of something else.
