### ISSUE TITLE
Unity Android IL2CPP build target

### ISSUE THREAD

**Issue by dzmitry-lahoda** [dotnet/reactive#848]
Please support IL2CPP Unity 2018.3+ which targets .NET Standard 2.0. Seems some open generics do not work. I have tried to handle that in

https://github.com/dzmitry-lahoda/reactive/tree/unityaot

and 

https://github.com/dzmitry-lahoda/AdvancedCameraControls  .

Issue I get is here

https://github.com/neuecc/UniRx/issues/300#issuecomment-439877584

**Comment by dzmitry-lahoda** [comment]
I see that reactive has bloat of old platforms, fails to build with `dotnet build`, and possible fast reflection free(small) core is mixed with platforms-helpers code. Cleaning and splitting could be could. So `core` could be used and build in Unity as is.

**Comment by grofit** [comment]
Has there been any progress in this area? 

I have been longing to remove UniRx and just use rx.net in unity for a while (also I need to support other frameworks such as MG/Godot etc which cant use UniRx).

To my knowledge the last frontier to pass is the AOT related code so fi we can get that sorted this should be usable in unity 2018+ right (given the .net 4.* support)

**Comment by RDeluxe** [comment]
I'm in the same boat: using dotnet.reactive + Unity would be a blessing

**Comment by glennawatson** [comment]
None of the platforms targeted are "old". They are all existing xamarin targets and net461 to avoid binding redirect issues.

**Comment by grofit** [comment]
If any of you guys are interested in talking further on this @RDeluxe @dzmitry-lahoda @Xerios Glenn and I were discussing how ReactiveUI uses rx.net on iOS and other AOT devices in the rx slack in a thread, feel free to jump in on it as you guys have far more knowledge as to the unity constraints than I do and Glenn has been super helpful in detailing what users of his library need to do to use rx in AOT scenarios. 

https://reactivex.slack.com/conversation/C02B9R3QA/p1554282998002200

I appreciate Unity IL2CPP may add some other quirks to the situation but I am getting into conversations over my head, but feel a lot of the answers could come from this conversation with Glenn around how ReactiveUI works.

**Comment by akarnokd** [comment]
This is an old issue and sounds like either UniRx, Unity or ReactiveUI tooling should be handling these.
