### ISSUE TITLE
Starting SignalR hub inside async Observable.Create emits OnComplete when lambda completes

### ISSUE THREAD

**Issue by atlemann** [dotnet/reactive#852]
I'm trying to connect my `HubConnection` on `Subscribe` but when this async lamda completes, the subscription gets an `OnCompleted` out of nowhere and my subscription unsubscribes before getting any notifications.

```csharp
Observable
    .Create<(JobStatus Status, double Progress, bool IsComplete)>(async observer =>
    {
        await _connection.StartAsync();
        await _connection.InvokeAsync<string>("Attach", id);

        var handler =
            _connection
                .On<string, JobStatus, double, bool>(
                    "iterationChanged",
                    (eventId, status, progress, isComplete) =>
                    {
                        if (eventId != id)
                            return;

                        observer.OnNext((status, progress, isComplete));
                        if (status == JobStatus.Finished)
                            observer.OnCompleted();
                    });

        return Disposable.Create(async () =>
                                 {
                                     handler.Dispose();
                                     await _connection.InvokeAsync<string>("Detach", id);
                                     await _connection.StopAsync();
                                 });
    })
    .Subscribe(x => Logger.Debug($"OnNext{x}"),
               ex => Logger.Debug($"OnException{ex}"),
               () => Logger.Debug("OnCompleted"));
```

**Comment by atlemann** [comment]
This works as expected, but I have to start and stop the hub manually, which I don't want.

```csharp
Observable
    .Create<(JobStatus Status, double Progress, bool IsComplete)>(observer =>
    {
        var handler =
            _connection
                .On<string, JobStatus, double, bool>(
                    "iterationChanged",
                    (eventId, status, progress, isComplete) =>
                    {
                        if (eventId != id)
                            return;

                        observer.OnNext((status, progress, isComplete));
                        if (status == JobStatus.Finished)
                            observer.OnCompleted();
                    });

        return Disposable.Create(() => handler.Dispose());
    })
```

**Comment by atlemann** [comment]
You can see it here. Where is that `OnComplete` coming from?

![signalr_fail2](https://user-images.githubusercontent.com/16226914/49734180-c1f87100-fc83-11e8-8a0b-1585a72a64aa.gif)

**Comment by atlemann** [comment]
I guess #83 and #802 are related.

So if the expected behavior is that when the async lamda returns, it emits an `OnComplete`? How can I then do what I want here? I want to asynchronously subscribe to SignalR when someone subscribes to the observable and asynchronously stop and dispose everything when the subscriber unsubscribes.

**Comment by danielcweber** [comment]
The behaviour is indeed by design. It has been subject to discussion though.

You could chain StartAsync and InvokeAsync as separate, individual observables and append what you're currently doing in Create (with SelectMany e.g.).

**Comment by atlemann** [comment]
Sooo  something like this?

```csharp
Observable
    .StartAsync(cts => _connection.StartAsync(cts))
    .SelectMany(_ => _connection.InvokeAsync<string>("Attach", id))
    .Select(_ => 
        Observable
            .Create<(JobStatus Status, double Progress, bool IsComplete)>(observer =>
                {
                    var handler =
                        _connection
                            .On<string, JobStatus, double, bool>(
                                "iterationChanged",
                                (eventId, status, progress, isComplete) =>
                                {
                                    if (eventId != id)
                                        return;

                                    observer.OnNext((status, progress, isComplete));
                                    if (status == JobStatus.Finished)
                                        observer.OnCompleted();
                                });

                    return Disposable.Create(() => handler.Dispose());
                }))
                .Finally(async () =>
                         {
                             await _connection.InvokeAsync<string>("Detach", id);
                             await _connection.StopAsync();
                         })
                .Subscribe(x => Logger.Debug($"OnNext{x}"),
                           ex => Logger.Debug($"OnException{ex}"),
                           () => Logger.Debug("OnCompleted"));
```

**Comment by atlemann** [comment]
I tried this, but `Publish().RefCount()` doesn't seem to work as expected this time. If I have two subscribers, the code inside `Observable.StartAsync` is run twice, which is what I wanted to avoid all along. 

```csharp
Observable
    .StartAsync(async cts =>
                {
                    var connection = await _getConnection.ConfigureAwait(false);
                    await connection.InvokeAsync<string>("Attach", id, cts).ConfigureAwait(false);
                    return connection;
                })
    .SelectMany(connection => 
        Observable
            .Create<(JobStatus Status, double Progress, bool IsComplete)>(observer =>
                {
                    var handler =
                        connection
                            .On<string, JobStatus, double, bool>(
                                "iterationChanged",
                                (eventId, status, progress, isComplete) =>
                                {
                                    if (eventId != id)
                                        return;

                                    observer.OnNext((status, progress, isComplete));
                                    if (status == JobStatus.Finished)
                                        observer.OnCompleted();
                                });

                    return Disposable.Create(async () =>
                                             {
                                                 handler.Dispose();
                                                 await connection.InvokeAsync<string>("Detach", id).ConfigureAwait(false);
                                                 await connection.StopAsync().ConfigureAwait(false);
                                             });
                }))
    .Publish()
    .RefCount();
```

**Comment by bartdesmet** [comment]
`Observable.Create` has arguably been overloaded a little bit to much over the years. This particular overload was introduced to make async generators of events easy to write, which is better done with an `(IObservable<T>, CancellationToken) -> Task` overload that does await with the `IDisposable` stuff altogether.

Fast forward from 2012 to 2019 and we now have a much better way of achieving producing values in an asynchronous fashion, possibily pushing them into an `IObserver<T>` using async iterators and `IAsyncEnumerable<T>` introduced in C# 8.0. (And indeed, a `ToObservable` operator to do just that exists in Ix.)

Taking a step back on the problem show above, it seems you'd really want a `UsingAsync` to really just have an observable that's dependent on some (async) disposable resource. Say you'd be able to encapsulate all of the setup logic in a `Task<Connection> ConnectAsync(CancellationToken)` method and f all the cleanup logic in an `IAsyncDisposable` implementation on your `Connection` wrapper, would a `IObservable<TResult> UsingAsync<TResource, TResult>(Func<CancellationToken, Task<TResource>> create, Func<TResource, IObservable<TResult>>) where TResource : IAsyncDisposable` method solve the issue?

If so, I think it'd be worth considering adding this, given the introduction of `IAsyncDisposable` in the upcoming .NET Core release (and the backport support in the Ix companion project, making it worthwhile to extract these interfaces out of Ix and into a separate assembly for use over here). Also note that the code as written above on this thread does suffer from an `async void` delegate in `Disposable.Create`, so the whole async disposal is fire-and-forget. A proper operator that deals with `IAsyncDisposable` would have to make a choice on this behavior (or it's time to revive the `AsyncRx.NET` project to support deep asynchrony in Rx).

**Comment by atlemann** [comment]
Did this suddenly change in v5?
