### ISSUE TITLE
Invalid <licenseUrl> in NuSpec file for System.Interactive.Async 3.2.0 package

### ISSUE THREAD

**Issue by RafalCichon** [dotnet/reactive#853]
The current license url in nuspec file is:
https://raw.githubusercontent.com/Reactive-Extensions/Rx.NET/master/Ix.NET/Source/license.txt

This url is invalid - Http 404: Not Found

**Comment by danielcweber** [comment]
PRs welcome.

**Comment by RafalCichon** [comment]
#855

**Comment by onovotny** [comment]
We should change this to be `<PackageLicenseExpression>MIT</PackageLicenseExpression>` instead of a license url.

**Comment by quinmars** [comment]
@onovotny You probably mean Apache License.

**Comment by onovotny** [comment]
Yes, wasn’t looking

**Comment by ghuntley** [comment]
I've updated https://github.com/dotnet/reactive/pull/855 to use PackageLicenseExpression.

**Comment by onovotny** [comment]
Closing as fixed in master
