### ISSUE TITLE
ToUnit/ToSignal extension method

### ISSUE THREAD

**Issue by qrzychu** [dotnet/reactive#860]
As I stated in ReactiveUI [issue](https://github.com/reactiveui/ReactiveUI/issues/1885), it would be nice to have a ToUnit/ToSignal method, that would just change every observable to IObservable<Unit> to make composition of different signals much easier:

```
public static IObservable<Unit> ToUnit<T>(this IObservable<T> obs)
{
   return obs.Select(x => Unit.Default);
}

// also could be usefull, maybe with better name
public static IObservable<Unit> ToUnitWithBegin<T>(this IObservable<T> obs)
{
   return obs.Select(x => Unit.Default).StartWith(Unit.Default);
}
```

Sample usage (with RxUI):

```
Observable.Merge(
   this.WhenAnyValue(x => x.SomeInteger).ToUnit(),
   this.SomeCommand.ToUnit(),
   this.WhenAnyValue(x => x.SomeString).Where(x => !string.IsNullOrEmpty(x)).ToUnit()
)
.Throttle(TimeSpan.FromSeconds(0.2))
.InvokeCommand(FetchSomeData);
```

**Comment by akarnokd** [comment]
You can have your extension methods as you see fit. I'm not sure Rx.NET should include trivial transformations such as this.

**Comment by qrzychu** [comment]
It should, because it's trivial, everyone eventually will use this and I have to add that in every single project I use, which becomes problematic in huge solutions.

Or in new project. Or maybe there is a project with just trivial extensions for .NET that is on nuget?

**Comment by akarnokd** [comment]
Why not put it into your library which then you publish and reference from anywhere? I'm [doing the same](https://github.com/akarnokd/reactive-extensions) with a lot of non-trivial operators.
Also trivial doesn't mean common.

**Comment by JohanLarsson** [comment]
I don't mind the `ToUnit` extension method.
