### ISSUE TITLE
error CS0433: The type 'ISubject<T>' exists in both 

### ISSUE THREAD

**Issue by PayteR** [dotnet/reactive#872]
When i want to use ISubject or ReplaySubject duplicate type occurs

```
Services\OrderEventService.cs(10,26,10,46): error CS0433: The type 'ISubject<T>' exists in both 'System.Reactive.Interfaces, Version=3.0.0.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263' and 'System.Reactive, Version=4.0.0.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263'
```
my code
```
.
.
using System.Reactive.Subjects;
.
.
.
private readonly ISubject<OrderEvent> _eventStream = new ReplaySubject<OrderEvent>(1);
```
Tried to use all 4.x.x versions, same issue everywhere. Im using ASP.NET 2.2.0

**Comment by onovotny** [comment]
> Tried to use all 4.x.x versions, same issue everywhere. Im using ASP.NET 2.2.0

Do you mean ASP.NET Core 2.2?

You should only need `System.Reactive`. The other packages are for compatibility with libraries compiled against older versions. You don't need `System.Reactive.Interfaces`.

**Comment by PayteR** [comment]
Yes, ASP.NET Core 2.2

Sadly, adding just `System.Reactive` doesn't helped.

![image](https://user-images.githubusercontent.com/1248565/53380709-99bd0c00-396e-11e9-9275-9f07b1591d02.png)

**Comment by onovotny** [comment]
The type is in `System.Reactive.Subjects`:

https://github.com/dotnet/reactive/blob/3af72770f949e397d62b0bf35b668eab95f6cfba/Rx.NET/Source/src/System.Reactive/Subjects/ReplaySubject.cs#L10

Have you tried adding the using?

**Comment by PayteR** [comment]
Yes, i had like that from beginning. Check my first code
```
.
.
using System.Reactive.Subjects;
.
.
.
private readonly ISubject<OrderEvent> _eventStream = new ReplaySubject<OrderEvent>(1);
```

**Comment by onovotny** [comment]
Do you have a repro? It's hard to tell otherwise; the library is a regular `netstandard2.0` library and has all off those types in it. Not sure what could be happening here otherwise.

**Comment by PayteR** [comment]
No, it's a private project. Let me know, what files do you need to examine.

**Comment by danielcweber** [comment]
Check whether one of your other dependencies has a transitive dependency on a 3.x version of Rx. I ran into this too the other day. If so, add replace System.Reactive by System.Reactive.Compatibility in your main project.

**Comment by PayteR** [comment]
@danielcweber you're right, Package `GraphQL.Server.Transports.WebSockets (3.4.0)` have dependency of `System.Reactive (>= 3.1.1)` so that was the issue i think. Anyway, install of `System.Reactive.Compatibility' package solved the problem, thank you!
