### ISSUE TITLE
Should examples mention which package?

### ISSUE THREAD

**Issue by jzabroski** [dotnet/reactive#874]
https://github.com/dotnet/reactive/blob/c256fe28ef21146f5b670f5e39f96e3380203cb4/Ix.NET/Source/System.Interactive/System/Linq/Operators/Memoize.cs#L22-L34

A couple of things:
1. Example needs `<PackageReference Include="NUnit" Version="[3,)" />`
2. Example needs `<PackageReference Include="System.Interactive" Version="[3,)" />`

I was including a package reference to System.Reactive, which does not contain a Memoize method (but a Buffer method that has different semantics). I also did not realize this was in System.Interactive package at first.

**Comment by bartdesmet** [comment]
Given that these examples are defined inline in the code in the right assembly, I think including package information over there would be redundant. E.g. the file linked above is in `System.Interactive`, so it's reasonable to assume that one needs that assembly to run the code :-). The use of `Assert` is different though, and I don't have a good answer for that.

This said, the bigger question is where this documentation is exported in the form of HTML docs in an MSDN-like fashion. That'd be a logical place to have package information included. In fact, it'd also be an ideal place to have code samples be executable in the browser.

**Comment by jzabroski** [comment]
Sort of.  My PackageReference is a terse way to indicate when the API was included (3.0) via a viz `Version="[3,)"` - jQuery does stuff like that and it's super helpful, albeit Rx does not have as many versions as jQuery.

Agreed, on bigger questions, but I think you mean "MS Docs", not MSDN.
