### ISSUE TITLE
Unsubscribing from BehaviorSubject while OnNext is executing fails to unsubscribe immediately

### ISSUE THREAD

**Issue by sbergen** [dotnet/reactive#875]
Test case:
```
[Test]
public void UnsubscribeFromOnNext()
{
    var subject = new BehaviorSubject<int>(0);

    bool receivedValue = false;
    IDisposable subscription = null;
    subject.Subscribe(_ =>
    {
        if (subscription != null)
        {
            // Assume order of calls, even though it is not guaranteed (?),
            // otherwise the test doesn't make sense.
            Assume.That(receivedValue, Is.False);
            subscription.Dispose();
            subscription = null;
        }
    });
    subscription = subject.Subscribe(_ => receivedValue = true);

    receivedValue = false;
    subject.OnNext(0);
    subject.OnCompleted();

    Assume.That(subscription, Is.Null);
    Assert.IsFalse(receivedValue);
}
```

I get that the test case is a bit artificial and assumes execution order, but in a case where a subscription gets disposed along with a disposable object, this can end up calling code on the disposed object.

---
Some background info:
I initially encountered this issue in UniRx with `Subject`, so I started cross referencing with dotnet Rx. The underlying issue in UniRx is the use of immutable lists of observers, and indeed, `BehaviorSubject` uses `ImmutableList<IObserver<T>>`, which is a dangerous pattern. Perhaps adding a warning about its use might be a good idea :)

I also ran the test on all types deriving from `SubjectBase`, but this was the only failing case.

**Comment by akarnokd** [comment]
Hi. `BehaviorSubject` does not eagerly check for disposed `Observer`s when it signals events, thus disposing one from a previous observer has no effect on that particular emission round.
I don't know if it was intended or just a use case not considered the time `BehaviorSubject` was designed and implemented. /cc @bartdesmet

**Comment by bartdesmet** [comment]
In fact, this was done by design for *all subjects*, which mirror the design of event handlers in .NET that have snapshot semantics too, which eliminates the need for guarding against mutation (or supporting it for that matter) during event invocation.

It further eliminates the need to perform various checks and synchronization (or volatile field reads at best) in the invocation path when the list of observers (equivalent to delegates in a multicast delegate) is being enumerated.

**Comment by bartdesmet** [comment]
In fact, this was done by design for **all** subjects, which mirror the design of event handlers in .NET that have snapshot semantics too, which eliminates the need for guarding against mutation (or supporting it for that matter) during event invocation.

It further eliminates the need to perform various checks and synchronization (or volatile field reads at best) in the invocation path when the list of observers (equivalent to delegates in a multicast delegate) is being enumerated.

The design point here is that high-frequency invocation path should be as fast as possible, while pushing all extra cost to the subscribe/unsubscribe low-frequency path. For use cases where the churn in observers is high, but event volume is low, alternative subject implementations could be used, but that is not the main case we optimized for.

For comparison, here's the behavior for events:

```csharp
using System;

class C
{
  public event Action A;

  public void Do()
  {
    A?.Invoke();
  }
}

var c = new C();

Action h2 = () => { Console.WriteLine("Second"); };
Action h1 = () => { Console.WriteLine("First"); c.A -= h2; };

c.A += h1;
c.A += h2;

c.Do(); // Prints First and Second
c.Do(); // Prints First

```

The whole implementation using the immutable list is completely analogous to the code emitted for events, where immutable delegates are `Interlocked.CompareExchange`-ed to the event's backing field in a prepare-commit fashion.

Changing this behavior for **any** subject is definitely a breaking change, not only for cases where events get converted to observables and one expects to retain the original behavior, but also for users who rely on this behavior. These are the very subtle kind of breaking changes where chasing the absence of a side-effect due to an upgrade of some library can cause major grief.

**Comment by bartdesmet** [comment]
In fact, looking at the [PR](https://github.com/dotnet/reactive/pull/511/files) that changed this behavior for `Subject<T>`, I'm seeing that each `On*` method invocation on the subject is now having an additional `null` check and a `volatile` field read for each observer in the list, which is worrisome for performance.

Subjects have been built for high degrees of fan-out while having occasional subscribe/unsubscribe operations that don't intersect with the invocation path. The typical test case for subject throughput is to create a subject, attach a million observers to it, and measure the time it takes to notify all of them by calling `OnNext`.

**Comment by bartdesmet** [comment]
Breaking change regression test:

```csharp
Subject<int> s = new Subject<int>();

var d2 = new SingleAssignmentDisposable();

var s1 = s.Subscribe(_ => { Console.WriteLine("First"); d2.Dispose(); });
var s2 = s.Subscribe(_ => { Console.WriteLine("Second"); });
d2.Disposable = s2;

s.OnNext(42);
s.OnNext(42);
```

In v3.0, prints "First, Second, First". In v4.15, prints "First, First". This regression **should** be fixed.

**Comment by akarnokd** [comment]
There was a benchmark measuring Subject: #775. The zero observer case got worse because of the field-virtual call was replaced by an array length check overhead. The one observer case was worse because a field-virtual call was replaced by an array-length, array-lookup and virtual call.

**Comment by bartdesmet** [comment]
Quick benchmark for the case of many observers:

**4.1.5**

```
RxSubjectBenchmark.OnNext: Core(Runtime=Core)
Runtime = .NET Core 3.0.0-preview4-27413-8 (CoreCLR 4.6.27413.71, CoreFX 4.7.19.11304), 64bit RyuJIT; GC = Concurrent Workstation
Mean = 5.0829 ms, StdErr = 0.0401 ms (0.79%); N = 91, StdDev = 0.3825 ms
Min = 4.2442 ms, Q1 = 4.8097 ms, Median = 5.1026 ms, Q3 = 5.3229 ms, Max = 6.0935 ms
IQR = 0.5132 ms, LowerFence = 4.0398 ms, UpperFence = 6.0927 ms
ConfidenceInterval = [4.9464 ms; 5.2193 ms] (CI 99.9%), Margin = 0.1364 ms (2.68% of Mean)
Skewness = 0.22, Kurtosis = 2.93, MValue = 3.62
-------------------- Histogram --------------------
[4.170 ms ; 4.335 ms) | @
[4.335 ms ; 4.484 ms) | @@@@@@
[4.484 ms ; 4.626 ms) | @@@
[4.626 ms ; 4.786 ms) | @@@@@@@@
[4.786 ms ; 4.935 ms) | @@@@@@@@@@@@@@@
[4.935 ms ; 5.068 ms) | @@@@@@
[5.068 ms ; 5.216 ms) | @@@@@@@@@@@@@@@@@@@@@@@
[5.216 ms ; 5.464 ms) | @@@@@@@@@@@@@@@@@
[5.464 ms ; 5.641 ms) | @@@@@
[5.641 ms ; 5.802 ms) | @@@@
[5.802 ms ; 5.968 ms) |
[5.968 ms ; 6.117 ms) | @@@
---------------------------------------------------

// * Summary *

BenchmarkDotNet=v0.11.5, OS=Windows 10.0.17134.648 (1803/April2018Update/Redstone4)
Intel Core i7-6600U CPU 2.60GHz (Skylake), 1 CPU, 4 logical and 2 physical cores
.NET Core SDK=3.0.100-preview4-010326
  [Host] : .NET Core 3.0.0-preview4-27413-8 (CoreCLR 4.6.27413.71, CoreFX 4.7.19.11304), 64bit RyuJIT
  Core   : .NET Core 3.0.0-preview4-27413-8 (CoreCLR 4.6.27413.71, CoreFX 4.7.19.11304), 64bit RyuJIT

Job=Core  Runtime=Core

| Method |     Mean |     Error |    StdDev |
|------- |---------:|----------:|----------:|
| OnNext | 5.083 ms | 0.1364 ms | 0.3825 ms |
```


**3.1.1**

```
RxSubjectBenchmark.OnNext: Core(Runtime=Core)
Runtime = .NET Core 3.0.0-preview4-27413-8 (CoreCLR 4.6.27413.71, CoreFX 4.7.19.11304), 64bit RyuJIT; GC = Concurrent Workstation
Mean = 4.6024 ms, StdErr = 0.0263 ms (0.57%); N = 53, StdDev = 0.1918 ms
Min = 4.3698 ms, Q1 = 4.4619 ms, Median = 4.5325 ms, Q3 = 4.7411 ms, Max = 5.1545 ms
IQR = 0.2791 ms, LowerFence = 4.0432 ms, UpperFence = 5.1598 ms
ConfidenceInterval = [4.5105 ms; 4.6942 ms] (CI 99.9%), Margin = 0.0919 ms (2.00% of Mean)
Skewness = 1.15, Kurtosis = 3.83, MValue = 2.55
-------------------- Histogram --------------------
[4.325 ms ; 4.424 ms) | @@@@@@
[4.424 ms ; 4.604 ms) | @@@@@@@@@@@@@@@@@@@@@@@@@@@
[4.604 ms ; 4.727 ms) | @@@@@
[4.727 ms ; 4.919 ms) | @@@@@@@@@@@@
[4.919 ms ; 5.181 ms) | @@@
---------------------------------------------------

// * Summary *

BenchmarkDotNet=v0.11.5, OS=Windows 10.0.17134.648 (1803/April2018Update/Redstone4)
Intel Core i7-6600U CPU 2.60GHz (Skylake), 1 CPU, 4 logical and 2 physical cores
.NET Core SDK=3.0.100-preview4-010326
  [Host] : .NET Core 3.0.0-preview4-27413-8 (CoreCLR 4.6.27413.71, CoreFX 4.7.19.11304), 64bit RyuJIT
  Core   : .NET Core 3.0.0-preview4-27413-8 (CoreCLR 4.6.27413.71, CoreFX 4.7.19.11304), 64bit RyuJIT

Job=Core  Runtime=Core

| Method |     Mean |     Error |    StdDev |
|------- |---------:|----------:|----------:|
| OnNext | 4.602 ms | 0.0919 ms | 0.1918 ms |
```

**Comment by akarnokd** [comment]
How is the memory usage?

**Comment by bartdesmet** [comment]
> 

In terms of allocations incurred by `OnNext`, 0 in both cases, as expected:

```csharp
| Method | Gen 0 | Gen 1 | Gen 2 | Allocated |
|------- |------:|------:|------:|----------:|
| OnNext |     - |     - |     - |         - |
```

In terms of memory used by the subject to hold the subscriber list, I've just done the quick-and-dirty approach below to get a ballpark estimate:

```csharp
var b = GC.GetTotalMemory(true);

for (var i = 0; i < SubscriberCount; i++)
{
    s.Subscribe(_ => { });
}

Console.WriteLine(GC.GetTotalMemory(true) - b);
```

which yields:

**3.1.1**
56360 bytes

**4.1.5**
88312 bytes

**Comment by akarnokd** [comment]
This is what I get on my current machine:

#### 3.1.1
// * Summary *

BenchmarkDotNet=v0.11.5, OS=Windows 7 SP1 (6.1.7601.0)
Intel Core i7-4770K CPU 3.50GHz (Haswell), 1 CPU, 8 logical and 4 physical cores

Frequency=3418007 Hz, Resolution=292.5682 ns, Timer=TSC
.NET Core SDK=2.1.602
  [Host]     : .NET Core 2.1.9 (CoreCLR 4.6.27414.06, CoreFX 4.6.27415.01), 64bit RyuJIT
  DefaultJob : .NET Core 2.1.9 (CoreCLR 4.6.27414.06, CoreFX 4.6.27415.01), 64bit RyuJIT


| Method |     Mean |     Error |    StdDev | Gen 0 | Gen 1 | Gen 2 | Allocated|
|------- |---------:|----------:|----------:|------:|------:|------:|----------:|
| OnNext | 3.764 ms | 0.0078 ms | 0.0073 ms |     - |     - |     - |         -|


#### 4.1.5

// * Summary *

BenchmarkDotNet=v0.11.5, OS=Windows 7 SP1 (6.1.7601.0)
Intel Core i7-4770K CPU 3.50GHz (Haswell), 1 CPU, 8 logical and 4 physical cores

Frequency=3418007 Hz, Resolution=292.5682 ns, Timer=TSC
.NET Core SDK=2.1.602
  [Host]     : .NET Core 2.1.9 (CoreCLR 4.6.27414.06, CoreFX 4.6.27415.01), 64bit RyuJIT
  DefaultJob : .NET Core 2.1.9 (CoreCLR 4.6.27414.06, CoreFX 4.6.27415.01), 64bit RyuJIT


| Method |     Mean |     Error |    StdDev | Gen 0 | Gen 1 | Gen 2 | Allocated|
|------- |---------:|----------:|----------:|------:|------:|------:|----------:|
| OnNext | 3.769 ms | 0.0076 ms | 0.0064 ms |     - |     - |     - |         -|

**Comment by bartdesmet** [comment]
It seems performance is within the range of noise then.

Either way, the change is a breaking change for the reasons described above and should be reconsidered. The following concisely summarizes the observable-event equivalence in behavior:

```csharp
class C
{
    public event Action<int> Event;
    public IObservable<int> EventAsObservable;

    public C()
    {
        EventAsObservable = Observable.FromEvent<int>(h => Event += h, h => Event -= h);
    }

    public IEnumerable<int> WithEvent()
    {
        var xs = new List<int>();

        Action<int> h1 = null;
        Action<int> h2 = null;

        h1 = (int x) => { xs.Add(x); Event -= h2; };
        h2 = (int x) => { xs.Add(x); };

        Event += h1;
        Event += h2;

        Event?.Invoke(42);

        return xs;
    }

    public IEnumerable<int> WithObservable()
    {
        var xs = new List<int>();

        var h1 = new SingleAssignmentDisposable();
        var h2 = new SingleAssignmentDisposable();

        h1.Disposable = EventAsObservable.Subscribe((int x) => { xs.Add(x); h2.Dispose(); });
        h2.Disposable = EventAsObservable.Subscribe((int x) => { xs.Add(x); });

        Event?.Invoke(42);

        return xs;
    }

    public void Test()
    {
        Assert.Equal(WithEvent(), WithObservable());
    }
}
```

`new C().Test()` fails on 4.x and passes on 3.x.

**Comment by sbergen** [comment]
Thanks for the comments! It seems what I thought was a fix, was a regression after all.

I'm sorry if this is a bit off topic, but I have a few questions related to this which I'd really appreciate some input on:

1) I tried to search for documentation on what the expected behavior should be, but failed to find any. Where should such documentation be found if it exists?

2) The case where this (intended) behavior is problematic is when publishing a value terminates a certain state in the application, causing other observers to be disposed. This then ends up calling into the disposed objects afterwards. Is there any common pattern to mitigate this issue?

**Comment by akarnokd** [comment]
1. Unfortunately, there isn't any documentation or unit tests for such behavior at the moment.
2. Depends on how directly those observers are connected to the subject. If through some standard operator, it is likely those operator's auto-detach behavior will prevent the delivery of signals.
