### ISSUE TITLE
System.Windows references when installing the package

### ISSUE THREAD

**Issue by apobekiaris** [dotnet/reactive#878]
Create a new Windows Desktop class lib and Install the package and you will get references to `System.Windows`, `System.Windows.Forms`, `WindowsBase` assemblies. The only reference I can found was this 2010 post https://social.msdn.microsoft.com/Forums/en-US/a1ec0664-4966-400c-a744-ab91ffe320ae/observeon-requires-project-reference-to-windowsbase-and-winforms?forum=rx, 

hoping that maybe 9 years later there is a better solution?

**Comment by onovotny** [comment]
If you use PackageReference, NuGet should add the framework references for you. You can update from Packages.config -> PackageReference in VS 2017 15.9 and in VS 2019 by right clicking them and selecting to update.

**Comment by apobekiaris** [comment]
I cannot follow your suggestion, the problem is that I get unwanted references in an platform agnostic lib how the PackageReference will help me? 

I have to report back to my platform agnostic framework users which now depends on System.Reactive as to the why they have to manually remove these reference for every installation.

**Comment by onovotny** [comment]
Those references are only in the .NET Framework version of the assembly, not the .NET Standard version. People using the .NET Standard version won't get those references.

**Comment by tfabian** [comment]
I have the same opinion. Why are there references like WinForms in the System.Reactive nuget? We don't need them in Console applications, windows services, WPF etc. In the past, in RX 2.x the dispatcher was nicely separated into Rx-XAML nuget and so on. I understand the benefits of merging Rx-Core and Rx-Interfaces into one assembly, but references of System.Windows* and WindowsBase in System.Reactive are unnecessary and unwanted even in dotNet Framework.

Thank you
