### ISSUE TITLE
System.InvalidOperationException: An asynchronous operation cannot be started at this time.

### ISSUE THREAD

**Issue by apobekiaris** [dotnet/reactive#884]
I am wrapping .NET events and consuming them from an ASP.NET WebForms application.

One of my queries looks like 
```cs
RxApp.Application
            .WhenModule(typeof(ViewEditModeModule))
            .DetailViewCreated()
            .ViewEditModeChanging()
            .SubScribe();
```

I do not unsubscribe explicitly in the main query as all my extensions do it internally. The `ViewEditMoeChaning` extension is defined like

```cs
public static IObservable<(DetailView detailView, CancelEventArgs e)> WhenViewEditModeChanging(this DetailView detailView){
            return Observable.FromEventPattern<EventHandler<CancelEventArgs>, CancelEventArgs>(
                    h => detailView.ViewEditModeChanging += h, h => detailView.ViewEditModeChanging -= h)
                .TakeUntil(detailView.WhenDisposingView())
                .TransformPattern<CancelEventArgs, DetailView>();
        }

        public static IObservable<(DetailView detailView, CancelEventArgs e)> ViewEditModeChanging<T>(this IObservable<T> source) where T : DetailView{
            return source.SelectMany(_ => _.WhenViewEditModeChanging());
        }
```

so for clean up there is a `.TakeUntil(detailView.WhenDisposingView())` similar I do for all my extensions. 

The exception:
>System.InvalidOperationException: An asynchronous operation cannot be started at this time. Asynchronous operations may only be started within an asynchronous handler or module or during certain events in the Page lifecycle. If this exception occurred while executing a Page, ensure that the Page is marked <%@ Page Async="true" %>. This exception may also indicate an attempt to call an "async void" method, which is generally unsupported within ASP.NET request processing. Instead, the asynchronous method should return a Task, and the caller should await it.
   at System.Web.AspNetSynchronizationContext.OperationStarted()

 It relates to the `WhenDisposingView` which is defined like:
```cs
public static IObservable<Unit> WhenDisposingView<TView>(this TView view) where TView:View{
            return Observable.Return(view).Disposing();
        }

        public static IObservable<Unit> Disposing<TView>(this IObservable<TView> source) where TView:View{
            return source.Select(item => Observable.FromEventPattern<CancelEventHandler, EventArgs>(handler => item.Disposing += handler,handler => item.Disposing -= handler))
            .Concat().ToUnit();
        }
```

if I return an Observable.Empty instead of FromEvent the web site works fine. 

Any ideas guidance much appreciated.

**Comment by akarnokd** [comment]
My guess is there is an async method call on the chain after `WhenViewEditModeChanging()` that could react to the `OnCompleted` of `TakeUntil`.

**Comment by akarnokd** [comment]
Closing due to age and lack of further feedback.
