### ISSUE TITLE
Subscribe to an IAsyncObservable<T> interface?

### ISSUE THREAD

**Issue by ronMilne** [dotnet/reactive#894]
What package(s) do I need to use the extension methods defined within AsyncObservableExtensions.cs defined within AsyncRx.NET/System.Reactive.Async.Core/System?

There seems to be no documentation or examples on this.

**Comment by NickDarvey** [comment]
This isn't available as a package right now as [AsyncRx.NET is a prototype](https://github.com/dotnet/reactive/pull/435#issuecomment-369986735). You can try it out if you check out this repo and build it yourself. There's no usage docs or examples but you'll find it's much the same as Rx.NET.

There might be other ways to achieve what you're looking for. Which particular extension method were you looking at in there and what were you trying to achieve? (e.g. were you trying to do an async call inside an OnNext?)
