### ISSUE TITLE
Consider using Microsoft.Bcl.AsyncInterfaces for IAsyncEnumerable

### ISSUE THREAD

**Issue by pakrym** [dotnet/reactive#897]
Now that `Microsoft.Bcl.AsyncInterfaces` (https://github.com/dotnet/corefx/blob/bfcbf22e72bd5f814af92c0980993a8b4e9c7232/src/Microsoft.Bcl.AsyncInterfaces/ref/Microsoft.Bcl.AsyncInterfaces.cs) is being produced, contains relevant IAsyncEnumerable interfaces and targets netstandard2.0 consider using it for netstandard2.0/2.1 builds of `System.Linq.Async`

cc @onovotny

**Comment by onovotny** [comment]
Will do once it's on NuGet.org.
