### ISSUE TITLE
Native toolchain OutOfMemory error in ilc.exe or nutc_driver.exe

### ISSUE THREAD

**Issue by rainerg2000** [dotnet/reactive#899]
In a Xamarin.forms project on UWP I can't use the native compile toolchain. Somehow the combination of System.Reactive, ReactiveUI, ReactiveUI.Xamforms
leads to build failures in the native compile toolchain. I've seen either ilc.exe or nutc_driver.exe run out of memory.

Attached is a Xamarin.Forms starter app from VS2019's new project generator. Building it in Debug works fine, building in Release fails as described.
[TestNativeToolchain.zip](https://github.com/dotnet/reactive/files/3168025/TestNativeToolchain.zip)

With older versions ReactiveUI 8.7.2 and System.Reactive 4.0.0 the project is buildable with native toolchain.

**Comment by danielcweber** [comment]
Yes, we managed to break the native compiler a while ago with our recent optimizations to Rx ;-)
I don't know about the current state, maybe @onovotny does. Development on the compiler is not done in  public.

Can you confirm you're using the latest in all your tools?

**Comment by rainerg2000** [comment]
Yes, I confirmed that ilc.exe and nutc_driver.exe abort with OutOfMemory errors using runtime.win10-x86.microsoft.net.native.compiler\2.2.3
Also confirmed that I'm using the latest ReactiveUI and ReactiveUI.Xamforms (9.15.1)

**Comment by MattWhilden** [comment]
As you've noticed, the various processes that power the .NET Native compiler are 32 bit processes. For simplicity you can think of ilc as "the orchestrator that contains various analysis functionality" and nutc_driver as "the native code generator and optimizer". These are both shipped to y'all as native binaries to optimize throughput performance of your builds (you've probably noticed that whole program optimization isn't cheap!).

Fortunately, starting with 6.X versions of Microsoft.NETCore.UniversalWindowsPlatform (and for folks targeting a MinSDK version of 16299+), we have a 64 bit version of of nutc_driver that folks having issues can opt in to. Adding this property to your UWP project should trigger the 64 bit compiler:
`
<Use64BitCompiler>true</Use64BitCompiler>
`
Adding that to TestNativeToolchain.UWP in your example project allows it to complete compilation.

To my knowledge, the only component that is aware of this flag is our tooling so you shouldn't see any other side effects. Further, that setting flows into the your Store submission so you don't need to worry about that.

OutOfMemory issues with ilc are a bit more tricky as we don't ship a 64 bit version of that yet. This is mostly a function of that class of failure being sufficiently rare as to not warrant investment. We're always open to feedback about that though!

Hope that helps. Certainly let me know if there's other issues.

**Comment by onovotny** [comment]
Closing as the answer is use the 64 bit. Pinning so it stays near the top.

**Comment by rainerg2000** [comment]
I confirmed that <Use64BitCompiler>true</Use64BitCompiler>
solves the problem for my small test program, which was running OutOfMemory in nutc_driver.exe
(unfortunately then I am running into another known issue [RHBIND error RHB0002](https://social.msdn.microsoft.com/Forums/en-US/75eae4c0-2603-4d52-9981-a1b017bf66c3/rhbind-error-rhb0002-failed-to-write-pdb-on-vs-2019?forum=windowsstore)

**Comment by FrancoisM** [comment]
I have Error : ILT0005 with:
runtime.win10-x86.microsoft.net.native.compiler\2.2.7-rel-27913-00\tools\x86\ilc\Tools64\nutc_driver.exe

As you see I'm already using Tools64. How do I know if it's the ilc memory issue described by @MattWhilden https://github.com/MattWhilden?

**Comment by MattWhilden** [comment]
@FrancoisM just getting back from paternity leave so sorry for the delay. If you have logging set to diagnostic (Tools > Options > Projects and Solutions > Build and Run > set the boxes to "Diagnostic") and redo the build, I'd expect to see an "out of memory" message from nutc_driver in that log. 

If it remains opaque, you can always send me an [ilcRepro](https://github.com/dotnet/core/blob/master/Documentation/ilcRepro.md) file and I'm happy to take a closer look.
