### ISSUE TITLE
ISubject is not marked as SecurityCritical but still triggering CA2146

### ISSUE THREAD

**Issue by jahmai** [dotnet/reactive#91]
I'm using Rx 2.2.5 in Xamarin.iOS/Android projects, linking to \lib\portable-windows8+net45+wp8*.
I'm getting the following warning from one of our custom subjects, but I cannot figure out why:

CA2146 : Microsoft.Security : Transparent or safe-critical type 'SafeSubject<T>' derives from critical type 'ISubject<T>' in violation of the transparency inheritance rules.  'SafeSubject<T>' must be critical to derive from a critical type or implement a critical interface.  

ISubject doesn't appear to be marked as security critical, nor does the assembly it is defined in.
This doesn't happen in our windows projects when we link to \lib\net45*.

It is in packages.config as:

  `<package id="Rx-Interfaces" version="2.2.5" targetFramework="xamarinios10" />`

Any ideas?

**Comment by bartdesmet** [comment]
I'm following up on this with the .NET Framework / CLR team. It seems to be the same issue as http://stackoverflow.com/questions/28280533/what-causes-an-interface-or-assembly-to-become-marked-security-critical.

**Comment by kpanwar** [comment]
Any updates on this @bartdesmet ?

**Comment by akarnokd** [comment]
Is this still a problem?

**Comment by jahmai** [comment]
I'm the raiser and haven't seen this issue in Xamarin/netfx/netcore/netstandard projects for quite some time. Sorry, I forgot I raised this!
