### ISSUE TITLE
Does System.Reactive.Concurrency.DefaultScheduler depend on the Windows Task Scheduler service in any way?

### ISSUE THREAD

**Issue by markashleybell** [dotnet/reactive#967]
Sorry for posting a question in the issue tracker; this may seem like a crazy question to anyone who knows the library well, but the answer has proved very difficult to Google... 

Does `System.Reactive.Concurrency.DefaultScheduler` depend on the Windows Task Scheduler service in any way? 

I'm using the `Scheduler.Default.SchedulePeriodic` method in the start method of a Windows Service written in C#. If I try to start it automatically when the server it's running on boots (ServiceStartMode.Automatic), the service startup times out, but it will start fine a minute or so later.

Before I go deeper into trying to diagnose the problem, I'm trying to rule out the fact that my service has a dependency on another service which I haven't declared in the installer.

I've tried looking through the source here, but obviously searching for combinations of "Task" and "Scheduler" returns a huge number of results (as I'd expect!) and everything is very abstracted, so I'm just not getting anywhere.

Can anyone enlighten me, please?

**Comment by bartdesmet** [comment]
There is no such dependency.

**Comment by markashleybell** [comment]
Great, thanks for the clarification.
