### ISSUE TITLE
Using/Finally execution order is wrong

### ISSUE THREAD

**Issue by eugbaranov** [dotnet/reactive#977]
I have expected that dispose will only happen after finalizer has been run, but the following proves that wrong:

	Observable.Using(
		() => Disposable.Create(() => Console.WriteLine("disposed")),
		_ => Observable.Return(0).Finally(() => Console.WriteLine("finalized"))).Dump();

Output shows that it disposed the resource first and only then ran the finalization action.

**Comment by eugbaranov** [comment]
Looks like Using/Using order is incorrect too, expanding previous sample to:

	Observable.Using(
		() => Disposable.Create(() => Console.WriteLine("outer disposed")),
		x => Observable.Using(
			() => Disposable.Create(() => Console.WriteLine("inner disposed")),
			y => Observable.Empty(0).Finally(() => Console.WriteLine("finalized")))).Dump();

Displays:
1. outer disposed
2. inner disposed
3. finalized

But the order should be reverse.

**Comment by quinmars** [comment]
That should already be fixed in the `master`, see #829 and #832. Apparently, it was never cherry picked into the `rel/4.1` release branch.

**Comment by eugbaranov** [comment]
I haven't realised that a change from almost a year old PR hasn't been released yet.
Checked against latest 4.2-preview NuGet and it works as expected.
Any idea when 4.2 will be out or whether this can indeed be cherry-picked onto 4.1?

**Comment by onovotny** [comment]
We're aiming to ship 4.2 along with .NET Core 3 in late September. I can see about a cherry-pick.

**Comment by onovotny** [comment]
4.1.6 was just published with this fix.

**Comment by eugbaranov** [comment]
Thanks!
