### ISSUE TITLE
Publish: run custom start logic on Connect

### ISSUE THREAD

**Issue by eugbaranov** [dotnet/reactive#983]
Is there a way to specify additional action to be run when connecting to published observable?

To demonstrate my case imagine the following application:

    public sealed class PublishTest
    {
        private CancellationTokenSource _cts;
        
        public event Action<int> Tick;
        public void Start() => Task.Run(() => Generate((_cts = new CancellationTokenSource()).Token));
        public void Stop() { _cts?.Cancel(); }
    
        private async Task Generate(CancellationToken cancellationToken)
        {
            for (int i = 0; !cancellationToken.IsCancellationRequested; i++)
            {
                Tick?.Invoke(i);
                await Task.Delay(1000, cancellationToken);
            }
        }
    }
    
    void Main()
    {
        var events = Observable.Defer(() =>
        {
            var p = new PublishTest();
            p.Start();
            return Observable.FromEvent<int>(h => p.Tick += h, h => p.Tick -= h)
                             .Publish()
                             .RefCount();
        });
        events.Dump();
    }

Currently the first event will be most certainly missed because ideally `p.Start()` needs to happen after observers had a change to subscribe - on connect.

It would be very useful to be able to say something like:

    return Observable.FromEvent<int>(h => p.Tick += h, h => p.Tick -= h)
                     .Publish(() =>
                     {
                         p.Start();
                         return Disposable.Create(() => p.Stop());
                     })
                     .RefCount();

**Comment by akarnokd** [comment]
If I understand correctly, you need to bridge the time window between p.Start and the FromEvent to handle the incoming observer from downstream. This could be done with a so-called [`UnicastSubject`](https://github.com/akarnokd/reactive-extensions/blob/master/reactive-extensions/UnicastSubject.cs) not part of Rx.NET at the moment:

```cs
var events = Observable.Defer(() =>
    {
        var p = new PublishTest();

        // us will buffer items until a single observer subscribes, 
        // then relays the rest directly
        var us = new UnicastSubject<T>(onTerminate: () => p.Stop());

        // this will link up a receiver (us) for the events before the generator is started
        Observable.FromEvent<int>(h => p.Tick += h, h => p.Tick -= h)
            .Subscribe(us);

        // this is now safe, us will buffer until it gets exposed to the
        // downstream consumer
        p.Start();

        return us;
    })
    .Publish()
    .RefCount();

    events.Dump();
```

**Comment by eugbaranov** [comment]
Actually, I realised there is a simpler solution using `Observable.Create`:

    var events = Observable.Create<int>(observer =>
    {
        var p = new PublishTest();
        var subscription = Observable.FromEvent<int>(h => p.Tick += h, h => p.Tick -= h)
                                     .Finally(() => p.Stop())
                                     .Subscribe(observer);
        p.Start();
        return subscription;
    });
