### ISSUE TITLE
Strong name signature could not be verified.

### ISSUE THREAD

**Issue by aalmada** [dotnet/reactive#984]
I'm getting the following error when building my project, that depends on `System.Interactive`, using an Azure DevOps pipeline:

`System.IO.FileLoadException : Could not load file or assembly 'System.Interactive, Version=4.0.0.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263' or one of its dependencies. Strong name signature could not be verified.  The assembly may have been tampered with, or it was delay signed but not fully signed with the correct private key. (Exception from HRESULT: 0x80131045)`

It happens for both `3.2.0` and `4.0.0` versions of `System.Interactive`.

**Comment by onovotny** [comment]
We haven't seen this before, is there more information you can provide? OS, build, platform, repro steps?

**Comment by aalmada** [comment]
I'm using a Microsoft-hosted agent with `windows-2019` image with the following pipeline definition: https://github.com/NetFabric/NetFabric.Hyperlinq/blob/bb3ae83453c808f8bc4aec7809ad88d3474957b1/azure-pipelines.yml

It installs .NET Core `3.0.100-preview7-012821` before building.

It's a unit testing project that targets `net461`and `netcoreapp2.1`: https://github.com/NetFabric/NetFabric.Hyperlinq/blob/bb3ae83453c808f8bc4aec7809ad88d3474957b1/NetFabric.Hyperlinq.UnitTests/NetFabric.Hyperlinq.UnitTests.csproj

Here's the build log: https://dev.azure.com/aalmada/NetFabric.Hyperlinq/_build/results?buildId=225

It fails when executing the unit tests that uses a class from `System.Interactive`.

**Comment by onovotny** [comment]
Coverlet modifies the files under test, which is what's leading to your error. You should exclude the Rx/Ix libraries from being instrumented by Coverlet as you're not collecting coverage for those.

**Comment by aalmada** [comment]
Oh! Thanks! I had no idea...

**Comment by aalmada** [comment]
I can now confirm that, excluding ```System.Interactive``` assembly from ```coverlet``` coverage, fixes the issue. Thanks for the help!
